### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by Pandoroz** [marticliment/WingetUI#1149]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
When I try to start the program (among other things it doesn't identify it as an application on windows) it hangs at the "start daemons". After clicking to skip launch, no online packages appear on the main menu.

## To Reproduce
Steps to reproduce the behaviour:
1. I install the program
2. I start the program

## Expected behaviour
I thought that after the first boot everything was fine without any strange bugs, but obviously I am not so lucky

## Screenshots
![image](https://github.com/marticliment/WingetUI/assets/128830542/cb4358a3-f864-4deb-883a-30e6714f59f2)
![image](https://github.com/marticliment/WingetUI/assets/128830542/fad55f36-7ea8-4075-8e07-f5df962d7a81)

## The Log

<details>

```
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.002270936965942383 to load all language files
🟢 checkQueue Thread started!
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
🔵 Starting update check
🔵 Language file up-to-date
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1687348596.770896]
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'WingetFound': True, 'WingetVersion': 'v1.5.1572\r', 'PipFound': True, 'PipVersion': 'pip 23.1.2 from C:\\Users\\david\\AppData\\Roaming\\Python\\Python39\\site-packages\\pip (python 3.9)\r\r', 'NpmFound': True, 'NpmVersion': '9.6.6', 'ChocolateyFound': True, 'ChocolateyVersion': '1.4.0\r', 'ScoopFound': False}
🔵 Reached main ui load milestone
🔵 Is Dark
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for available packages
🔵 Starting Scoop search for available packages
🔵 Starting Chocolatey search for available packages
🟠 Scoop cache file exists but is empty!
🔵 Starting Scoop package caching
🟢 Found valid, non-empty cache file for Chocolatey!
🟢 Found valid, non-empty cache file for Winget!
🔵 Starting Winget package caching
🟢 Winget search for installed packages finished with 4800 result(s)
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 9429 result(s)
Can't disconnect
Can't disconnect
🟢 Scoop packages cached successfuly
🔵 Starting Scoop search for available packages
🟠 Scoop cache file exists but is empty!
🔴 Could not load Scoop packages, returning an empty list!
Can't disconnect
🟢 Install tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting Pip search for installed packages
🔵 Starting Npm search for installed packages
🟢 Searching for string ""
Can't disconnect
🟢 Settings tab loaded!
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\uiSections.py", line 1233, in __init__

🔴   File ".\uiSections.py", line 1233, in __init__

🔴 KeyError: 'ScoopVersion'

🔴 KeyError: 'ScoopVersion'

🔴 Note this traceback was caught by reporter and has been added to the log ('ScoopVersion')
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\uiSections.py", line 1234, in __init__

🔴   File ".\uiSections.py", line 1234, in __init__

🔴 AttributeError: 'NoneType' object has no attribute 'setTextAlignment'

🔴 AttributeError: 'NoneType' object has no attribute 'setTextAlignment'

🔴 Note this traceback was caught by reporter and has been added to the log ('NoneType' object has no attribute 'setTextAlignment')
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\uiSections.py", line 1234, in __init__

🔴   File ".\uiSections.py", line 1234, in __init__

🔴 AttributeError: 'NoneType' object has no attribute 'setTextAlignment'

🔴 AttributeError: 'NoneType' object has no attribute 'setTextAlignment'

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\uiSections.py", line 1241, in __init__

🔴   File ".\uiSections.py", line 1241, in __init__

🔴 AttributeError: 'NoneType' object has no attribute 'setTextAlignment'

🔴 AttributeError: 'NoneType' object has no attribute 'setTextAlignment'

🔴 Note this traceback was caught by reporter and has been added to the log ('NoneType' object has no attribute 'setTextAlignment')
🟢 About tab loaded!
🟢 Main application loaded...
Win32Mica Error: win32 version 19044 is not supported
🟢 Pip search for installed packages finished with 53 result(s)
🟢 Total packages: 1262
🟢 Total packages: 8393
🟢 Total packages: 14229
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🟢 Npm search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 Scoop search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🔵 Starting Pip search for updates
🔵 Starting Chocolatey search for updates
🔵 Starting Scoop search for updates
🔵 Starting Npm search for updates
🔵 Starting Winget search for updates
🟢 Npm search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Scoop search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 171 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 226
🟢 Winget packages cached successfuly
🟢 Winget search for updates finished with 101 result(s)
🟡 Package Libretro.RetroArch version Unknown is ignored
🟢 Searching for string ""
🟢 Pip search for updates finished with 28 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 44
🔵 Loading log...
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

```

</details>

**Comment by ppvnf** [comment]
You could also enable this  if you prefer
<img width="605" alt="Screenshot 2023-06-21 143522" src="https://github.com/marticliment/WingetUI/assets/73800734/7c238fac-c473-4af1-8207-6b066069c2a0">

**Comment by Pandoroz** [comment]
Oh, now it finds the packages, now how would I fix the boot? it doesn't detect it as a program and freezes on startup

**Comment by marticliment** [comment]
> Oh, now it finds the packages, now how would I fix the boot? it doesn't detect it as a program and freezes on startup

This issue has already been reported and will be fixed soon. To avoid the hang, please go to Settings -> Scoop Package Manager Preferences -> Uncheck "enable scoop"

**Comment by Pandoroz** [comment]
Ah okay perfect, fixed the block thanks a lot :)
