### ISSUE TITLE
[BUG] several stack traces in the logfile

### ISSUE THREAD

**Issue by erwindon** [marticliment/WingetUI#1257]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The logfile (of just the log) has several stack traces that may be worth an improved handling.
I've added a few that occured recently.

In this stack trace, all lines are present twice:
```
🔴 Traceback (most recent call last):
🔴 Traceback (most recent call last):
🔴   File "urllib\request.py", line 1348, in do_open
🔴   File "urllib\request.py", line 1348, in do_open
🔴   File "http\client.py", line 1283, in request
🔴   File "http\client.py", line 1283, in request
🔴   File "http\client.py", line 1329, in _send_request
🔴   File "http\client.py", line 1329, in _send_request
🔴   File "http\client.py", line 1278, in endheaders
🔴   File "http\client.py", line 1278, in endheaders
🔴   File "http\client.py", line 1038, in _send_output
🔴   File "http\client.py", line 1038, in _send_output
🔴   File "http\client.py", line 976, in send
🔴   File "http\client.py", line 976, in send
🔴   File "http\client.py", line 1455, in connect
🔴   File "http\client.py", line 1455, in connect
🔴   File "ssl.py", line 517, in wrap_socket
🔴   File "ssl.py", line 517, in wrap_socket
🔴   File "ssl.py", line 1075, in _create
🔴   File "ssl.py", line 1075, in _create
🔴   File "ssl.py", line 1346, in do_handshake
🔴   File "ssl.py", line 1346, in do_handshake
🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)
🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)
🔴 During handling of the above exception, another exception occurred:
🔴 During handling of the above exception, another exception occurred:
🔴 Traceback (most recent call last):
🔴 Traceback (most recent call last):
🔴   File ".\tools.py", line 470, in getPackageIcon
🔴   File ".\tools.py", line 470, in getPackageIcon
🔴   File "urllib\request.py", line 216, in urlopen
🔴   File "urllib\request.py", line 216, in urlopen
🔴   File "urllib\request.py", line 519, in open
🔴   File "urllib\request.py", line 519, in open
🔴   File "urllib\request.py", line 536, in _open
🔴   File "urllib\request.py", line 536, in _open
🔴   File "urllib\request.py", line 496, in _call_chain
🔴   File "urllib\request.py", line 496, in _call_chain
🔴   File "urllib\request.py", line 1391, in https_open
🔴   File "urllib\request.py", line 1391, in https_open
🔴   File "urllib\request.py", line 1351, in do_open
🔴   File "urllib\request.py", line 1351, in do_open
🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)>
🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)>
🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)>)
🟡 Icon for GnuCash.GnuCash does not exist
```

I have similar stack traces that end in:
```
🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 404: Not Found)
🟡 Icon for Atlassian.Sourcetree does not exist
```

also a few times:
```
🔴 Traceback (most recent call last):
🔴 Traceback (most recent call last):
🔴   File ".\genericCustomWidgets.py", line 337, in removeItem
🔴   File ".\genericCustomWidgets.py", line 337, in removeItem
🔴 ValueError: list.remove(x): x not in list
🔴 ValueError: list.remove(x): x not in list
🔴 Note this traceback was caught by reporter and has been added to the log (list.remove(x): x not in list)
```

and finally.
this one repeats for every time the button "Update selected packages" is used.
but no update procedures are started.
```
Traceback (most recent call last):
  File ".\uiSections.py", line 614, in <lambda>
  File ".\uiSections.py", line 930, in updateSelectedPackageItems
  File ".\uiSections.py", line 938, in updatePackageItem
  File ".\storeEngine.py", line 407, in __init__
  File ".\storeEngine.py", line 51, in __init__
  File ".\storeEngine.py", line 395, in resizeEvent
  File ".\storeEngine.py", line 399, in updateProgressbarSize
AttributeError: 'PackageUpdaterWidget' object has no attribute 'liveOutputButton'. Did you mean: 'liveOutputWindow'?
    Note: This exception was delayed.
```

### Steps to reproduce the issue

all under normal use, searching and installing

### WingetUI Log

```text
(github does not accept this)
```

### Package Managers Logs

```text
(github does not accept this)
```

**Comment by marticliment** [comment]
this third one is an actual issue. the first one stands for failing to check for updates and the second one is expected under certain circumstances.
