### ISSUE TITLE
[BUG] Wrong versions detceted

### ISSUE THREAD

**Issue by mooms06** [marticliment/WingetUI#1302]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

See the images, WingetUI is detecting Thunderbird 117.0b4, I have 102.14.0. Also, it proposes Dotnet runtimes 7.0.10, but it is already installed, and version 7 is not an update to version 6 anyway.

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0020017623901367188 to load all language files
🟢 checkQueue Thread started!
🔵 Found default chocolatey installation on expected location
🔵 Starting main application...
[<customWidgets.WelcomeWizardPackageManager(0x1b124f6a360) at 0x000001B13EFD7540>]
[<customWidgets.WelcomeWizardPackageManager(0x1b124f6a360) at 0x000001B13EFD7540>, <customWidgets.WelcomeWizardPackageManager(0x1b124e17ce0) at 0x000001B13EFB0480>]
[<customWidgets.WelcomeWizardPackageManager(0x1b124f6a360) at 0x000001B13EFD7540>, <customWidgets.WelcomeWizardPackageManager(0x1b124e17ce0) at 0x000001B13EFB0480>, <customWidgets.WelcomeWizardPackageManager(0x1b124e13410) at 0x000001B13EFE8240>]
[<customWidgets.WelcomeWizardPackageManager(0x1b124f6a360) at 0x000001B13EFD7540>, <customWidgets.WelcomeWizardPackageManager(0x1b124e17ce0) at 0x000001B13EFB0480>, <customWidgets.WelcomeWizardPackageManager(0x1b124e13410) at 0x000001B13EFE8240>, <customWidgets.WelcomeWizardPackageManager(0x1b124e12510) at 0x000001B13EFE8980>]
[<customWidgets.WelcomeWizardPackageManager(0x1b124f6a360) at 0x000001B13EFD7540>, <customWidgets.WelcomeWizardPackageManager(0x1b124e17ce0) at 0x000001B13EFB0480>, <customWidgets.WelcomeWizardPackageManager(0x1b124e13410) at 0x000001B13EFE8240>, <customWidgets.WelcomeWizardPackageManager(0x1b124e12510) at 0x000001B13EFE8980>, <customWidgets.WelcomeWizardPackageManager(0x1b124e15570) at 0x000001B13EFE9080>]
Win32Mica Error: win32 version 19045 is not supported
🔵 Language file up-to-date
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Starting update check
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:7058
Press CTRL+C to quit
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
{'sudoFound': True, 'sudoVersion': '', 'ScoopFound': False, 'ScoopVersion': 'Scoop est désactivé(e)', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey est désactivé(e)', 'PipFound': False, 'PipVersion': 'Pip est désactivé(e)', 'NpmFound': False, 'NpmVersion': 'Npm est désactivé(e)', 'WingetFound': True, 'WingetVersion': ''}
🔵 Reached main ui load milestone
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for available packages
🟢 Found valid, non-empty cache file for Winget!
🔵 Starting Winget package caching
🟢 Winget search for installed packages finished with 5125 result(s)
Can't disconnect
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
Can't disconnect
🔵 Reloading Scoop sources...
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🔵 Starting Winget search for updates
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
Win32Mica Error: win32 version 19045 is not supported
50
🟢 Total packages: 5125
🟢 Winget search for installed packages finished with 126 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 126
🟢 Winget search for updates finished with 4 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 4
🟢 Winget packages cached successfuly
Win32Mica Error: win32 version 19045 is not supported
🟢 Waiting for install permission... title=Chromium, id=eloston.ungoogled-chromium, installId=1692835047.7099178
🔵 Given package: <Package: Chromium;eloston.ungoogled-chromium;116.0.5845.82;Winget: winget;<PackageManagers.winget.WingetPackageManager object at 0x000001B126422F10>;<genericCustomWidgets.TreeWidgetItemWithQAction object at 0x000001B13F5F8F00>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
[<customWidgets.WelcomeWizardPackageManager(0x1b124f6a360) at 0x000001B13EFD7540>, <customWidgets.WelcomeWizardPackageManager(0x1b124e17ce0) at 0x000001B13EFB0480>, <customWidgets.WelcomeWizardPackageManager(0x1b124e13410) at 0x000001B13EFE8240>, <customWidgets.WelcomeWizardPackageManager(0x1b124e12510) at 0x000001B13EFE8980>, <customWidgets.WelcomeWizardPackageManager(0x1b124e15570) at 0x000001B13EFE9080>, <storeEngine.PackageUpdaterWidget(0x1b1410f6e90, name="package") at 0x000001B13EFEB900>]
🔵 Found cached image in C:\Users\xxx\.wingetui/cachedmeta/ungoogled-chromium.icon.png
🔵 Current program set to 1692835047.7099178
🟢 Have permission to install, starting installation threads...
🔵 Starting <Package: Chromium;eloston.ungoogled-chromium;116.0.5845.82;Winget: winget;<PackageManagers.winget.WingetPackageManager object at 0x000001B126422F10>;<genericCustomWidgets.TreeWidgetItemWithQAction object at 0x000001B13F5F8F00>> update with Command ['C:\\Program Files\\WingetUI\\PackageManagers\\winget-cli_x64\\winget.exe', 'upgrade', '--id', 'eloston.ungoogled-chromium', '--exact', '--include-unknown', '--accept-source-agreements', '--disable-interactivity', '--accept-package-agreements']
['- \r                                                                                                                        \r\r  █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 16.5 MB\r  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 16.5 MB\r  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 16.5 MB\r  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 16.5 MB\r  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 16.5 MB\r  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 16.5 MB\r  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 16.5 MB\r  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  8.00 MB / 16.5 MB\r  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  9.00 MB / 16.5 MB\r  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  10.0 MB / 16.5 MB\r  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  11.0 MB / 16.5 MB\r  █████████████████████▒▒▒▒▒▒▒▒▒  12.0 MB / 16.5 MB\r  ███████████████████████▒▒▒▒▒▒▒  13.0 MB / 16.5 MB\r  █████████████████████████▒▒▒▒▒  14.0 MB / 16.5 MB\r  ███████████████████████████▒▒▒  15.0 MB / 16.5 MB\r  █████████████████████████████▒  16.0 MB / 16.5 MB\r  ██████████████████████████████  16.5 MB / 16.5 MB\r                                                                                                                        \r\r   - \r                                                                                                                        \rFound Chromium [eloston.ungoogled-chromium] Version 116.0.5845.97', 'This application is licensed to you by its owner.', 'Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.', 'Downloading https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/116.0.5845.97-1.1/ungoogled-chromium_116.0.5845.97-1.1_installer_x64.exe', '- \r   \\ \r   | \r   / \r   - \r                                                                                                                        \r\r                                                                                                                        \r\r  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0.00 B / 72.9 MB\r  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0.00 B / 72.9 MB\r  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  14.0 MB / 72.9 MB\r  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  26.0 MB / 72.9 MB\r  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  37.0 MB / 72.9 MB\r  ████████████████████▒▒▒▒▒▒▒▒▒▒  49.0 MB / 72.9 MB\r  ████████████████████████▒▒▒▒▒▒  59.9 MB / 72.9 MB\r  █████████████████████████████▒  71.9 MB / 72.9 MB\r  ██████████████████████████████  72.9 MB / 72.9 MB', 'Successfully verified installer hash', 'Starting package install...', '- \r   \\ \r   | \r   / \r   - \r   \\ \r   | \r   / \r   - \r   \\ \r   | \r                                                                                                                        \rSuccessfully installed', '']
[<customWidgets.WelcomeWizardPackageManager(0x1b124f6a360) at 0x000001B13EFD7540>, <customWidgets.WelcomeWizardPackageManager(0x1b124e17ce0) at 0x000001B13EFB0480>, <customWidgets.WelcomeWizardPackageManager(0x1b124e13410) at 0x000001B13EFE8240>, <customWidgets.WelcomeWizardPackageManager(0x1b124e12510) at 0x000001B13EFE8980>, <customWidgets.WelcomeWizardPackageManager(0x1b124e15570) at 0x000001B13EFE9080>]
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\genericCustomWidgets.py", line 337, in removeItem

🔴   File ".\genericCustomWidgets.py", line 337, in removeItem

🔴 ValueError: list.remove(x): x not in list

🔴 ValueError: list.remove(x): x not in list

🔴 Note this traceback was caught by reporter and has been added to the log (list.remove(x): x not in list)
[<customWidgets.WelcomeWizardPackageManager(0x1b124f6a360) at 0x000001B13EFD7540>, <customWidgets.WelcomeWizardPackageManager(0x1b124e17ce0) at 0x000001B13EFB0480>, <customWidgets.WelcomeWizardPackageManager(0x1b124e13410) at 0x000001B13EFE8240>, <customWidgets.WelcomeWizardPackageManager(0x1b124e12510) at 0x000001B13EFE8980>, <customWidgets.WelcomeWizardPackageManager(0x1b124e15570) at 0x000001B13EFE9080>]
🔵 Loading log...
🔵 Copying log to the clipboard...
🔵 Loading log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------Winget
- 
                                                                                                                        

  █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 16.5 MB
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 16.5 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 16.5 MB
  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 16.5 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 16.5 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 16.5 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 16.5 MB
  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  8.00 MB / 16.5 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  9.00 MB / 16.5 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  10.0 MB / 16.5 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  11.0 MB / 16.5 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  12.0 MB / 16.5 MB
  ███████████████████████▒▒▒▒▒▒▒  13.0 MB / 16.5 MB
  █████████████████████████▒▒▒▒▒  14.0 MB / 16.5 MB
  ███████████████████████████▒▒▒  15.0 MB / 16.5 MB
  █████████████████████████████▒  16.0 MB / 16.5 MB
  ██████████████████████████████  16.5 MB / 16.5 MB
                                                                                                                        

   - 
                                                                                                                        
Name                                      Id                                        Version        Available     Source
-----------------------------------------------------------------------------------------------------------------------
FreeTube 0.19.0                           PrestonN.FreeTube                         0.19.0                       winget
7-Zip 23.01 (x64)                         7zip.7zip                                 23.01                        winget
AIMP                                      AIMP.AIMP                                 5.11.2435                    winget
AMD Chipset Software                      AMD_Chipset_IODrivers                     5.05.16.529
Audacity 3.3.3                            Audacity.Audacity                         3.3.3                        winget
Avidemux 2.8.1                            Avidemux_is1                              2.8.1
Chromium                                  eloston.ungoogled-chromium                116.0.5845.82  116.0.5845.97 winget
ContextConsole Shell Extension (x86-64)   CmdOpen Shell Extension                   2.1.0.1
DTS Custom for Asus                       DTSInc.DTSCustomforAsus_t5j2fzbtdg37r     2.1.1.0
Microsoft DirectX End-User Runtime        DirectX End-User Runtime                  9.29.1974
Microsoft DirectX Managed Assemblies      DirectX Managed Assemblies                1.1
Dolby Vision Extensions                   DolbyLaboratories.DolbyVisionAccess_rz1t… 2.2.337.0
EZ CD Audio Converter                     EZ CD Audio Converter                     11.0.3
Everything 1.4.1.1024 (x64)               voidtools.Everything                      1.4.1.1024                   winget
F1 22                                     F1 22_is1                                 Unknown
FFmpeg 5.0.0 for Audacity - x86_64        FFmpeg for Audacity_is1                   Unknown
FileZilla 3.65.0                          FileZilla Client                          3.65.0
Flowframes                                Flowframes                                1.36.0
Greenshot 1.3.277                         Greenshot.Greenshot                       1.3.277                      winget
HandBrake 1.6.1                           HandBrake.HandBrake                       1.6.1                        winget
HashCheck Shell Extension                 gurnec.HashCheckShellExtension            2.5.0.1                      winget
Inno Setup version 6.2.2                  JRSoftware.InnoSetup                      6.2.2                        winget
KC Softwares SUMo                         KCSoftwares.SUMo                          5.17.10.542                  winget
K-Lite Codec Pack 17.7.4 Full             KLiteCodecPack_is1                        17.7.4
LockHunter 3.4, 32/64 bit                 CrystalRich.LockHunter                    3.4.3.146                    winget
Logitech Options                          Logitech.Options                          10.10.58                     winget
Cinebench                                 MAXONComputerGmbH.Cinebench_rsne5bsk8s7tj 23.2.0.0
MKVToolNix 79.0.0 (64-bit)                MoritzBunkus.MKVToolNix                   79.0.0                       winget
Microsoft Edge                            Microsoft.Edge                            116.0.1938.54                winget
Microsoft Edge Update                     Microsoft Edge Update                     1.3.177.11
Microsoft Edge WebView2 Runtime           Microsoft.EdgeWebView2Runtime             115.0.1901.203               winget
AV1 Video Extension                       Microsoft.AV1VideoExtension_8wekyb3d8bbwe 1.1.61781.0
Programme d'installation d'application    Microsoft.DesktopAppInstaller_8wekyb3d8b… 1.20.2201.0
HEIF Image Extensions                     Microsoft.HEIFImageExtension_8wekyb3d8bb… 1.0.62091.0
Extensions vidéo HEVC du fabricant de l'… Microsoft.HEVCVideoExtension_8wekyb3d8bb… 2.0.61931.0
Module d'expérience locale français (Fra… Microsoft.LanguageExperiencePackfr-FR_8w… 19041.65.213.0
Microsoft Edge                            Microsoft.MicrosoftEdge.Stable_8wekyb3d8… 115.0.1901.203
Hôte de l'expérience du Microsoft Store   Microsoft.StorePurchaseApp_8wekyb3d8bbwe  22307.1401.6.0
VP9 Video Extensions                      Microsoft.VP9VideoExtensions_8wekyb3d8bb… 1.0.61591.0
Microsoft Pay                             Microsoft.Wallet_8wekyb3d8bbwe            2.4.18324.0
Extensions de support web                 Microsoft.WebMediaExtensions_8wekyb3d8bb… 1.0.61591.0
Webp Image Extensions                     Microsoft.WebpImageExtension_8wekyb3d8bb… 1.0.62011.0
Calculatrice Windows                      Microsoft.WindowsCalculator_8wekyb3d8bbwe 11.2210.0.0
Caméra Windows                            Microsoft.WindowsCamera_8wekyb3d8bbwe     2023.2305.4.0
Microsoft Store                           Microsoft.WindowsStore_8wekyb3d8bbwe      22307.1401.6.0
Windows Package Manager Source (winget)   Microsoft.Winget.Source_8wekyb3d8bbwe     2023.203.2238…
Xbox Game Bar Plugin                      Microsoft.XboxGameOverlay_8wekyb3d8bbwe   1.54.4001.0
Xbox Identity Provider                    Microsoft.XboxIdentityProvider_8wekyb3d8… 12.95.3001.0
Mozilla Firefox (x64 fr)                  Mozilla.Firefox                           116.0.3                      winget
Mozilla Thunderbird (x64 fr)              Mozilla.Thunderbird.Beta                  > 117.0b4      117.0b6       winget
Mozilla Maintenance Service               MozillaMaintenanceService                 116.0.3
NVIDIA Control Panel                      NVIDIACorp.NVIDIAControlPanel_56jybvy8sc… 8.1.964.0
NetWorx 5.5.5                             NetWorx_is1                               Unknown
NewsLeecher version V8.0 Beta 4           CrystalArtSoftware.NewsLeecher            V8.0 Beta 4    7.0.0.0       winget
Notepad++ (64-bit x64)                    Notepad++.Notepad++                       8.5.6                        winget
OBS Studio                                OBSProject.OBSStudio                      29.1.3                       winget
Old Classic Calculator for Windows 11 an… Old Classic Calculator for Windows 11 an… 2.0
Realtek Audio Control                     RealtekSemiconductorCorp.RealtekAudioCon… 1.44.299.0
Steam                                     Valve.Steam                               2.10.91.91                   winget
SumatraPDF                                SumatraPDF.SumatraPDF                     3.4.6                        winget
SyncBackFree                              2BrightSparks.SyncBackFree                11.0.0.25                    winget
UltraISO Premium V9.76                    EZBSystems.UltraISO                       9.76                         winget
Utilitaires version 23.08.22              Utilitaires_is1                           23.08.22
Vivaldi                                   VivaldiTechnologies.Vivaldi               6.1.3035.302                 winget
WinRAR 6.23 (64-bit)                      RARLab.WinRAR                             6.23.0                       winget
Malwarebytes Windows Firewall Control     BiniSoft.WindowsFirewallControl           6.9.2.0                      winget
XnViewMP 1.5.3                            XnSoft.XnViewMP                           1.5.3                        winget
Intel Media SDK DLLs 8.18.6.8             libmfxsw_is1                              8.18.6.8
Tixati                                    tixati                                    Unknown
Microsoft Visual C++ 2013 x64 Additional… {010792BA-551A-3AC0-A7EF-0FAB4156C382}    12.0.40664
Microsoft Windows Desktop Runtime - 6.0.… Microsoft.DotNet.DesktopRuntime.6         6.0.21                       winget
Microsoft Visual C++ 2010  x64 Redistrib… Microsoft.VCRedist.2010.x64               10.0.40219                   winget
Python Launcher                           {23514291-DEF3-42FD-A67C-A96E35C92F24}    3.11.4150.0
Geeks3D FurMark 1.35.0.0                  {2397CAD4-2263-4CD0-96BE-E43A980B9C9A}_i… 1.35.0.0
Microsoft Visual C++ 2022 X86 Minimum Ru… {2F7F071D-83D0-4994-8237-7B0579452FD4}    14.38.32919
Microsoft Visual C++ 2012 x64 Additional… {37B8F9C7-03FB-3253-8781-2517C99D7C00}    11.0.61135
Oracle VM VirtualBox 7.0.10               Oracle.VirtualBox                         7.0.10                       winget
Path Copy Copy 20.0                       CLechasseur.PathCopyCopy                  20.0                         winget
Python 3.11.4 (64-bit)                    Python.Python.3.11                        3.11.4                       winget
Microsoft Visual Studio 2010 Tools for O… {47C2CCDB-7A04-3797-992B-A84D3E90258F}    10.0.60833
HidHide                                   ViGEm.HidHide                             1.2.128                      winget
Microsoft Visual C++ 2013 x64 Minimum Ru… {53CF6934-A98D-3D84-9146-FC4EDF3D5641}    12.0.40664
Telegram Desktop                          Telegram.TelegramDesktop                  4.9.2                        winget
Microsoft Visual C++ 2022 X86 Additional… {5F0295FE-3DAA-4C04-94A6-2AFC6D739D34}    14.38.32919
Microsoft Visual C++ 2008 Redistributabl… Microsoft.VCRedist.2008.x64               9.0.30729.7523               winget
Microsoft Visual C++ 2005 Redistributable Microsoft.VCRedist.2005.x86               8.0.61187                    winget
Microsoft Windows Desktop Runtime - 7.0.… Microsoft.DotNet.DesktopRuntime.6         > 6.0.21       7.0.10        winget
Microsoft Visual C++ 2013 x86 Minimum Ru… {8122DAB1-ED4D-3676-BB0A-CA368196543E}    12.0.40664
WingetUI                                  SomePythonThings.WingetUIStore            2.0.3                        winget
Futuremark SystemInfo                     {93086761-C4E7-48FC-A090-E9AE1C73B254}    5.64.1188.0
Microsoft Visual C++ 2022 X64 Additional… {98B96874-2649-4CC3-B599-1F2EEC28A500}    14.38.32919
Microsoft Visual C++ 2008 Redistributabl… Microsoft.VCRedist.2008.x86               9.0.30729.7523               winget
ViGEm Bus Driver                          ViGEm.ViGEmBus                            1.21.442                     winget
paint.net                                 dotPDNLLC.paintdotnet                     5.0.9                        winget
Microsoft Visual C++ 2012 x86 Additional… {B175520C-86A2-35A7-8619-86DC379688B9}    11.0.61135
NVIDIA Pilote graphique 537.13            {B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_D… 537.13
NVIDIA Logiciel système PhysX 9.21.0713   {B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_D… 9.21.0713
NVIDIA Pilote audio HD : 1.3.40.14        {B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_H… 1.3.40.14
NVCleanstall                              TechPowerUp.NVCleanstall                  1.16.0                       winget
Microsoft Update Health Tools             {BB052C53-34CB-42DE-AF41-66FDFCEEC868}    3.72.0.0
Microsoft Visual C++ 2012 x86 Minimum Ru… {BD95A8CD-1D9F-35AD-981A-3E7925026EBB}    11.0.61135
pinga 0.42                                {C207AD7B-AE16-4A26-B31C-F79880F30A22}}_… 0.42
Microsoft Visual Basic/C++ Runtime (x86)  {C5E3A69D-D391-45A6-A8FB-00B01E2B010D}    1.1.0
Eclipse Temurin JRE avec Hotspot 17.0.7+… EclipseAdoptium.Temurin.17.JRE            17.0.7.7                     winget
Microsoft Visual C++ 2012 x64 Minimum Ru… {CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}    11.0.61135
Microsoft Visual C++ 2022 X64 Minimum Ru… {D028B71C-9372-40C9-B535-5841F78448CC}    14.38.32919
LibreOffice 7.6.0.3                       TheDocumentFoundation.LibreOffice         7.6.0.3                      winget
Microsoft Visual C++ 2013 x86 Additional… {D401961D-3A20-3AC7-943B-6139D5BD490A}    12.0.40664
Microsoft Visual C++ 2010  x86 Redistrib… Microsoft.VCRedist.2010.x86               10.0.40219                   winget
Realtek Audio Driver                      {F132AF7F-7BCA-4EDE-8A7C-958108FE7DBC}    6.0.9539.1
Microsoft Visual C++ 2005 Redistributabl… {ad8a2fa1-06e7-4b0d-927d-6e54b3d31028}    8.0.61186
---------Winget
- 
                                                                                                                        

  █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 16.5 MB
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 16.5 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 16.5 MB
  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 16.5 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 16.5 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 16.5 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 16.5 MB
  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  8.00 MB / 16.5 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  9.00 MB / 16.5 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  10.0 MB / 16.5 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  11.0 MB / 16.5 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  12.0 MB / 16.5 MB
  ███████████████████████▒▒▒▒▒▒▒  13.0 MB / 16.5 MB
  █████████████████████████▒▒▒▒▒  14.0 MB / 16.5 MB
  ███████████████████████████▒▒▒  15.0 MB / 16.5 MB
  █████████████████████████████▒  16.0 MB / 16.5 MB
  ██████████████████████████████  16.5 MB / 16.5 MB
                                                                                                                        

   - 
                                                                                                                        
Name                                             Id                                Version       Available     Source
---------------------------------------------------------------------------------------------------------------------
Chromium                                         eloston.ungoogled-chromium        116.0.5845.82 116.0.5845.97 winget
Mozilla Thunderbird (x64 fr)                     Mozilla.Thunderbird.Beta          > 117.0b4     117.0b6       winget
NewsLeecher version V8.0 Beta 4                  CrystalArtSoftware.NewsLeecher    V8.0 Beta 4   7.0.0.0       winget
Microsoft Windows Desktop Runtime - 7.0.10 (x64) Microsoft.DotNet.DesktopRuntime.6 > 6.0.21      7.0.10        winget
4 upgrades available.
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/25405517/c5b3a5b3-cf5c-4704-a6f3-d1b77f440762)

![image](https://github.com/marticliment/WingetUI/assets/25405517/a4c9dc31-8c34-4699-8b4d-affe14c97a2b)

**Comment by marticliment** [comment]
For the time being, please skip version/ignore the packages in question

**Comment by mooms06** [comment]
> This issue is an issue with Winget, and is not WingetUI's fault. Please note that this issue will be fixed soon on microsoft/winget-cli

Good news then.

> For the time being, please skip version/ignore the packages in question

Already did it.
