### ISSUE TITLE
Program does not show the correct version of WinGet and does not find an update of it

### ISSUE THREAD

**Issue by In139** [marticliment/WingetUI#1419]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Hello Martí and developers,

today MS have updated WinGet to 1.6.2701. I still have 1.6.2631 installed. However, WinGetUI shows me that I would have 1.5.1881 installed (all visible in the screenshot wit WinGetUI, CMD of Windows 11 and software news ticker from computerbase.de).
Furthermore, WinGetUI does not find an update for WinGet either.

Possibly the latter is not a bug, but not possible in principle - I don't know.

Thank you for the tool - I am new to using it and still testing it.

[Translated with help from DeepL]

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0 to load all language files
🟢 checkQueue Thread started!
🟡 Chocolatey was not found on the default location, perhaps a portable WingetUI installation?
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
🔵 Loading WingetUI AUMID...
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:7058
Press CTRL+C to quit
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\wingetui.exe
🔵 Reactivation signal ignored: RaiseWindow_[1695901381.1611614]
{'sudoFound': True, 'sudoVersion': '', 'ScoopFound': False, 'ScoopVersion': 'Scoop ist deaktiviert', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey ist deaktiviert', 'PipFound': False, 'PipVersion': 'Pip ist deaktiviert', 'NpmFound': False, 'NpmVersion': 'Npm ist deaktiviert', '.NET ToolFound': False, '.NET ToolVersion': '', 'WingetFound': True, 'WingetVersion': 'v1.5.1881  '}
🔵 Reached main ui load milestone
Can't disconnect
Can't disconnect
Can't disconnect
C:/Program Files/WingetUI/resources/installed_masked_white.png
🟢 Discover tab loaded successfully
🟢 Total packages: 0
Can't disconnect
Can't disconnect
Can't disconnect
Can't disconnect
C:/Program Files/WingetUI/resources/update_masked_white.png
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
Can't disconnect
Can't disconnect
Can't disconnect
🔵 Reloading Scoop sources...
C:/Program Files/WingetUI/resources/pin_masked_white.png
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting .NET Tool search for installed packages
🟢 Searching for string ""
Der Befehl "dotnet.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
Der Befehl "dotnet.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
🟢 .NET Tool search for installed packages finished with 0 result(s)
Can't disconnect
🟢 Starting winget source search...
🟢 Starting winget source search...
Can't disconnect
🟢 Settings tab loaded!
🔵 Starting Winget search for updates
🟢 winget source search finished
🟢 winget source search finished
🟢 About tab loaded!
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
🟢 Main application loaded...
🟢 Searching for string ""
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
🟢 Winget search for installed packages finished with 74 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 74
🔵 Reloading Scoop sources...
🔵 Starting .NET Tool search for updates
🟡 Installing dotnet-tools-outdated, that was missing...
[b'Der Befehl "dotnet.exe" ist entweder falsch geschrieben oder\r\n', b'konnte nicht gefunden werden.\r\n']
Der Befehl "dotnet-tools-outdated" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
🟢 .NET Tool search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 7 result(s)
🟢 Searching for string ""
Exception ignored in: <function BaseWindowsToaster.show_toast.<locals>.<lambda> at 0x00000225F2572E80>
Traceback (most recent call last):
  File "windows_toasts\toasters.py", line 147, in <lambda>
  File ".\Interface\CustomWidgets\GenericWidgets.py", line 717, in <lambda>
TypeError: ToastNotification.reportException() missing 1 required positional argument: 'id'
🟢 Searching for string ""
🟢 Total packages: 7
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 -------dotnet
Der Befehl "dotnet.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

-------dotnet
Der Befehl "dotnet.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

---------Winget
- 
   \ 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 7.98 MB
  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 7.98 MB
  ███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 7.98 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 7.98 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 7.98 MB
  ██████████████████████▒▒▒▒▒▒▒▒  6.00 MB / 7.98 MB
  ██████████████████████████▒▒▒▒  7.00 MB / 7.98 MB
  ██████████████████████████████  7.98 MB / 7.98 MB
                                                                                                                        

   - 
                                                                                                                        
Name                                Id                                   Version                Available        Source
-----------------------------------------------------------------------------------------------------------------------
7-Zip 23.01 (x64)                   7zip.7zip                            23.01                                   winget
Dolby Access OEM                    DolbyLaboratories.DolbyAccessOEM_rz… 3.18.46.0
Dolby Vision Extensions             DolbyLaboratories.DolbyVisionAccess… 2.2.337.0
Microsoft Edge                      Microsoft.Edge                       117.0.2045.43                           winget
Microsoft Edge Update               Microsoft Edge Update                1.3.177.11
Microsoft Edge WebView2-Laufzeit    Microsoft EdgeWebView                117.0.2045.43
App-Installer                       Microsoft.DesktopAppInstaller_8weky… 1.21.2631.0
HEIF Image Extensions               Microsoft.HEIFImageExtension_8wekyb… 1.0.62261.0
HEVC-Videoerweiterungen vom Geräte… Microsoft.HEVCVideoExtension_8wekyb… 2.0.61931.0
Deutsch Local Experience Pack       Microsoft.LanguageExperiencePackde-… 22621.37.178.0
Microsoft Edge                      Microsoft.MicrosoftEdge.Stable_8wek… 117.0.2045.43
Paint                               Microsoft.Paint_8wekyb3d8bbwe        11.2304.33.0
Raw Image Extension                 Microsoft.RawImageExtension_8wekyb3… 2.1.61661.0
Snipping Tool                       Microsoft.ScreenSketch_8wekyb3d8bbwe 11.2306.44.0
Windows-Sicherheit                  Microsoft.SecHealthUI_8wekyb3d8bbwe  1000.25873.9001.0
Host der Store-Benutzeroberfläche   Microsoft.StorePurchaseApp_8wekyb3d… 22307.1401.9.0
VP9 Video Extensions                Microsoft.VP9VideoExtensions_8wekyb… 1.0.61591.0
Webmedienerweiterungen              Microsoft.WebMediaExtensions_8wekyb… 1.0.61591.0
Webp Image Extensions               Microsoft.WebpImageExtension_8wekyb… 1.0.62011.0
Windows-Uhr                         Microsoft.WindowsAlarms_8wekyb3d8bb… 11.2306.23.0
Windows-Rechner                     Microsoft.WindowsCalculator_8wekyb3… 11.2307.4.0
Windows-Kamera                      Microsoft.WindowsCamera_8wekyb3d8bb… 2023.2305.4.0
Windows-Editor                      Microsoft.WindowsNotepad_8wekyb3d8b… 11.2306.15.0
Microsoft Store                     Microsoft.WindowsStore_8wekyb3d8bbwe 22308.1401.5.0
Vorschau auf Windows-Terminal       Microsoft.WindowsTerminal.Preview    1.19.2682.0                             winget
Windows-Terminal                    Microsoft.WindowsTerminal            1.17.11461.0           1.18.2681.0      winget
Windows Package Manager Source (wi… Microsoft.Winget.Source_8wekyb3d8bb… 2023.907.1819.473
Xbox Game Bar Plugin                Microsoft.XboxGameOverlay_8wekyb3d8… 1.54.4001.0
Xbox Identity Provider              Microsoft.XboxIdentityProvider_8wek… 12.95.3001.0
Xbox Game Speech Window             Microsoft.XboxSpeechToTextOverlay_8… 1.21.13002.0
Smartphone-Link                     Microsoft.YourPhone_8wekyb3d8bbwe    1.23082.131.0
Windows Web Experience Pack         MicrosoftWindows.Client.WebExperien… 423.23500.0.0
Mozilla Firefox (x64 de)            Mozilla.Firefox                      117.0                  118.0            winget
Mozilla Maintenance Service         MozillaMaintenanceService            115.0
Microsoft 365 Apps for Enterprise … Microsoft.Office                     16.0.15726.20202       16.0.16626.20148 winget
Microsoft 365 Apps for enterprise … Microsoft.Office                     16.0.15726.20202       16.0.16626.20148 winget
Vivaldi                             Vivaldi                              6.2.3105.51
Microsoft Visual C++ 2013 Redistri… Microsoft.VCRedist.2013.x64          12.0.40664.0                            winget
PowerShell 7-x64                    Microsoft.PowerShell                 7.3.7.0                                 winget
Microsoft Visual C++ 2010  x64 Red… Microsoft.VCRedist.2010.x64          10.0.40219                              winget
LibreOffice 7.6 Help Pack (German)  TheDocumentFoundation.LibreOffice.H… 7.6.2.1                                 winget
Microsoft Visual C++ 2012 Redistri… Microsoft.VCRedist.2012.x86          11.0.61030.0                            winget
Malwarebytes version 4.6.3.282      Malwarebytes.Malwarebytes            4.6.3.282                               winget
Microsoft Visual C++ 2015-2019 Red… Microsoft.VCRedist.2015+.x86         14.25.28508.3          14.38.32919.0    winget
LibreOffice 7.6.2.1                 TheDocumentFoundation.LibreOffice    7.6.2.1                                 winget
Microsoft SQL Server 2012 Manageme… {7ED2561C-FBC2-421E-A2B5-C7BEFD6231… 11.4.7001.0
WingetUI                            SomePythonThings.WingetUIStore       2.1.0                                   winget
Microsoft Visual C++ 2015-2022 Red… Microsoft.VCRedist.2015+.x64         14.36.32532.0          14.38.32919.0    winget
PowerShell 7.3.6.0-x64              Microsoft.PowerShell                 7.3.6.0                7.3.7.0          winget
Microsoft Visual C++ 2013 Redistri… Microsoft.VCRedist.2013.x86          12.0.40664.0                            winget
paint.net                           dotPDNLLC.paintdotnet                5.0.9                                   winget
Veeam Agent for Microsoft Windows   {AA732883-16A3-45A4-A2A0-E9157E1331… 6.0.2.1090
KeePassXC                           KeePassXCTeam.KeePassXC              2.7.6                                   winget
Microsoft Update Health Tools       {AF47B488-9780-4AB5-A97E-762E28013C… 5.71.0.0
OpenHashTab Version v3.0.4          namazso.OpenHashTab                  v3.0.4                                  winget
Microsoft SQL Server 2012 Express … {C18B132E-4032-4425-826A-24B1CA9DFF… 11.4.7001.0
Microsoft System CLR Types for SQL… {CECCBAE9-1880-411E-9D28-8E562F6DAA… 11.4.7001.0
ExplorerPatcher                     valinet.ExplorerPatcher              22621.2361.58.1                         winget
MPC-BE x64 1.6.9                    MPC-BE.MPC-BE                        1.6.9                                   winget
Microsoft Visual C++ 2012 Redistri… Microsoft.VCRedist.2012.x64          11.0.61030.0                            winget--------dotnet

Der Befehl "dotnet-tools-outdated" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.---------Winget
- 
   \ 
   | 
   / 
   - 
   \ 
   | 
   / 
   - 
   \ 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 7.98 MB
  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 7.98 MB
  ███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 7.98 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 7.98 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 7.98 MB
  ██████████████████████▒▒▒▒▒▒▒▒  6.00 MB / 7.98 MB
  ██████████████████████████▒▒▒▒  7.00 MB / 7.98 MB
  ██████████████████████████████  7.98 MB / 7.98 MB
                                                                                                                        

   - 
                                                                                                                        
Name                                              Id                           Version          Available        Source
-----------------------------------------------------------------------------------------------------------------------
Windows-Terminal                                  Microsoft.WindowsTerminal    1.17.11461.0     1.18.2681.0      winget
Mozilla Firefox (x64 de)                          Mozilla.Firefox              117.0            118.0            winget
Microsoft 365 Apps for Enterprise - de-de         Microsoft.Office             16.0.15726.20202 16.0.16626.20148 winget
Microsoft 365 Apps for enterprise - en-us         Microsoft.Office             16.0.15726.20202 16.0.16626.20148 winget
Microsoft Visual C++ 2015-2019 Redistributable (… Microsoft.VCRedist.2015+.x86 14.25.28508.3    14.38.32919.0    winget
Microsoft Visual C++ 2015-2022 Redistributable (… Microsoft.VCRedist.2015+.x64 14.36.32532.0    14.38.32919.0    winget
PowerShell 7.3.6.0-x64                            Microsoft.PowerShell         7.3.6.0          7.3.7.0          winget
7 upgrades available.
```

### Screenshots and videos

![WinGetUI inconsistency](https://github.com/marticliment/WingetUI/assets/102912715/e5a29df4-d719-40a8-b010-b9a21f389292)

**Comment by marticliment** [comment]
Winget is bundled, so it won't be updated automatically. 

Instead, the next WingetUI version will automatically update winget to version 1.6.
Automatic updates are disabled to prevent breakings on api changes
