### ISSUE TITLE
[BUG] Failed in attempting to update the source: winget

### ISSUE THREAD

**Issue by Leuconoe** [marticliment/WingetUI#1442]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Every time I tried to update the software on wingetui, I got the error "Cannot install because the hash is different".
To fix the problem, I tried reset winget sources, and after that I ran into the problem of not being able to get the sources.
I tried using the system default winget, resetting and reinstalling wingetui, etc, but nothing worked.

I thought it might be a CDN error, but with the latest wingetcli there was no problem. ( https://github.com/microsoft/winget-cli/issues/3652 )

v 2.1.0

### Steps to reproduce the issue

![image](https://github.com/marticliment/WingetUI/assets/6531761/636beb23-4ed7-4ee4-8e63-31b8fb03c61d)
1. run the program
2. Select the Software Update tab
3. a message that there are no updates.

![image](https://github.com/marticliment/WingetUI/assets/6531761/9aadcbcd-273c-4d73-b5c2-47c6d9471200)
1. run the program
2. search for software to install
3. winget source is not in the list.

![image](https://github.com/marticliment/WingetUI/assets/6531761/4b1dc120-9412-40cf-b4eb-418422a0c7a4)
Error when updating using winget from wingetui.
Updates using the system default winget complete normally.

### WingetUI Log

```text
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\tools.py", line 706, in <module>

🔴    File ".\tools.py", line 706, in <module>

🔴    File "<frozen ntpath>", line 251, in dirname

🔴    File "<frozen ntpath>", line 251, in dirname

🔴    File "<frozen ntpath>", line 213, in split

🔴    File "<frozen ntpath>", line 213, in split

🔴  TypeError: expected str, bytes or os.PathLike object, not NoneType

🔴  TypeError: expected str, bytes or os.PathLike object, not NoneType

🔴 Note this traceback was caught by reporter and has been added to the log (expected str, bytes or os.PathLike object, not NoneType)
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
It took 0.003000497817993164 to load all language files
🟢 checkQueue Thread started!
🔵 Found default chocolatey installation on expected location
🟢 Updating outdated language file...
🟢 Using cached lang file
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:7058
Press CTRL+C to quit
expected str, bytes or os.PathLike object, not NoneType
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\wingetui.exe
🔵 Reactivation signal ignored: RaiseWindow_[1696395447.7105687]
{'sudoFound': False, 'sudoVersion': False, 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool is disabled', 'WingetFound': True, 'WingetVersion': 'v1.5.1881  ', 'ChocolateyFound': True, 'ChocolateyVersion': '2.2.2  '}
🔵 Reached main ui load milestone
Can't disconnect
Can't disconnect
Can't disconnect
C:/Program Files/WingetUI/resources/installed_masked_white.png
🟢 Discover tab loaded successfully
🟢 Total packages: 0
Can't disconnect
Can't disconnect
Can't disconnect
Can't disconnect
C:/Program Files/WingetUI/resources/update_masked_white.png
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
Can't disconnect
Can't disconnect
Can't disconnect
C:/Program Files/WingetUI/resources/pin_masked_white.png
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
Can't disconnect
🟢 Starting winget source search...
🟢 Starting winget source search...
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 winget source search finished
🟢 winget source search finished
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
Win32Mica Error: win32 version 19045 is not supported
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
Win32Mica Error: win32 version 19045 is not supported
🟢 Main application loaded...
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
🟡 package 프레젠테이션                   60d7de failed parsing, going for method 2...
🟡 package ThunderboltTM 제어 센터        AppU failed parsing, going for method 2...
🟡 package 꿀뷰                           Ho failed parsing, going for method 2...
🟡 package 카카오톡                       Kaka failed parsing, going for method 2...
🟡 package Microsoft 마우스 키보드 센터   Microsof failed parsing, going for method 2...
🟡 package MSN 날씨                       Mi failed parsing, going for method 2...
🟡 package 앱 설치 관리자                 Micros failed parsing, going for method 2...
🟡 package 게임 서비스                    Micro failed parsing, going for method 2...
🟡 package 도움말                         Mic failed parsing, going for method 2...
🟡 package 한국어 로컬 경험 팩            Microsof failed parsing, going for method 2...
🟡 package 그림판 3D                      Mic failed parsing, going for method 2...
🟡 package 3D 뷰어                        Mi failed parsing, going for method 2...
🟡 package Microsoft 스티커 메모          Micro failed parsing, going for method 2...
🟡 package Mixed Reality 포털             Mi failed parsing, going for method 2...
🟡 package Microsoft 피플                 Mi failed parsing, going for method 2...
🟡 package 캡처 및 스케치                 Micros failed parsing, going for method 2...
🟡 package Microsoft Store 환경 호스트    Micro failed parsing, going for method 2...
🟡 package 웹 미디어 확장                 Micros failed parsing, going for method 2...
🟡 package Microsoft 사진                 Mi failed parsing, going for method 2...
🟡 package Windows 시계                   Mi failed parsing, going for method 2...
🟡 package Windows 계산기                 Mic failed parsing, going for method 2...
🟡 package Windows 카메라                 Mic failed parsing, going for method 2...
🟡 package Windows 지도                   Mi failed parsing, going for method 2...
🟡 package Windows 음성 녹음기            Micro failed parsing, going for method 2...
🟡 package Xbox 콘솔 컴패니언             Micros failed parsing, going for method 2...
🟡 package Xbox 액세서리                  Micr failed parsing, going for method 2...
🟡 package 휴대폰과 연결                  Micros failed parsing, going for method 2...
🟡 package Windows 미디어 플레이어        Microso failed parsing, going for method 2...
🟡 package 영화 및 TV                     Mic failed parsing, going for method 2...
🟡 package Linux용 Windows 하위 시스템    Micros failed parsing, going for method 2...
🟡 package 샤나인코더 5.3.1.1             Shana failed parsing, going for method 2...
🟡 package Google 드라이브                daa7 failed parsing, going for method 2...
🟡 package Chrome 원격 데스크톱           e7a915 failed parsing, going for method 2...
🟡 package 메일 및 일정                   micro failed parsing, going for method 2...
🟡 package 한컴오피스 2022                {12F5 failed parsing, going for method 2...
🟡 package 에스원VP                       {38 failed parsing, going for method 2...
🟡 package AppCheck 안티랜섬웨어          {8AE36 failed parsing, going for method 2...
🟡 package NVIDIA 그래픽 드라이버 537.13  {B2FE19 failed parsing, going for method 2...
🟡 package NVIDIA PhysX 시스템 소프트웨…  {B2FE19 failed parsing, going for method 2...
C:/Program Files/WingetUI/resources/pin_masked_white.png
🟢 Winget search for installed packages finished with 209 result(s)
Traceback (most recent call last):
  File ".\Interface\SoftwareSections.py", line 1493, in addItem
TypeError: 'PySide6.QtWidgets.QTreeWidgetItem.setIcon' called with wrong argument types:
  PySide6.QtWidgets.QTreeWidgetItem.setIcon(int, NoneType)
Supported signatures:
  PySide6.QtWidgets.QTreeWidgetItem.setIcon(int, Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap])
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 209
🔵 Starting Chocolatey search for updates
🔵 Starting Winget search for updates
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🔵 Loading WingetUI log...
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Loading WingetUI log...
🟢 Searching for string " "
🟢 Searching for string ""
🟢 Searching for string " "
🟢 Searching for string "  "
🟢 Searching for string "  "
🔵 Loading dynamic packages for query   
🔵 Searching packages on chocolatey for query   
🔵 Starting Winget search for dynamic packages
🟢 Searching for string "a"
🟢 Searching for string ""
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string "w"
🟢 Searching for string "wi"
🟢 Searching for string "win"
🟢 Searching for string "wing"
🟢 Searching for string "winge"
🟢 Searching for string "winget"
🔵 Loading dynamic packages for query winget
🔵 Searching packages on chocolatey for query winget
🔵 Starting Winget search for dynamic packages
🟢 Winget search for updates finished with 1 result(s)
🟢 Searching for string "d"
🟢 Searching for string "de"
🔵 Loading dynamic packages for query de
🔵 Searching packages on chocolatey for query de
🔵 Starting Winget search for dynamic packages
🟢 Searching for string "dee"
🟢 Searching for string "de"
🟢 Searching for string "ded"
🟢 Searching for string "dede"
🟢 Searching for string "ded"
🟢 Winget search for updates finished with 19 result(s)
🔵 Loading dynamic packages for query ded
🔵 Searching packages on chocolatey for query ded
🔵 Starting Winget search for dynamic packages
🟢 Searching for string "de"
🟢 Searching for string "dee"
🟢 Searching for string "deep"
🟢 Searching for string "deep"
🔵 Loading dynamic packages for query deep
🔵 Searching packages on chocolatey for query deep
🔵 Starting Winget search for dynamic packages
🟢 Winget search for updates finished with 7 result(s)
🟢 Winget search for updates finished with 2 result(s)
🟢 Searching for string "deep"
🟢 Starting winget source search...
🟢 winget source search finished
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
🔵 Loading WingetUI log...
🔵 Saving log...
🔵 Loading WingetUI log...
🟡 log save cancelled!
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------Chocolatey
Chocolatey v2.2.2
0 packages installed.

---------Winget
- 
   \ 
                                                                                                                        
Failed in attempting to update the source: winget
- 
                                                                                                                        
Failed when searching source; results will not be included: winget
Name                           Id                                                        Version
--------------------------------------------------------------------------------------------------------
Game Controller Tester         11032Reconco.XboxControllerTester_thvmwcgtjwwvy           1.7.26.0
EyeTune                        13183Mancoast.EyeTune_k7gtqf3v1rgjm                       0.9.7.0
***************************************************
My company's security program was included in the list, so I removed it.
My company's security program was included in the list, so I removed it.
My company's security program was included in the list, so I removed it.
My company's security program was included in the list, so I removed it.
My company's security program was included in the list, so I removed it.
My company's security program was included in the list, so I removed it.
My company's security program was included in the list, so I removed it.
My company's security program was included in the list, so I removed it.
My company's security program was included in the list, so I removed it.
***************************************************
VIVEPORT Diagnosis             {f88bbc8e-bb9e-41a6-9772-e827c795d039}                    1.2.4.4---------Chocolatey
Chocolatey v2.2.2
0 packages installed.---------Chocolatey
Chocolatey v2.2.2
Outdated Packages
Output is package name | current version | available version | pinned?Chocolatey has determined 0 package(s) are outdated.

---------Winget
- 
   \ 
   | 
                                                                                                                        
Failed in attempting to update the source: winget
- 
                                                                                                                        
Failed when searching source; results will not be included: winget
No installed package found matching input criteria.------- Winget query   - 
   \ 
                                                                                                                        
Failed in attempting to update the source: wingetFailed when searching source; results will not be included: wingetNo package found matching input criteria.

------- Winget query winget- 
   \ 
   | 
                                                                                                                        
Failed in attempting to update the source: wingetFailed when searching source; results will not be included: wingetName                           Id             Version Source--------------------------------------------------------------WinGet-AutoUpdate-Configurator XP89BSK82W9J28 Unknown msstore

------- Winget query de- 
   \ 
                                                                                                                        
Failed in attempting to update the source: wingetFailed when searching source; results will not be included: wingetName                                              Id           Version Source-------------------------------------------------------------------------------Curso de Java                                     9NBLGGH1NPRF Unknown msstoreCâmara de Lobos                                   9P0D9RHQFTDP Unknown msstoreMunicípio de Salvaterra de Magos                  9P1D9Q1JKT67 Unknown msstoreEstrategias de Inversion                          9NBLGGH4N8RR Unknown msstoreTalleres de Cordoba                               9NBLGGGZZJL4 Unknown msstorePaquete de experiencia local en español (España)  9NWVGWLHPB1Z Unknown msstorePrism Conversor de Vídeo                          9NTSCCJR4B15 Unknown msstoreVoz de Esperanza App                              9NBLGGH51QKR Unknown msstoreDoxillion Software Conversor de Documento         9P0F2HFR2R1M Unknown msstoreSpeed Test - Le Blog de la Tech                   9NQWH29N048D Unknown msstoreVille de Rouen                                    9NBLGGH5L7V8 Unknown msstoreFondos de Inversion                               9NBLGGH4N7XS Unknown msstoreGenerador de horarios para centros educativos     9N7N7NNFHJKL Unknown msstoreNumérologie (algèbre de votre destinée)           9NJ2Q2MPBG9D Unknown msstorePacote de Experiência Local em Português (Brasil) 9P8LBDM4FW35 Unknown msstorePapel de Parede ZX                                9NBLGGH5GBF5 Unknown msstorePaquete de experiencia local en español (México)  9N8MCM1X3928 Unknown msstoreInglés de Negocios                                9WZDNCRDG60S Unknown msstoreManipulador De Alimentos Test                     9MTTLHF4DNSJ Unknown msstore

------- Winget query deep- 
   \ 
                                                                                                                        
Failed in attempting to update the source: wingetFailed when searching source; results will not be included: wingetName                                               Id           Version Source--------------------------------------------------------------------------------Deep Relaxation                                    9NBLGGH4M9J6 Unknown msstoreDeep Unzip                                         9PBCSP1Q5V40 Unknown msstoreDeep Relax Sounds                                  9PCKV329TNS0 Unknown msstoreKabbalah, deep spiritual meditation, reincarnation 9N90600292Q6 Unknown msstoreDeep Breath                                        9NBLGGH6972F Unknown msstoreHoloDeepEX                                         9P4DT1XFJGXS Unknown msstoreDeepNotes                                          9PH76W3HPQZJ Unknown msstore

------- Winget query ded- 
   \ 
   | 
                                                                                                                        
Failed in attempting to update the source: wingetFailed when searching source; results will not be included: wingetName                                       Id           Version Source------------------------------------------------------------------------Deduplicator                               9NBLGGH4WDRN Unknown msstoreNatural Deduction using Strict Implication 9N3B5NB9PKGX Unknown msstore
```

**Comment by marticliment** [comment]
Yes, it is the same issue, please subscribe to that thread

**Comment by Leuconoe** [comment]
Fixed, thank you!
