### ISSUE TITLE
[BUG] wingetUI isn't displaying current information for chocolatey package curl

### ISSUE THREAD

**Issue by 12932** [marticliment/WingetUI#1489]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

WingetUI is showing curl as version 8.3.0 for the chocolatey package manager, but the current version on Chocolatey (as of posting this) is 8.4.0

### Steps to reproduce the issue

Open WingetUI
Search for "curl" in the Discover Packages tab

### WingetUI Log

```text
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
🔵 It took 0.0030012130737304688 to load all language files
🟢 checkQueue Thread started!
🔵 Found default chocolatey installation on expected location
🔵 Starting main application...
🟢 Updating outdated language file...
🟢 Using cached lang file
Win32Mica Error: win32 version 19045 is not supported
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:7058
Press CTRL+C to quit
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\...
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'WingetFound': True, 'WingetVersion': 'v1.6.2771  ', '.NET ToolFound': True, '.NET ToolVersion': '8.0.100-rc.1.23463.5\r', 'PipFound': True, 'PipVersion': 'pip 23.1.2 from C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pip (python 3.11)   ', 'ScoopFound': True, 'ScoopVersion': "Current Scoop version: v0.3.1 - Released at 2022-11-15  'cargo-lambda' bucket: 34fc90b Release v0.19.0  'main' bucket: 49c33b59e sccache: Update to version 0.4.2  ", 'ChocolateyFound': True, 'ChocolateyVersion': '2.2.2  ', 'NpmFound': True, 'NpmVersion': '8.10.0 '}
🔵 Reached main ui load milestone
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\MainWindow.py", line 51, in __init__

🔴    File ".\Interface\MainWindow.py", line 51, in __init__

🔴  AssertionError: Invalid window geometry format

🔴  AssertionError: Invalid window geometry format

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid window geometry format)
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting Pip search for installed packages
🔵 Starting Npm search for installed packages
🔵 Starting .NET Tool search for installed packages
🟢 Searching for string ""
🟢 .NET Tool search for installed packages finished with 10 result(s)
🟢 Starting winget source search...
🟢 Starting winget source search...
🟢 Starting scoop search...
🟢 Starting scoop search...
🟢 Settings tab loaded!
🟢 winget source search finished
🟢 winget source search finished
🟢 About tab loaded!
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
Win32Mica Error: win32 version 19045 is not supported
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 Scoop bucket search finished
🟢 Scoop bucket search finished
Win32Mica Error: win32 version 19045 is not supported
🟢 Main application loaded...
🟢 Searching for string ""
🟢 Pip search for installed packages finished with 194 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Scoop search for installed packages finished with 2 result(s)
🟢 Searching for string ""
🟢 Npm search for installed packages finished with 4 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 231 result(s)
🔵 Starting Scoop search for updates
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 441
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
🔵 Starting Pip search for updates
🔵 Starting Npm search for updates
🔵 Starting .NET Tool search for updates
🟡 Installing dotnet-tools-outdated, that was missing...
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Scoop search for updates finished with 2 result(s)
🟢 Searching for string ""
🟢 Npm search for updates finished with 4 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 90 result(s)
🟢 Searching for string ""
[b'You can invoke the tool using the following command: dotnet-tools-outdated\r\n', b"Tool 'dotnet-tools-outdated' (version '0.6.0') was successfully installed.\r\n"]
🟢 .NET Tool search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Pip search for updates finished with 120 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 215
🟢 Starting winget source search...
🟢 Starting scoop search...
🟢 winget source search finished
🟢 Scoop bucket search finished
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
🟢 Starting winget source search...
🟢 winget source search finished
🟢 Searching for string "d"
🟢 Searching for string "df"
🔵 Loading dynamic packages for query df
🔵 Starting Pip search for dynamic packages
🔵 Starting Npm search for dynamic packages
🔵 Searching packages on chocolatey for query df
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟡 Installing scoop-search, that was missing...
🟡 Installing pip-search, that was missing...
🟢 .NET Tool package query finished successfully
🟢 Npm search for updates finished with 23 result(s)
🟢 Winget search for updates finished with 130 result(s)
🟢 Scoop search for updates finished with 19 result(s)
🟢 Searching for string "s"
🟢 Searching for string "sp"
🟢 Searching for string "spa"
🟢 Searching for string "spac"
🟢 Searching for string "space"
🟢 Searching for string "spaces"
🟢 Searching for string "spacesn"
🟢 Searching for string "spacesni"
🟢 Searching for string "spacesnif"
🟢 Searching for string "spacesniff"
🟢 Searching for string "spacesniffe"
🟢 Searching for string "spacesniffer"
🔵 Loading dynamic packages for query spacesniffer
🔵 Starting Pip search for dynamic packages
🔵 Starting Npm search for dynamic packages
🔵 Searching packages on chocolatey for query spacesniffer
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Pip search for updates finished with 5 result(s)
🟢 Scoop search for updates finished with 0 result(s)
🟢 Winget search for updates finished with 1 result(s)
🟢 Npm search for updates finished with 0 result(s)
🟢 Pip search for updates finished with 2 result(s)
🟢 .NET Tool package query finished successfully
🟢 Searching for string "spacesniffer"
🟢 Searching for string ""
🟢 Searching for string "w"
🟢 Searching for string "wi"
🟢 Searching for string "wiz"
🟢 Searching for string "wizt"
🟢 Searching for string "wiztr"
🟢 Searching for string "wiztre"
🟢 Searching for string "wiztree"
🔵 Loading dynamic packages for query wiztree
🔵 Starting Pip search for dynamic packages
🔵 Starting Npm search for dynamic packages
🔵 Searching packages on chocolatey for query wiztree
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Scoop search for updates finished with 0 result(s)
🟢 Winget search for updates finished with 1 result(s)
🟢 Pip search for updates finished with 2 result(s)
🟢 .NET Tool package query finished successfully
🟢 Npm search for updates finished with 0 result(s)
🟢 Searching for string "c"
🟢 Searching for string "cu"
🟢 Searching for string "cur"
🟢 Searching for string "curl"
🔵 Loading dynamic packages for query curl
🔵 Starting Pip search for dynamic packages
🔵 Starting Npm search for dynamic packages
🔵 Searching packages on chocolatey for query curl
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Scoop search for updates finished with 5 result(s)
🟢 .NET Tool package query finished successfully
🟢 Pip search for updates finished with 8 result(s)
🟢 Npm search for updates finished with 20 result(s)
🟢 Winget search for updates finished with 4 result(s)
🟢 Searching for string "curl"
🟢 Waiting for install permission... title=cURL, id=cURL.cURL, installId=1697111195.2409072
🔵 Given package: <Package: cURL;cURL.cURL;8.4.0;Winget: winget;<PackageManagers.winget.WingetPackageManager object at 0x000001A3C1ECF590>;<Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x000001A3C30431C0>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🔵 Found icon:  https://community.chocolatey.org/content/packageimages/curl.7.88.1.png
Win32Mica Error: win32 version 19045 is not supported
🔵 Current program set to 1697111195.2409072
🟢 Have permission to install, starting installation threads...
🔵 Starting <Package: cURL;cURL.cURL;8.4.0;Winget: winget;<PackageManagers.winget.WingetPackageManager object at 0x000001A3C1ECF590>;<Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x000001A3C30431C0>> installation with Command ['C:\\Program Files\\WingetUI\\PackageManagers\\winget-cli_x64\\winget.exe', 'install', '--id', 'cURL.cURL', '--exact', '--accept-source-agreements', '--disable-interactivity', '--accept-package-agreements']
['-', '\\', '███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 8.11 MB', '███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 8.11 MB', '███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 8.11 MB', '██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 8.11 MB', '██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 8.11 MB', '██████████████████████▒▒▒▒▒▒▒▒  6.00 MB / 8.11 MB', '█████████████████████████▒▒▒▒▒  7.00 MB / 8.11 MB', '█████████████████████████████▒  8.00 MB / 8.11 MB', '██████████████████████████████  8.11 MB / 8.11 MB', '-', 'Found cURL [cURL.cURL] Version 8.4.0', 'This application is licensed to you by its owner.', 'Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.', 'Downloading https://curl.se/windows/dl-8.4.0_1/curl-8.4.0_1-win64-mingw.zip', '-', '\\', '|', '/', '-', '\\', '▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0.00 B / 10.0 MB', '████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.01 MB / 10.0 MB', '██████████████████████████████  10.0 MB / 10.0 MB', 'Successfully verified installer hash', 'Extracting archive...', 'Successfully extracted archive', 'Starting package install...', 'Path environment variable modified; restart your shell to use the new value.', 'Command line alias added: "curl"', 'Successfully installed', '']
🔵 Adding package to the uninstall section...
Exception ignored in: <function BaseWindowsToaster.show_toast.<locals>.<lambda> at 0x000001A3C300EB60>
Traceback (most recent call last):
  File "windows_toasts\toasters.py", line 147, in <lambda>
  File ".\Interface\CustomWidgets\GenericWidgets.py", line 717, in <lambda>
TypeError: ToastNotification.reportException() missing 1 required positional argument: 'id'
🟢 Waiting for install permission... title=Curl, id=curl, installId=1697111318.6873834
🔵 Given package: <Package: Curl;curl;8.4.0_1;Scoop: main;<PackageManagers.scoop.ScoopPackageManager object at 0x000001A3C1F257D0>;<Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x000001A3C2FF9EC0>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🔵 Found cached image in C:\Users\admin\.wingetui/cachedmeta/curl.icon.png
Win32Mica Error: win32 version 19045 is not supported
🔵 Current program set to 1697111318.6873834
🟢 Have permission to install, starting installation threads...
🔵 Starting <Package: Curl;curl;8.4.0_1;Scoop: main;<PackageManagers.scoop.ScoopPackageManager object at 0x000001A3C1F257D0>;<Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x000001A3C2FF9EC0>> installation with Command ['powershell', '-ExecutionPolicy', 'ByPass', '-Command', 'scoop', 'install', 'main/curl']
["Installing '7zip' (23.01) [64bit] from main bucket", 'Downloading https://www.7-zip.org/a/7z2301-x64.msi (1.8 MB)...', 'Checking hash of 7z2301-x64.msi ... ok.', 'Extracting 7z2301-x64.msi ... done.', 'Linking ~\\scoop\\apps\\7zip\\current => ~\\scoop\\apps\\7zip\\23.01', "Creating shim for '7z'.", "Creating shim for '7zFM'.", "Creating shim for '7zG'.", 'Creating shortcut for 7-Zip (7zFM.exe)', 'Persisting Codecs', 'Persisting Formats', 'Running post_install script...', "'7zip' (23.01) was installed successfully!", 'Notes', '-----', 'Add 7-Zip as a context menu option by running: "C:\\Users\\admin\\scoop\\apps\\7zip\\current\\install-context.reg"', "Installing 'curl' (8.4.0_1) [64bit] from main bucket", 'Downloading https://curl.se/windows/dl-8.4.0_1/curl-8.4.0_1-win64-mingw.tar.xz (5.9 MB)...', 'Checking hash of curl-8.4.0_1-win64-mingw.tar.xz ... ok.', 'Extracting curl-8.4.0_1-win64-mingw.tar.xz ... done.', 'Linking ~\\scoop\\apps\\curl\\current => ~\\scoop\\apps\\curl\\8.4.0_1', "Creating shim for 'curl'.", "'curl' (8.4.0_1) was installed successfully!", '']
Exception ignored in: <function BaseWindowsToaster.show_toast.<locals>.<lambda> at 0x000001A3C300FBA0>
Traceback (most recent call last):
  File "windows_toasts\toasters.py", line 147, in <lambda>
  File ".\Interface\CustomWidgets\GenericWidgets.py", line 717, in <lambda>
🔵 Adding package to the uninstall section...
TypeError: ToastNotification.reportException() missing 1 required positional argument: 'id'
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting Pip search for installed packages
🔵 Starting Npm search for installed packages
🔵 Starting .NET Tool search for installed packages
🟢 Searching for string ""
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\SpecificWidgets.py", line 865, in <lambda>
  File ".\Interface\CustomWidgets\SpecificWidgets.py", line 1162, in addItemsToTreeWidget
KeyError: <Interface.CustomWidgets.SpecificWidgets.InstalledPackageItem object at 0x000001A3C3330100>
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 Pip search for installed packages finished with 198 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Npm search for installed packages finished with 4 result(s)
🟢 Searching for string ""
🟢 Scoop search for installed packages finished with 5 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 232 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 440
Win32Mica Error: win32 version 19045 is not supported
Win32Mica Error: win32 version 19045 is not supported
🟢 Waiting for install permission... title=Curl, id=curl, installId=1697111518.1468687
🔵 Given package: <Package: Curl;curl;8.4.0_1;Scoop: main;<PackageManagers.scoop.ScoopPackageManager object at 0x000001A3C1F257D0>;<Interface.CustomWidgets.SpecificWidgets.InstalledPackageItem object at 0x000001A3C3040140>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=True;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🔵 Found cached image in C:\Users\admin\.wingetui/cachedmeta/curl.icon.png
Win32Mica Error: win32 version 19045 is not supported
🔵 Current program set to 1697111518.1468687
🟢 Have permission to install, starting installation threads...
🔵 Starting <Package: Curl;curl;8.4.0_1;Scoop: main;<PackageManagers.scoop.ScoopPackageManager object at 0x000001A3C1F257D0>;<Interface.CustomWidgets.SpecificWidgets.InstalledPackageItem object at 0x000001A3C3040140>> uninstall with Command ['C:\\Program Files\\WingetUI\\components\\gsudo.exe', 'powershell', '-ExecutionPolicy', 'ByPass', '-Command', 'scoop', 'uninstall', 'main/curl', '--global']
["ERROR 'curl' isn't installed globally, but it may be installed locally.", 'WARN  Try again without the --global (or -g) flag instead.', '']
Win32Mica Error: win32 version 19045 is not supported
Exception ignored in: <function BaseWindowsToaster.show_toast.<locals>.<lambda> at 0x000001A3C8A9F100>
Traceback (most recent call last):
  File "windows_toasts\toasters.py", line 147, in <lambda>
  File ".\Interface\CustomWidgets\GenericWidgets.py", line 717, in <lambda>
TypeError: ToastNotification.reportException() missing 1 required positional argument: 'id'
Win32Mica Error: win32 version 19045 is not supported
🟢 Waiting for install permission... title=Curl, id=curl, installId=1697111527.684864
🔵 Given package: <Package: Curl;curl;8.4.0_1;Scoop: main;<PackageManagers.scoop.ScoopPackageManager object at 0x000001A3C1F257D0>;<Interface.CustomWidgets.SpecificWidgets.InstalledPackageItem object at 0x000001A3C3040140>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🔵 Found cached image in C:\Users\admin\.wingetui/cachedmeta/curl.icon.png
Win32Mica Error: win32 version 19045 is not supported
🔵 Current program set to 1697111527.684864
🟢 Have permission to install, starting installation threads...
🔵 Starting <Package: Curl;curl;8.4.0_1;Scoop: main;<PackageManagers.scoop.ScoopPackageManager object at 0x000001A3C1F257D0>;<Interface.CustomWidgets.SpecificWidgets.InstalledPackageItem object at 0x000001A3C3040140>> uninstall with Command ['powershell', '-ExecutionPolicy', 'ByPass', '-Command', 'scoop', 'uninstall', 'main/curl']
["Uninstalling 'curl' (8.4.0_1).", "Removing shim 'curl.shim'.", "Removing shim 'curl.exe'.", 'Unlinking ~\\scoop\\apps\\curl\\current', "'curl' was uninstalled.", '']
Exception ignored in: <function BaseWindowsToaster.show_toast.<locals>.<lambda> at 0x000001A3C8AE02C0>
Traceback (most recent call last):
  File "windows_toasts\toasters.py", line 147, in <lambda>
  File ".\Interface\CustomWidgets\GenericWidgets.py", line 717, in <lambda>
TypeError: ToastNotification.reportException() missing 1 required positional argument: 'id'
🔵 Sending cancel signal...
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Searching for string "curl"
🔵 Loading dynamic packages for query curl
🔵 Starting Pip search for dynamic packages
🔵 Starting Npm search for dynamic packages
🔵 Searching packages on chocolatey for query curl
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Scoop search for updates finished with 5 result(s)
🟢 Winget search for updates finished with 4 result(s)
🟢 .NET Tool package query finished successfully
🟢 Npm search for updates finished with 20 result(s)
🟢 Pip search for updates finished with 8 result(s)
🟡 No valid screenshots were found
🔵 Found cached image in C:\Users\admin\.wingetui/cachedmeta/curl.icon.png
🔵 Starting get info for Curl on Chocolatey
<br>curl is used in command lines or scripts to transfer data. It is also used in cars, television sets, routers, printers, audio equipment, mobile phones, tablets, settop boxes, media players and is the internet transfer backbone for thousands of software applications affecting billions of humans daily.<br><b style="font-size:12.5pt;"><br> Features</b><br>Supports DICT, FILE, FTP, FTPS, GOPHER, GOPHERS, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, MQTT, POP3, POP3S, RTMP, RTMPS, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET and TFTP. curl supports SSL certificates, HTTP POST, HTTP PUT, FTP uploading, HTTP form based upload, proxies, HTTP/2, HTTP/3, cookies, user+password authentication (Basic, Plain, Digest, CRAM-MD5, NTLM, Negotiate and Kerberos), file transfer resume, proxy tunneling and more.
<br>
<br>
🟢 Starting get info for id curl
🟢 Get info finished for Curl on Chocolatey
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Dont think this is relevant
```

### Relevant information

wingetUI is showing curl version as 8.3.0 for chocolatey, but when I visit the chocolatey website for the curl package it shows 8.4.0 as the latest version. is this because the checks on chocolatey haven't completed yet?

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/68835423/d4131d23-8a6e-4968-bbf9-aa51bf21afa4)

![image](https://github.com/marticliment/WingetUI/assets/68835423/539ca178-1049-43f4-9e73-f687d6bc308a)

Interestingly the last updated date is correct, but the version number is not:

![image](https://github.com/marticliment/WingetUI/assets/68835423/d8d6f129-6c5f-48a7-b068-d741d0261371)

**Comment by marticliment** [comment]
Hello,

This issue was likely a temporary issue caused by package list caching. All packages show up-to-date now with chocolatey.
