### ISSUE TITLE
[BUG] Bugs on package exporting

### ISSUE THREAD

**Issue by marticliment** [marticliment/WingetUI#1528]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

N/A

### WingetUI Log

```text
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\tools.py", line 701, in <module>

🔴    File ".\tools.py", line 701, in <module>

🔴    File "<frozen ntpath>", line 251, in dirname

🔴    File "<frozen ntpath>", line 251, in dirname

🔴    File "<frozen ntpath>", line 213, in split

🔴    File "<frozen ntpath>", line 213, in split

🔴  TypeError: expected str, bytes or os.PathLike object, not NoneType

🔴  TypeError: expected str, bytes or os.PathLike object, not NoneType

🔴 Note this traceback was caught by reporter and has been added to the log (expected str, bytes or os.PathLike object, not NoneType)






🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\GenericSections.py", line 469, in exportSettings

🔴    File ".\Interface\GenericSections.py", line 469, in exportSettings

🔴    File "encodings\cp1252.py", line 19, in encode

🔴    File "encodings\cp1252.py", line 19, in encode

🔴  UnicodeEncodeError: 'charmap' codec can't encode characters in position 1589-1618: character maps to <undefined>

🔴  UnicodeEncodeError: 'charmap' codec can't encode characters in position 1589-1618: character maps to <undefined>

🔴 Note this traceback was caught by reporter and has been added to the log ('charmap' codec can't encode characters in position 1589-1618: character maps to <undefined>)
```

### Package Managers Logs

```text
N/A
```

**Comment by marticliment** [comment]
Likely fixed, the whole procedure has been changed
