### ISSUE TITLE
[BUG] Not scalling on higher resolution monitor

### ISSUE THREAD

**Issue by DavidPampel** [marticliment/WingetUI#1601]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When utilizing WingetUI on a monitor with, for example, 150% scaling, the application does not adjust accordingly. Consequently, when used on a laptop with high resolution, the app becomes challenging to use.

### Steps to reproduce the issue

Use it on a screen with more then 100% scaling set in windows settings.

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.029674530029296875 to load all language files
🟢 checkQueue Thread started!
🔵 Found default chocolatey installation on expected location
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:7058
Press CTRL+C to quit
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1701332245.996935]
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\...
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'PipFound': False, 'PipVersion': 'Pip ist deaktiviert', 'NpmFound': False, 'NpmVersion': 'Npm ist deaktiviert', '.NET ToolFound': False, '.NET ToolVersion': '', 'WingetFound': True, 'WingetVersion': 'v1.6.2771  ', 'ChocolateyFound': True, 'ChocolateyVersion': '2.2.2  ', 'ScoopFound': True, 'ScoopVersion': "Current Scoop version: v0.3.1 - Released at 2022-11-15  'main' bucket:  "}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting .NET Tool search for installed packages
🟢 Searching for string ""
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🟢 .NET Tool search for installed packages finished with 0 result(s)
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting .NET Tool search for updates
🟡 Installing dotnet-tools-outdated, that was missing...
[b'Der Befehl "dotnet.exe" ist entweder falsch geschrieben oder\r\n', b'konnte nicht gefunden werden.\r\n']
🟢 .NET Tool search for updates finished with 0 result(s)
🟢 Starting winget source search...
🟢 Starting winget source search...
🟢 Starting scoop search...
🟢 Chocolatey search for installed packages finished with 7 result(s)
🟢 Starting scoop search...
🟢 winget source search finished
🔵 Starting Winget search for updates
🟢 Settings tab loaded!
🟢 winget source search finished
🟢 Scoop search for installed packages finished with 0 result(s)
🔵 Starting Scoop search for updates
🟢 About tab loaded!
🟢 Scoop bucket search finished
list index out of range list index out of range
IndexError: list index out of range
list index out of range list index out of range
IndexError: list index out of range
🔵 Starting Chocolatey search for updates
IndexError: list index out of range
IndexError: list index out of range
🟢 Scoop bucket search finished
🟢 Scoop search for updates finished with 0 result(s)
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Main application loaded...
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟡 package APK 安装程序                             1818 failed parsing, going for method 2...
🟢 Winget search for installed packages finished with 169 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 176
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting .NET Tool search for installed packages
🟢 Searching for string ""
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 7 result(s)
🟢 Searching for string ""
🟢 Searching for string "s"
🟢 Searching for string "sa"
🟢 Scoop search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Searching for string "sam"
🟢 Searching for string "sams"
🟢 Searching for string "samsu"
🟢 Searching for string "samsun"
🟢 Searching for string "samsung"
🟡 package APK 安装程序                             1818 failed parsing, going for method 2...
🟢 Winget search for installed packages finished with 169 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 177
🔵 Loading dynamic packages for query samsung
🔵 Searching packages on chocolatey for query samsung
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Searching for string "samsung "
🟢 .NET Tool package query finished successfully
🔵 Loading dynamic packages for query samsung 
🔵 Searching packages on chocolatey for query samsung 
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Searching for string "samsung i"
🟢 .NET Tool package query finished successfully
🔵 Loading dynamic packages for query samsung i
🔵 Searching packages on chocolatey for query samsung i
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Searching for string "samsung in"
🟢 .NET Tool package query finished successfully
🔵 Loading dynamic packages for query samsung in
🔵 Searching packages on chocolatey for query samsung in
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Searching for string "samsung int"
🟢 .NET Tool package query finished successfully
🔵 Loading dynamic packages for query samsung int
🔵 Searching packages on chocolatey for query samsung int
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Searching for string "samsung inte"
🟢 Searching for string "samsung inter"
🟢 .NET Tool package query finished successfully
🔵 Loading dynamic packages for query samsung inter
🔵 Searching packages on chocolatey for query samsung inter
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Searching for string "samsung intern"
🟢 .NET Tool package query finished successfully
🔵 Loading dynamic packages for query samsung intern
🔵 Searching packages on chocolatey for query samsung intern
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Searching for string "samsung interne"
🟢 .NET Tool package query finished successfully
🔵 Loading dynamic packages for query samsung interne
🔵 Searching packages on chocolatey for query samsung interne
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Searching for string "samsung internet"
🟢 .NET Tool package query finished successfully
🔵 Loading dynamic packages for query samsung internet
🔵 Searching packages on chocolatey for query samsung internet
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 Winget search for updates finished with 30 result(s)
🟢 .NET Tool package query finished successfully
🟢 Winget search for updates finished with 23 result(s)
🟢 Winget search for updates finished with 0 result(s)
🟢 Winget search for updates finished with 0 result(s)
🟢 Winget search for updates finished with 0 result(s)
🟢 Winget search for updates finished with 0 result(s)
🟢 Winget search for updates finished with 0 result(s)
🟢 Winget search for updates finished with 0 result(s)
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string "samsung internet"
🟢 Scoop search for updates finished with 0 result(s)
🟢 Scoop search for updates finished with 0 result(s)
🟢 Scoop search for updates finished with 0 result(s)
🟢 Scoop search for updates finished with 0 result(s)
🟢 Scoop search for updates finished with 0 result(s)
🟢 Scoop search for updates finished with 0 result(s)
🟢 Scoop search for updates finished with 0 result(s)
🟢 Scoop search for updates finished with 0 result(s)
🟢 Scoop search for updates finished with 0 result(s)
🟢 Searching for string "samsung "
🟢 Searching for string "samsung"
🔵 Loading dynamic packages for query samsung
🔵 Searching packages on chocolatey for query samsung
🔵 Starting Winget search for dynamic packages
🔵 Starting Scoop search for dynamic packages
🔵 Starting .NET Tool query search
🟢 .NET Tool package query finished successfully
🟢 Scoop search for updates finished with 0 result(s)
🟢 Winget search for updates finished with 30 result(s)
🟢 Searching for string "samsung"
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\SoftwareSections.py", line 2163, in loadPackageScreenshots

🔴    File ".\Interface\SoftwareSections.py", line 2163, in loadPackageScreenshots

🔴  KeyError: ''

🔴  KeyError: ''
```

### Package Managers Logs

```text
not necessary
```

### Screenshots and videos

![Screenshot 2023-12-01 101054](https://github.com/marticliment/WingetUI/assets/131004821/f360b1eb-7df6-445c-8263-f054ba7adc6d)

**Comment by ppvnf** [comment]
related to https://github.com/marticliment/WingetUI/issues/285

**Comment by marticliment** [comment]
Hello,

please try downloading the latest beta
