### ISSUE TITLE
[BUG] (Winget component not working, hangs in 2.1.2-beta and in earlier releases)

### ISSUE THREAD

**Issue by ExpPhysU** [marticliment/WingetUI#1625]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Winget is installed on win 11 23H2 with latest updates. It works.
However the Winget-Section in WingetUi 2.1.2-beta hangs

![grafik](https://github.com/marticliment/WingetUI/assets/33446790/007c98b1-8178-4e80-9b4b-04697cd17ff2)

### Steps to reproduce the issue

Bug appear independent of  the situation
- uninstall winget and winget ui and reinstall
- reset winget in wingetui

### WingetUI Log

```text
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
🔵 It took 0.0 to load all language files
🟢 checkQueue Thread started!
Exception in thread Tools: get foreground window:
Traceback (most recent call last):
  File "threading.py", line 1052, in _bootstrap_inner
  File "threading.py", line 989, in run
  File ".\tools.py", line 517, in foregroundWindowThread
ImportError: Module use of python311.dll conflicts with this version of Python.
🟡 Chocolatey was not found on the default location, perhaps a portable WingetUI installation?
🟢 Updating outdated language file...
🟢 Using cached lang file
---------------------------------------------------------------------------------------------------

   WingetUI version 2.1.2-beta (version number 2.119) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token be4dae6561023d3e4a2b460e986253f10731471b75bc2a9e9a77865eb3743bf7
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1702412948.6002963]
🟢 Found valid aumid C:\Users\Othmar\scoop\apps\wingetui\current\WingetUI.exe
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', 'ChocolateyFound': True, 'ChocolateyVersion': '', 'WingetFound': True, 'WingetVersion': '', '.NET ToolFound': True, '.NET ToolVersion': '7.0.404\r', 'ScoopFound': True, 'ScoopVersion': "Current Scoop version: v0.3.1 - Released at 2022-11-15  'extras' bucket: af033e3cf yubioath: Update to version 6.3.1  'main' bucket: 9ca9444ff winget: Update to version 1.6.3421  ", 'PipFound': True, 'PipVersion': 'pip 23.3.1 from C:\\Users\\Othmar\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\pip (python 3.10)   '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting Pip search for installed packages
🔵 Starting .NET Tool search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Starting winget source search...
🟢 Starting winget source search...
🟢 Starting scoop search...
🟢 Starting scoop search...
🟢 Settings tab loaded!
🟢 winget source search finished
🟢 winget source search finished
🟢 About tab loaded!
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🟢 Main application loaded...
🟢 Searching for string ""
🟢 Scoop search for installed packages finished with 0 result(s)
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Scoop bucket search finished
🟢 Scoop bucket search finished
🟢 Pip search for installed packages finished with 14 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 15
🔵 Starting Pip search for updates
🔵 Starting .NET Tool search for updates
🔵 Starting Winget search for updates
🔵 Starting Scoop search for updates
🔵 Starting Chocolatey search for updates
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Starting winget source search...
🟢 Starting scoop search...
🟢 winget source search finished
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟢 .NET Tool search for updates finished with 1 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Scoop bucket search finished
🟢 Pip search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Scoop search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 1
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------Winget

---------Winget

---------Chocolatey
Chocolatey v2.2.2
0 packages installed.-------dotnet
Paket-ID                   Version      Befehle
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated

---------Scoop
Installed apps:

Name         Version Source Updated             Info

-------dotnet
Paket-ID                   Version      Befehle
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated

---------Chocolatey
Chocolatey v2.2.2
0 packages installed.---------Winget
--------dotnet

Package Id            Current Available
---------------------------------------
dotnet-tools-outdated 0.6.0   0.6.1---------Chocolatey
Chocolatey v2.2.2
Outdated Packages
Output is package name | current version | available version | pinned?Chocolatey has determined 0 package(s) are outdated.---------Pip
---------Scoop
Scoop is up to date.
Everything is ok!
```

### Screenshots and videos

![Screenshot 2023-12-12 213058](https://github.com/marticliment/WingetUI/assets/33446790/af3f08de-c334-4934-9074-097cf7fa4e77)

**Comment by marticliment** [comment]
Hello, could you please give more details on the hang?

Thanks!

**Comment by mi-skam** [comment]
I have the same issue. I can also provide logs, if needed.

**Comment by marticliment** [comment]
@mi-skam, does the file exist? Reinstallign WingetUI does restore this file to a working state?

**Comment by mi-skam** [comment]
It exists, but does nothing.

**Comment by ExpPhysU** [comment]
Same for me, ...\winget-cli_x64\winget.exe is there, independent wheter wingetui is installed from git or from scoop. The windows installation of winget (is there in parallel) is a modern windows app, i.e. there is no direct winget.exe from microsoft. Using a link to %localappdata%\microsoft\WindowsApps\winget.exe does not help either.
Did Microsoft change thew protocol?
Thanks for Wingetui

**Comment by marticliment** [comment]
Winget binaries have been updated to a newer version

**Comment by candrapersada** [comment]
the problem persists in wingetui WingetUI 2.2.0
```
C:\Program Files\WingetUI\wingetui\PackageEngine\Managers\winget-cli_x64
λ gsudo winget source reset
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt
```
```
winget path: "C:\Program Files\WingetUI\wingetui\resources\..\winget-cli\PackageManagers\winget-cli_x64\winget.exe"
Performing reset...
The system cannot find the path specified.
'.\winget.exe' is not recognized as an internal or external command,
operable program or batch file.
'.\winget.exe' is not recognized as an internal or external command,
operable program or batch file.
'.\winget.exe' is not recognized as an internal or external command,
operable program or batch file.
Info: Cache session closed.
Task completed!
You can now close this window and refresh your package lists
Press any key to continue . . .
```

**Comment by marticliment** [comment]
Could you please enable system winget and try it again? Thanks!

**Comment by candrapersada** [comment]
yes working
