### ISSUE TITLE
Wants to install version already installed

### ISSUE THREAD

**Issue by chjohans** [marticliment/WingetUI#1659]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I have Ultimaker Cura Version 5.6.0 installed (latest version at this time), together with an older version 4.8.0..

WingetUI is asking me to upgrade version 4.8.0 to version 5.6.0.

Obviously that is not necessary as I alreacdy have version 5.6.0 installed. WingetUI should check and not offer to upgrade to a version that is already installed, even if older versions are installed as well - obviously by choice.

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.012012243270874023 to load all language files
🟢 checkQueue Thread started!
🟢 Updating outdated language file...
🟢 Using cached lang file
🔵 Found default chocolatey installation on expected location
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0-beta (version number 2.91) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\__main__.py", line 69, in <module>

🔴    File ".\__main__.py", line 69, in <module>

🔴    File ".\PackageEngine\Classes.py", line 39, in __init__

🔴    File ".\PackageEngine\Classes.py", line 39, in __init__

🔴  AttributeError: 'NoneType' object has no attribute 'NAME'

🔴  AttributeError: 'NoneType' object has no attribute 'NAME'

🔴 Note this traceback was caught by reporter and has been added to the log ('NoneType' object has no attribute 'NAME')
🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token 0c09f4990104b20ab2348cd146021d0c3091e2d64b39c949cd97b704f8e39f65
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Starting Winget source search...
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Winget source search finished with 2 sources
🔵 Reactivation signal ignored: RaiseWindow_[1703488793.8097646]
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\winget...
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool is disabled', 'WingetFound': True, 'WingetVersion': 'v1.6.3133  ', 'PowerShellFound': False, 'PowerShellVersion': '', 'ChocolateyFound': True, 'ChocolateyVersion': '2.2.2  '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🟢 Winget source search finished with 2 sources
🟢 About tab loaded!
🟢 Chocolatey search for installed packages finished with 0 result(s)
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
🟢 Scoop source search finished with 5 sources
🔵 Starting Winget search for updates
🟢 Chocolatey source search finished with 0 sources
🟢 PowerShell source search finished with 0 sources
🟢 Main application loaded...
🔵 Starting Chocolatey search for updates
🔵 Starting PowerShell source search...
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Searching for string ""
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Searching for string ""
🟢 PowerShell source search finished with 0 sources
🔵 Starting PowerShell search for updates
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 557 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 557
🟢 Winget search for updates finished with 24 result(s)
🟡 Package FinalWire.AIDA64.Engineer has version 6.92 ignored
🟡 Package Amazon.Kindle has version * ignored
🟡 Package REALiX.HWiNFO has version 7.68 ignored
🟡 Package BinaryFortress.DisplayFusion has version * ignored
🟡 Package Treexy.DriverFusion has version * ignored
🟡 Package Ultimaker.Cura has version 5.6.0 ignored
🟡 Package Ubisoft.Connect has version * ignored
🟡 Package Resplendence.WhySoSlow has version 1.61 ignored
🟡 Package WinDirStat.WinDirStat has version 1.1.2 ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Multiple versions of Microsoft.DotNet.SDK.5 are installed, latest version is installed. Not showing the update
🟡 Package H2IK.JoystickGremlin has version 13.3 ignored
🟡 Package Garmin.BaseCamp has version * ignored
🟡 Package Microsoft.DotNet.Runtime.6 has version * ignored
🟡 Package Python.Launcher has version * ignored
🟡 Multiple versions of Microsoft.DotNet.Runtime.3_1 are installed, latest version is installed. Not showing the update
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Package Google.EarthPro has version * ignored
🟡 Package DavidTHOIRON.FotoSketcher has version 3.80 ignored
🟡 Package MSI.Kombustor.4 has version 4.1.20.0 ignored
🟡 Package Microsoft.DotNet.Runtime.6 has version * ignored
🟡 Package Microsoft.VCRedist.2005.x86 has version 8.0.61001 ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
🔵 Starting PowerShell source search...
🟢 PowerShell source search finished with 0 sources
🔵 Starting PowerShell search for updates
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 24 result(s)
🟡 Package FinalWire.AIDA64.Engineer has version 6.92 ignored
🟡 Package Amazon.Kindle has version * ignored
🟡 Package REALiX.HWiNFO has version 7.68 ignored
🟡 Package BinaryFortress.DisplayFusion has version * ignored
🟡 Package Treexy.DriverFusion has version * ignored
🟡 Package Ultimaker.Cura has version 5.6.0 ignored
🟡 Package Ubisoft.Connect has version * ignored
🟡 Package Resplendence.WhySoSlow has version 1.61 ignored
🟡 Package WinDirStat.WinDirStat has version 1.1.2 ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Multiple versions of Microsoft.DotNet.SDK.5 are installed, latest version is installed. Not showing the update
🟡 Package H2IK.JoystickGremlin has version 13.3 ignored
🟡 Package Garmin.BaseCamp has version * ignored
🟡 Package Microsoft.DotNet.Runtime.6 has version * ignored
🟡 Package Python.Launcher has version * ignored
🟡 Multiple versions of Microsoft.DotNet.Runtime.3_1 are installed, latest version is installed. Not showing the update
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Package Google.EarthPro has version * ignored
🟡 Package DavidTHOIRON.FotoSketcher has version 3.80 ignored
🟡 Package MSI.Kombustor.4 has version 4.1.20.0 ignored
🟡 Package Microsoft.DotNet.Runtime.6 has version * ignored
🟡 Package Microsoft.VCRedist.2005.x86 has version 8.0.61001 ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Winget source search finished with 2 sources
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🟢 PowerShell source search finished with 0 sources
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
🟢 Scoop source search finished with 5 sources
🟢 Chocolatey source search finished with 1 sources
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
https://marticliment.com/wingetui/help?isWingetUIIframe
https://marticliment.com/wingetui/help?isWingetUIIframe
https://marticliment.com/wingetui/help?isWingetUIIframe
https://marticliment.com/wingetui/help?isWingetUIIframe
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\SpecificWidgets.py", line 603, in resetAll
AttributeError: 'NoneType' object has no attribute 'click'
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting PowerShell source search...
🟢 PowerShell source search finished with 0 sources
🔵 Starting PowerShell search for updates
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 24 result(s)
🟡 Package FinalWire.AIDA64.Engineer has version 6.92 ignored
🟡 Package Amazon.Kindle has version * ignored
🟡 Package REALiX.HWiNFO has version 7.68 ignored
🟡 Package BinaryFortress.DisplayFusion has version * ignored
🟡 Package Treexy.DriverFusion has version * ignored
🟡 Package Ubisoft.Connect has version * ignored
🟡 Package Resplendence.WhySoSlow has version 1.61 ignored
🟡 Package WinDirStat.WinDirStat has version 1.1.2 ignored
🟡 Multiple versions of Microsoft.DotNet.SDK.5 are installed, latest version is installed. Not showing the update
🟡 Package H2IK.JoystickGremlin has version 13.3 ignored
🟡 Package Garmin.BaseCamp has version * ignored
🟡 Package Python.Launcher has version * ignored
🟡 Multiple versions of Microsoft.DotNet.Runtime.3_1 are installed, latest version is installed. Not showing the update
🟡 Package Google.EarthPro has version * ignored
🟡 Package DavidTHOIRON.FotoSketcher has version 3.80 ignored
🟡 Package MSI.Kombustor.4 has version 4.1.20.0 ignored
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 8
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.012012243270874023 to load all language files
🟢 checkQueue Thread started!
🟢 Updating outdated language file...
🟢 Using cached lang file
🔵 Found default chocolatey installation on expected location
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0-beta (version number 2.91) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\__main__.py", line 69, in <module>

🔴    File ".\__main__.py", line 69, in <module>

🔴    File ".\PackageEngine\Classes.py", line 39, in __init__

🔴    File ".\PackageEngine\Classes.py", line 39, in __init__

🔴  AttributeError: 'NoneType' object has no attribute 'NAME'

🔴  AttributeError: 'NoneType' object has no attribute 'NAME'

🔴 Note this traceback was caught by reporter and has been added to the log ('NoneType' object has no attribute 'NAME')
🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token 0c09f4990104b20ab2348cd146021d0c3091e2d64b39c949cd97b704f8e39f65
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Starting Winget source search...
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Winget source search finished with 2 sources
🔵 Reactivation signal ignored: RaiseWindow_[1703488793.8097646]
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\winget...
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool is disabled', 'WingetFound': True, 'WingetVersion': 'v1.6.3133  ', 'PowerShellFound': False, 'PowerShellVersion': '', 'ChocolateyFound': True, 'ChocolateyVersion': '2.2.2  '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🟢 Winget source search finished with 2 sources
🟢 About tab loaded!
🟢 Chocolatey search for installed packages finished with 0 result(s)
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
🟢 Scoop source search finished with 5 sources
🔵 Starting Winget search for updates
🟢 Chocolatey source search finished with 0 sources
🟢 PowerShell source search finished with 0 sources
🟢 Main application loaded...
🔵 Starting Chocolatey search for updates
🔵 Starting PowerShell source search...
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Searching for string ""
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Searching for string ""
🟢 PowerShell source search finished with 0 sources
🔵 Starting PowerShell search for updates
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 557 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 557
🟢 Winget search for updates finished with 24 result(s)
🟡 Package FinalWire.AIDA64.Engineer has version 6.92 ignored
🟡 Package Amazon.Kindle has version * ignored
🟡 Package REALiX.HWiNFO has version 7.68 ignored
🟡 Package BinaryFortress.DisplayFusion has version * ignored
🟡 Package Treexy.DriverFusion has version * ignored
🟡 Package Ultimaker.Cura has version 5.6.0 ignored
🟡 Package Ubisoft.Connect has version * ignored
🟡 Package Resplendence.WhySoSlow has version 1.61 ignored
🟡 Package WinDirStat.WinDirStat has version 1.1.2 ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Multiple versions of Microsoft.DotNet.SDK.5 are installed, latest version is installed. Not showing the update
🟡 Package H2IK.JoystickGremlin has version 13.3 ignored
🟡 Package Garmin.BaseCamp has version * ignored
🟡 Package Microsoft.DotNet.Runtime.6 has version * ignored
🟡 Package Python.Launcher has version * ignored
🟡 Multiple versions of Microsoft.DotNet.Runtime.3_1 are installed, latest version is installed. Not showing the update
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Package Google.EarthPro has version * ignored
🟡 Package DavidTHOIRON.FotoSketcher has version 3.80 ignored
🟡 Package MSI.Kombustor.4 has version 4.1.20.0 ignored
🟡 Package Microsoft.DotNet.Runtime.6 has version * ignored
🟡 Package Microsoft.VCRedist.2005.x86 has version 8.0.61001 ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
🔵 Starting PowerShell source search...
🟢 PowerShell source search finished with 0 sources
🔵 Starting PowerShell search for updates
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 24 result(s)
🟡 Package FinalWire.AIDA64.Engineer has version 6.92 ignored
🟡 Package Amazon.Kindle has version * ignored
🟡 Package REALiX.HWiNFO has version 7.68 ignored
🟡 Package BinaryFortress.DisplayFusion has version * ignored
🟡 Package Treexy.DriverFusion has version * ignored
🟡 Package Ultimaker.Cura has version 5.6.0 ignored
🟡 Package Ubisoft.Connect has version * ignored
🟡 Package Resplendence.WhySoSlow has version 1.61 ignored
🟡 Package WinDirStat.WinDirStat has version 1.1.2 ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Multiple versions of Microsoft.DotNet.SDK.5 are installed, latest version is installed. Not showing the update
🟡 Package H2IK.JoystickGremlin has version 13.3 ignored
🟡 Package Garmin.BaseCamp has version * ignored
🟡 Package Microsoft.DotNet.Runtime.6 has version * ignored
🟡 Package Python.Launcher has version * ignored
🟡 Multiple versions of Microsoft.DotNet.Runtime.3_1 are installed, latest version is installed. Not showing the update
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Package Google.EarthPro has version * ignored
🟡 Package DavidTHOIRON.FotoSketcher has version 3.80 ignored
🟡 Package MSI.Kombustor.4 has version 4.1.20.0 ignored
🟡 Package Microsoft.DotNet.Runtime.6 has version * ignored
🟡 Package Microsoft.VCRedist.2005.x86 has version 8.0.61001 ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟡 Package Microsoft.DotNet.AspNetCore.6 has version * ignored
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Winget source search finished with 2 sources
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🟢 PowerShell source search finished with 0 sources
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
🟢 Scoop source search finished with 5 sources
🟢 Chocolatey source search finished with 1 sources
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
https://marticliment.com/wingetui/help?isWingetUIIframe
https://marticliment.com/wingetui/help?isWingetUIIframe
https://marticliment.com/wingetui/help?isWingetUIIframe
https://marticliment.com/wingetui/help?isWingetUIIframe
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\SpecificWidgets.py", line 603, in resetAll
AttributeError: 'NoneType' object has no attribute 'click'
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting PowerShell source search...
🟢 PowerShell source search finished with 0 sources
🔵 Starting PowerShell search for updates
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 24 result(s)
🟡 Package FinalWire.AIDA64.Engineer has version 6.92 ignored
🟡 Package Amazon.Kindle has version * ignored
🟡 Package REALiX.HWiNFO has version 7.68 ignored
🟡 Package BinaryFortress.DisplayFusion has version * ignored
🟡 Package Treexy.DriverFusion has version * ignored
🟡 Package Ubisoft.Connect has version * ignored
🟡 Package Resplendence.WhySoSlow has version 1.61 ignored
🟡 Package WinDirStat.WinDirStat has version 1.1.2 ignored
🟡 Multiple versions of Microsoft.DotNet.SDK.5 are installed, latest version is installed. Not showing the update
🟡 Package H2IK.JoystickGremlin has version 13.3 ignored
🟡 Package Garmin.BaseCamp has version * ignored
🟡 Package Python.Launcher has version * ignored
🟡 Multiple versions of Microsoft.DotNet.Runtime.3_1 are installed, latest version is installed. Not showing the update
🟡 Package Google.EarthPro has version * ignored
🟡 Package DavidTHOIRON.FotoSketcher has version 3.80 ignored
🟡 Package MSI.Kombustor.4 has version 4.1.20.0 ignored
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 8
🔵 Loading WingetUI log...
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/24390228/24d7edaa-45fa-4fe5-bb9a-36f1d3296bdc)

**Comment by marticliment** [comment]
I am sorry, but this is an issue with cura only, because of the way their installers work.

You might want to skip versions/ignore curs for updated until they get this fixed.
