### ISSUE TITLE
[BUG] Horizontal scroll bar on top of settings page

### ISSUE THREAD

**Issue by umnovI** [marticliment/WingetUI#1666]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

After the new update I've got a scroll bar at the top of settings/about page.
![image](https://github.com/marticliment/WingetUI/assets/30232564/01192b51-061e-4d6a-a78e-63cf22ffae0e)
![image](https://github.com/marticliment/WingetUI/assets/30232564/2c8dc1a5-6033-41d3-957b-7a6c7fad5b2e)

### Steps to reproduce the issue

- update to 2.2.0
- open settings/about page

### WingetUI Log

```text
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
🔵 It took 0.0015494823455810547 to load all language files
🟢 checkQueue Thread started!
🔵 Found default chocolatey installation on expected location
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\__main__.py", line 69, in <module>

🔴    File ".\__main__.py", line 69, in <module>

🔴    File ".\PackageEngine\Classes.py", line 39, in __init__

🔴    File ".\PackageEngine\Classes.py", line 39, in __init__

🔴  AttributeError: 'NoneType' object has no attribute 'NAME'

🔴  AttributeError: 'NoneType' object has no attribute 'NAME'

🔴 Note this traceback was caught by reporter and has been added to the log ('NoneType' object has no attribute 'NAME')
🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token 0c66a0a7c217f7842ea14f6e81c83c3b4e2367c7fce6e3ad1f4e0e82c5a61f0c
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🔵 Starting Winget source search...
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🟢 Winget source search finished with 2 sources
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\Winget...
🔵 Reactivation signal ignored: RaiseWindow_[1703799112.6316478]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', '.NET ToolFound': False, '.NET ToolVersion': '', 'PowerShellFound': False, 'PowerShellVersion': '', 'WingetFound': True, 'WingetVersion': 'v1.6.3482  ', 'NpmFound': True, 'NpmVersion': '10.2.3 '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Npm search for installed packages
🔵 Starting .NET Tool search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 .NET Tool search for installed packages finished with 0 result(s)
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🟢 Winget source search finished with 2 sources
🟢 About tab loaded!
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
🟢 Scoop source search finished with 5 sources
🔵 Starting Npm search for updates
🟢 Chocolatey source search finished with 1 sources
🟢 Main application loaded...
🔵 Starting .NET Tool search for updates
🔵 Starting Winget search for updates
🔵 Starting PowerShell source search...
🟡 Installing dotnet-tools-outdated, that was missing...
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
[b'The command could not be loaded, possibly because:\r\n', b'  * You intended to execute a .NET application:\r\n', b"      The application 'tool' does not exist.\r\n", b'  * You intended to execute a .NET SDK command:\r\n', b'      No .NET SDKs were found.\r\n', b'\r\n', b'Download a .NET SDK:\r\n', b'https://aka.ms/dotnet/download\r\n', b'\r\n', b'Learn about SDK resolution:\r\n', b'https://aka.ms/dotnet/sdk-not-found\r\n']
🟢 Searching for string ""
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 .NET Tool search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🟢 Npm search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟡 package Планшет Wacom 㠴ㄯἕ뛶؀蠀                   Wa failed parsing, going for method 2...
🟢 Winget search for installed packages finished with 201 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 202
🟢 Starting package backup...
🔵 Backup path set to C:\Users\ilyaa\Documents\WingetUI\Laptop-15ACH6A installed packages 29-12-2023 00.39.json
🟢 Package backup succeeded!
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🟢 Npm search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 1 result(s)
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
🟢 Searching for string ""
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Winget source search finished with 2 sources
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
🟢 Scoop source search finished with 5 sources
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟠 Unable to retrieve announcement image
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴  FileNotFoundError: [Errno 2] No such file or directory: '~\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴  FileNotFoundError: [Errno 2] No such file or directory: '~\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: '~\\AppData/Local/WingetUI/CachedIcons\\announcement.png')
🟢 Chocolatey source search finished with 1 sources
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 24: invalid start byte

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 24: invalid start byte

🔴 Note this traceback was caught by reporter and has been added to the log ('utf-8' codec can't decode byte 0x8a in position 24: invalid start byte)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 1
🟢 PowerShell source search finished with 1 sources
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 -------dotnet
The command could not be loaded, possibly because:

-------dotnet
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

---------Npm
~

---------
. :  㧨 䠩 ~\Documents\WindowsPowerShell\profile.ps1, ⠪  믮 業ਥ ⪫
祭  ⮩ ⥬.  祭 ⥫ ᢥ . about_Execution_Policies   https:/go.microsoft.
com/fwlink/?LinkID=135170.
ப:1 :3
+ . '~\Documents\WindowsPowerShell\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : 訡 ᭮: (:) [], PSSecurityException
+ FullyQualifiedErrorId : UnauthorizedAccess

--------dotnet

"dotnet-tools-outdated"   ७  譥
, ᯮ塞 ணࠬ   䠩.---------Npm
---------Npm
~\AppData\Roaming\npm
`-- eslint@8.56.0---------Winget
- 
   \ 
                                                                                                                        

   - 
   \ 
   | 
                                                                                                                        
Name                                     Id                                        Version            Available  Source
-----------------------------------------------------------------------------------------------------------------------
Divinity: Original Sin 2 - Sir Lora      1326441817_is1                            3.6.117.3735_ptbr
Divinity: Original Sin 2 - Definitive E… 1584823040_is1                            3.6.117.3735_ptbr
NVM for Windows 1.1.12                   CoreyButler.NVMforWindows                 1.1.12                        winget
Marmoset Viewer 1.0.0                    61bc8947-3f88-593a-93ad-6e1d1ce09dc7      1.0.0
7-Zip ZS 22.01 ZS v1.5.5 R2 (x64)        mcmilk.7zip-zstd                          22.01 ZS v1.5.5 R2            winget
Adobe After Effects 2022                 AEFT_22_2_1                               22.2.1
AMD Software                             AMD Catalyst Install Manager              23.12.1
AMD Chipset Software                     AMD_Chipset_IODrivers                     4.06.10.651
Adobe Media Encoder 2022                 AME_22_2                                  22.2
Adobe Audition 2022                      AUDT_22_2                                 22.2
AVG AntiVirus Free                       AVG Antivirus                             23.12.3314
Adobe Digital Editions 4.5               Adobe Digital Editions 4.5                4.5.11
Adobe Express                            AdobeSystemsIncorporated.AdobeCreativeCl… 2.1.1.0
AMD Radeon Software                      AdvancedMicroDevicesInc-RSXCM_fhmx3h6dzf… 22.10.0.0
Autodesk Identity Manager                Autodesk.AutodeskAccess                   1.10.4.0           1.43.0.186 winget
Brave                                    Brave.Brave                               120.1.61.109                  winget
CPUID HWMonitor 1.52                     CPUID.HWMonitor                           1.52                          winget
CrystalDiskInfo 9.2.1                    CrystalDewWorld.CrystalDiskInfo           9.2.1                         winget
DJV2                                     Humanity.DJV2                             2.0.8                         winget
Discord                                  Discord.Discord                           1.0.9018           1.0.9025   winget
Dolby Vision                             DolbyLaboratories.DolbyVisionHDR_rz1tebt… 2.20301.388.0
Lenovo Companion                         E046963F.LenovoCompanion_k1h2ywk1493x8    10.2312.17.0
Lenovo Hotkeys                           E0469640.LenovoUtility_5grkq8ppsgwt4      4.5.109.0
FBReader                                 FBReader.ORGLimited.FBReader_n9cpejf4jr0… 2.0.5.0
GitHub Desktop                           GitHub.GitHubDesktop                      3.3.5                         winget
Git                                      Git.Git                                   2.43.0                        winget
GNU Privacy Guard                        GnuPG.GnuPG                               2.4.3                         winget
Google Chrome                            Google.Chrome                             120.0.6099.130                winget
Gpg4win (4.2.0)                          GnuPG.Gpg4win                             4.2.0                         winget
Houdini 20.0.506                         Houdini 20.0.506                          20.0.506
Houdini Launcher                         Houdini Launcher                          20.0.506
Adobe Illustrator 2023                   ILST_27_5                                 27.5
Marmoset Toolbag 4                       MSET_Toolbag4                             Unknown
Mari 6.0v2                               Mari6.0v2                                 6.0v2
Marvelous Designer Personal              Marvelous Designer Personal               7.1.143
Microsoft Edge                           Microsoft Edge                            120.0.2210.91
Microsoft Edge Update                    Microsoft Edge Update                     1.3.181.5
Среда выполнения Microsoft Edge WebView… Microsoft EdgeWebView                     120.0.2210.91
Cortana                                  Microsoft.549981C3F5F10_8wekyb3d8bbwe     4.2308.1005.0
AV1 Video Extension                      Microsoft.AV1VideoExtension_8wekyb3d8bbwe 1.1.61781.0
MSN Weather                              Microsoft.BingWeather_8wekyb3d8bbwe       4.53.52331.0
App Installer                            Microsoft.AppInstaller                    1.21.3482.0                   winget
DirectX                                  Microsoft.DirectXRuntime_8wekyb3d8bbwe    9.29.1974.0
Gaming Services                          Microsoft.GamingServices_8wekyb3d8bbwe    17.84.7001.0
Get Help                                 Microsoft.GetHelp_8wekyb3d8bbwe           10.2308.12552.0
HEIF Image Extensions                    Microsoft.HEIFImageExtension_8wekyb3d8bb… 1.0.63001.0
HEVC Video Extensions from Device Manuf… Microsoft.HEVCVideoExtension_8wekyb3d8bb… 2.0.61931.0
Пакет локализованного интерфейса на рус… Microsoft.LanguageExperiencePackru-RU_8w… 22621.47.187.0
MPEG-2 Video Extension                   Microsoft.MPEG2VideoExtension_8wekyb3d8b… 1.0.61931.0
Paint 3D                                 Microsoft.MSPaint_8wekyb3d8bbwe           1.0.68.0
3D Viewer                                Microsoft.Microsoft3DViewer_8wekyb3d8bbwe 7.2311.30032.0
Microsoft Edge                           Microsoft.MicrosoftEdge.Stable_8wekyb3d8… 120.0.2210.91
Microsoft Mahjong                        Microsoft.MicrosoftMahjong_8wekyb3d8bbwe  4.4.10270.0
Solitaire & Casual Games                 Microsoft.MicrosoftSolitaireCollection_8… 4.18.11210.0
Microsoft Sticky Notes                   Microsoft.MicrosoftStickyNotes_8wekyb3d8… 6.0.2.0
Microsoft Sudoku                         Microsoft.MicrosoftSudoku_8wekyb3d8bbwe   2.8.10203.0
Microsoft Treasure Hunt                  Microsoft.MicrosoftTreasureHunt_8wekyb3d… 2.4.7190.0
Mixed Reality Portal                     Microsoft.MixedReality.Portal_8wekyb3d8b… 2000.21051.1282.0
Microsoft .Net Native Framework Package… Microsoft.NET.Native.Framework.2.2_8weky… 2.2.29512.0
Microsoft .Net Native Runtime Package 2… Microsoft.NET.Native.Runtime.2.2_8wekyb3… 2.2.28604.0
OneDrive                                 Microsoft.OneDriveSync_8wekyb3d8bbwe      23246.1127.2.0
Outlook for Windows                      Microsoft.OutlookForWindows_8wekyb3d8bbwe 1.2023.1214.201
Microsoft People                         Microsoft.People_8wekyb3d8bbwe            10.2202.33.0
PowerToys ImageResizer Context Menu      Microsoft.PowerToys.ImageResizerContextM… 0.76.0.0
PowerToys PowerRename Context Menu       Microsoft.PowerToys.PowerRenameContextMe… 0.76.0.0
Raw Image Extension                      Microsoft.RawImageExtension_8wekyb3d8bbwe 2.1.63181.0
Snipping Tool                            Microsoft.ScreenSketch_8wekyb3d8bbwe      11.2310.54.0
Windows Security                         Microsoft.SecHealthUI_8wekyb3d8bbwe       1000.25873.9001.0
Microsoft Engagement Framework           Microsoft.Services.Store.Engagement_8wek… 10.0.23012.0
Store Experience Host                    Microsoft.StorePurchaseApp_8wekyb3d8bbwe  22310.1401.1.0
Microsoft Ultimate Word Games            Microsoft.Studios.Wordament_8wekyb3d8bbwe 4.2.10261.0
Microsoft To Do                          Microsoft.Todos_8wekyb3d8bbwe             2.110.63211.0
Microsoft.UI.Xaml.2.0                    Microsoft.UI.Xaml.2.0_8wekyb3d8bbwe       2.1810.18004.0
Microsoft.UI.Xaml.2.1                    Microsoft.UI.Xaml.2.1_8wekyb3d8bbwe       2.11906.6001.0
Microsoft.UI.Xaml.2.3                    Microsoft.UI.Xaml.2.3_8wekyb3d8bbwe       2.32002.13001.0
Microsoft.UI.Xaml.2.4                    Microsoft.UI.Xaml.2.4_8wekyb3d8bbwe       2.42007.9001.0
Microsoft.UI.Xaml.2.5                    Microsoft.UI.Xaml.2.5_8wekyb3d8bbwe       2.52012.2002.0
Microsoft.UI.Xaml.2.7                    Microsoft.UI.Xaml.2.7                     7.2208.15002.0                winget
Microsoft.UI.Xaml.2.8                    Microsoft.UI.Xaml.2.8                     8.2310.30001.0                winget
Microsoft Visual C++ 2012 UWP Desktop R… Microsoft.VCLibs.110.00.UWPDesktop_8weky… 11.0.61135.0
Microsoft Visual C++ 2013 UWP Desktop R… Microsoft.VCLibs.120.00.UWPDesktop_8weky… 12.0.40653.0
Microsoft Visual C++ 2013 Runtime Packa… Microsoft.VCLibs.120.00.Universal_8wekyb… 12.0.30501.0
Microsoft Visual C++ Runtime Package     Microsoft.VCLibs.120.00_8wekyb3d8bbwe     12.0.21005.1
Microsoft Visual C++ 2015 UWP Desktop R… Microsoft.VCLibs.Desktop.14               14.0.32530.0                  winget
Microsoft Visual C++ 2015 UWP Runtime P… Microsoft.VCLibs.140.00_8wekyb3d8bbwe     14.0.32530.0
VP9 Video Extensions                     Microsoft.VP9VideoExtensions_8wekyb3d8bb… 1.0.62911.0
Web Media Extensions                     Microsoft.WebMediaExtensions_8wekyb3d8bb… 1.0.62931.0
Webp Image Extensions                    Microsoft.WebpImageExtension_8wekyb3d8bb… 1.0.62681.0
Microsoft Whiteboard                     Microsoft.Whiteboard_8wekyb3d8bbwe        53.21027.539.0
Dev Home GitHub Extension (Preview)      Microsoft.Windows.DevHomeGitHubExtension… 0.800.344.0
Dev Home (Preview)                       Microsoft.DevHome                         0.801.344.0                   winget
Microsoft Photos                         Microsoft.Windows.Photos_8wekyb3d8bbwe    2023.11110.29003.0
Windows Clock                            Microsoft.WindowsAlarms_8wekyb3d8bbwe     11.2306.23.0
WindowsAppRuntime.1.2                    Microsoft.WindowsAppRuntime.1.2_8wekyb3d… 2000.802.31.0
WindowsAppRuntime.1.3                    Microsoft.WindowsAppRuntime.1.3_8wekyb3d… 3000.934.1904.0
WindowsAppRuntime.1.4                    Microsoft.WindowsAppRuntime.1.4_8wekyb3d… 4000.1049.117.0
Windows Calculator                       Microsoft.WindowsCalculator_8wekyb3d8bbwe 11.2307.4.0
Windows Camera                           Microsoft.WindowsCamera_8wekyb3d8bbwe     2023.2311.5.0
Feedback Hub                             Microsoft.WindowsFeedbackHub_8wekyb3d8bb… 1.2309.12711.0
Windows Maps                             Microsoft.WindowsMaps_8wekyb3d8bbwe       1.0.57.0
Windows Notepad                          Microsoft.WindowsNotepad_8wekyb3d8bbwe    11.2310.13.0
Windows Scan                             Microsoft.WindowsScan_8wekyb3d8bbwe       6.3.9654.17133
Windows Sound Recorder                   Microsoft.WindowsSoundRecorder_8wekyb3d8… 1.0.67.0
Microsoft Store                          Microsoft.WindowsStore_8wekyb3d8bbwe      22311.1401.2.0
Windows Terminal                         Microsoft.WindowsTerminal                 1.18.3181.0                   winget
Windows Package Manager Source (winget)  Microsoft.Winget.Source_8wekyb3d8bbwe     2023.1228.2210.772
Xbox TCUI                                Microsoft.Xbox.TCUI_8wekyb3d8bbwe         1.24.10001.0
Xbox Game Bar Plugin                     Microsoft.XboxGameOverlay_8wekyb3d8bbwe   1.54.4001.0
Game Bar                                 Microsoft.XboxGamingOverlay_8wekyb3d8bbwe 6.123.11012.0
Xbox Identity Provider                   Microsoft.XboxIdentityProvider_8wekyb3d8… 12.95.3001.0
Xbox Game Speech Window                  Microsoft.XboxSpeechToTextOverlay_8wekyb… 1.21.13002.0
Phone Link                               Microsoft.YourPhone_8wekyb3d8bbwe         1.23102.126.0
Windows Media Player                     Microsoft.ZuneMusic_8wekyb3d8bbwe         11.2310.8.0
Windows Web Experience Pack              MicrosoftWindows.Client.WebExperience_cw… 423.30700.0.0
Narrator Extension - Excel               MicrosoftWindows.NarratorScript.Excel_cw… 1.0.13.0
Narrator Extension - Outlook             MicrosoftWindows.NarratorScript.Outlook_… 1.0.6.0
Microsoft Aria (Natural) - English (Uni… MicrosoftWindows.Voice.en-US.Aria.1_cw5n… 1.0.8.0
Miniconda3 py311_23.10.0-1 (Python 3.11… Miniconda3 py311_23.10.0-1 (Python 3.11.… py311_23.10.0-1
Mozilla Firefox (x64 en-US)              Mozilla.Firefox                           121.0                         winget
Mozilla Maintenance Service              MozillaMaintenanceService                 110.0.1
MtoA for Maya 2024                       MtoA2024                                  5.3.1.1
Microsoft 365 - en-us                    O365HomePremRetail - en-us                16.0.17029.20068
Microsoft 365 - ru-ru                    O365HomePremRetail - ru-ru                16.0.17029.20068
OBS Studio                               OBSProject.OBSStudio                      30.0.2                        winget
Oh My Posh version 19.3.0                JanDeDobbeleer.OhMyPosh                   19.3.0                        winget
Microsoft OneDrive                       Microsoft.OneDrive                        23.246.1127.0002              winget
Microsoft OneNote - en-us                OneNoteFreeRetail - en-us                 16.0.17029.20068
Microsoft OneNote - ru-ru                OneNoteFreeRetail - ru-ru                 16.0.17029.20068
Adobe Photoshop 2022                     PHSP_23_3_1                               23.3.1.426
Adobe Premiere Pro 2022                  PPRO_22_2                                 22.2
Postman x86_64 10.21.0                   Postman.Postman                           10.21.0                       winget
PureRef                                  PureRef                                   1.11.1
Realtek Audio Control                    RealtekSemiconductorCorp.RealtekAudioCon… 1.39.283.0
RizomUV VS RS 2023.0                     RizomUV VS RS 2023.0_is1                  Unknown
Adobe Substance 3D Sampler               SBSTA_3_3_1                               3.3.1
Adobe Substance 3D Designer              SBSTD_13_0_1                              13.0.1
Adobe Substance 3D Painter               SBSTP_8_3_1                               8.3.1
Spotify                                  Spotify.Spotify                           1.2.26.1187.g36b7…            winget
Steam                                    Valve.Steam                               2.10.91.91                    winget
Blender                                  BlenderFoundation.Blender                 Unknown            4.0.2      winget
Telegram Desktop                         TelegramMessengerLLP.TelegramDesktop_t4v… 4.13.1.0
UXP WebView Support                      UXPW_1_1_0                                1.1.0
Lenovo Vantage Service                   VantageSRV_is1                            4.0.49.0
Планшет Wacom 㠴ㄯἕ뛶؀蠀                   Wacom.WacomTabletDriver                   6.4.4-3                       winget
ZBrush 2023.2.2                          ZBrush 2023.2.2 2023.2.2                  2023.2.2
Obsidian                                 Obsidian.Obsidian                         1.4.16             1.5.3      winget
Bridge 2023.1.0                          d31b3501-1485-515e-b9cc-ec663e464c2a      2023.1.0
Antares 0.7.20                           Fabio286.antares                          0.7.20                        winget
DbGate 5.2.7                             JanProchazka.dbgate                       5.2.7                         winget
Google Keep                              ff316073b75e8169db042ed81d72f2ac          1.0
Mail and Calendar                        microsoft.windowscommunicationsapps_8wek… 16005.14326.21768…
Adobe Express                            new.express.adobe.com-E403B1D1_jbhg725hw… 2.1.1.1
MayaUSD Extension 0.23.1 202304181210-1… {0CF7057F-1EE4-4142-851D-8A04A1ACA1D7}    0.23.1
Microsoft Windows Desktop Runtime - 3.1… Microsoft.DotNet.DesktopRuntime.3_1       3.1.32                        winget
Microsoft Windows Desktop Runtime - 8.0… Microsoft.DotNet.DesktopRuntime.8         8.0.0                         winget
Microsoft Visual C++ 2010 Redistributab… Microsoft.VCRedist.2010.x64               10.0.40219                    winget
OneMoreAddIn                             stevencohn.OneMore                        5.9.0                         winget
Microsoft Visual C++ 2015-2022 Redistri… Microsoft.VCRedist.2015+.x64              14.38.33130.0                 winget
Microsoft Visual Studio Code Insiders (… Microsoft.VisualStudioCode.Insiders       1.86.0                        winget
Lenovo Service Bridge                    {2C74547D-EF88-47F4-85F5-BE46A31E26B7}_i… 5.0.2.14
Microsoft Visual C++ 2015-2022 Redistri… Microsoft.VCRedist.2015+.x86              14.38.33130.0                 winget
Microsoft Windows Desktop Runtime - 6.0… Microsoft.DotNet.DesktopRuntime.6         6.0.25                        winget
Python Launcher                          Python.Launcher                           3.12.0                        winget
Microsoft ASP.NET Core 6.0.25 - Shared … Microsoft.DotNet.AspNetCore.6             6.0.25                        winget
PlanetVPN-2.7.8.23                       {33eecf4f-167f-4fa6-9e3e-5a4be965965c}_i… 2.7.8.23
Node.js                                  {3BC1471A-748E-48EE-94F3-024920ADA553}    20.10.0
Intel(R) C++ Redistributables on Intel(… {3E1C36F0-C3A2-4137-9DA4-8580CF6191E1}    19.0.324
Autodesk Maya 2024                       {42762096-E3FE-3521-9687-693E0B913A4F}    2024.1.0.4816
Bifrost 2.7.0.1 for Maya 2024            {46FC9650-C8C9-4C47-A1D3-75D12B2F7D55}    2.7.0.1
Microsoft Visual C++ 2013 Redistributab… {49e969a1-2990-464d-92b5-25f6f34573c6}    12.0.40664.0
Allegorithmic Substance Player 13.0.1    {5147d42e-226c-402a-a4cb-bfaf0bc5182d}_i… 13.0.1
DB Browser for SQLite                    DBBrowserForSQLite.DBBrowserForSQLite     3.12.2                        winget
Microsoft Visual C++ 2008 Redistributab… Microsoft.VCRedist.2008.x64               9.0.30729.6161                winget
PowerShell 7.3.10.0-x64                  Microsoft.PowerShell                      7.3.10.0           7.4.0.0    winget
Microsoft Visual C++ 2005 Redistributab… Microsoft.VCRedist.2005.x86               8.0.61001                     winget
Java 8 Update 391 (64-bit)               {71324AE4-039E-4CA4-87B4-2F64180391F0}    8.0.3910.13
Epic Online Services                     {758842D2-1538-4008-A8E3-66F65A061C52}    2.0.33.0
Microsoft Visual Studio Code (User)      Microsoft.VisualStudioCode                1.85.1                        winget
ImageGlass                               DuongDieuPhap.ImageGlass                  9.0.8.1208                    winget
Nefarius Software Solutions e.U. HidHid… {80A2C3FE-5F05-4DFC-BF1D-1ED32440D54A}    1.1.50.0
Autodesk LookdevX 1.1.0                  {82CC6B12-BF70-4CE7-BA9E-ABCD5F58F944}    1.1.0
WingetUI                                 SomePythonThings.WingetUIStore            2.2.0                         winget
Nefarius Virtual Gamepad Emulation Bus … ViGEm.ViGEmBus                            1.17.333.0         1.22.0     winget
Microsoft Visual C++ 2008 Redistributab… Microsoft.VCRedist.2008.x86               9.0.30729.6161                winget
KeePassXC                                KeePassXCTeam.KeePassXC                   2.7.6                         winget
NVIDIA Системное программное обеспечени… {B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_D… 9.17.0524
Epic Games Launcher                      EpicGames.EpicGamesLauncher               1.3.23.0           1.3.93.0   winget
Microsoft Update Health Tools            {C6FD611E-7EFE-488C-A0E0-974C09EF6473}    5.72.0.0
SpeedTree Games version 9.0.1            {C8D56161-3A2A-4DCD-A880-3F004895EDFF}_i… 9.0.1
Microsoft Visual C++ 2010 Redistributab… Microsoft.VCRedist.2010.x86               10.0.40219                    winget
gsudo v2.4.2                             gerardog.gsudo                            2.4.2                         winget
MPC-BE x64 1.6.11                        MPC-BE.MPC-BE                             1.6.11                        winget
Python 3.10.11 (64-bit)                  Python.Python.3.10                        3.10.11                       winget
Microsoft Visual C++ 2012 Redistributab… {a2199617-3609-410f-a8e8-e8806c73545b}    11.0.61030.0
Microsoft Visual C++ 2005 Redistributab… {ad8a2fa1-06e7-4b0d-927d-6e54b3d31028}    8.0.61000
Microsoft Visual C++ 2013 Redistributab… {d2c8df0e-f15d-4426-9e51-f13f329f9cb4}    12.0.40664.0
Adobe Substance 3D for Maya 2024-2.3.2   {e2dfd9b3-4f98-4696-a524-97b7ab092406}_i… 2.3.2
Microsoft Visual C++ 2012 Redistributab… {f0080ca2-80ae-4958-b6eb-e8fa916d744a}    11.0.61030.0
PowerToys (Preview) x64                  Microsoft.PowerToys                       0.76.2                        winget
Microsoft Windows Desktop Runtime - 6.0… Microsoft.DotNet.DesktopRuntime.6         6.0.25                        winget---------Npm@global
---------Winget
- 
                                                                                                                        

   - 
   \ 
   | 
                                                                                                                        
Name                    Id                   Version  Available Source
----------------------------------------------------------------------
PowerShell 7.3.10.0-x64 Microsoft.PowerShell 7.3.10.0 7.4.0.0   winget
1 upgrades available.
7 package(s) have pins that prevent upgrade. Use the 'winget pin' command to view and edit pins. Using the --include-pinned argument may show more results.
```

### Relevant information

Path to home directory was replaced with ~

**Comment by marticliment** [comment]
Hello,

I can't see the attached pictures

**Comment by umnovI** [comment]
That's weird. I didn't anything with them.
What about now?
![image](https://github.com/marticliment/WingetUI/assets/30232564/6279f291-71e9-409b-93f7-002ccf4cd3bc)
![image](https://github.com/marticliment/WingetUI/assets/30232564/531bb4ac-1471-46c1-911c-80cd5d068407)

**Comment by marticliment** [comment]
Yes, now I can see them.

The issue you are facing is the same as #1629. 

I will mark this as duplicate
