### ISSUE TITLE
[BUG] When using <Select All Packages> on Search filter, all packages in system is uninstalled.

### ISSUE THREAD

**Issue by GKilsgaard** [marticliment/WingetUI#1678]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I think this is at bug, but it could be as designed, but had a bad experience.

I wantes to uninstall the powershell package [AzureRM].
So i wint in installed packages and used "Search on your Software" to locate all AzureRm packages. 
Then i pressed "Select all Packages" 
And pressed "Uninstall Selected Packages"

Then I left my computer and when i got back it was in the process of uninstalling all applications, packages etc. that was installed on my computer.

I thought that "Select all packages" was referring to the selected list in the grid, but it looks like it is all packages in the complete list.

hope this gives any sense..
[packagemanagerlog.txt](https://github.com/marticliment/WingetUI/files/13812476/packagemanagerlog.txt)

### Steps to reproduce the issue

Open WingetUI 
go to: "Istalled Packages"
In the "Search on your computer" : create a filter on what to uninstall
Press: "Select All packages"
Press: "Uninstall selected packages"

Then i should uninstall the packages you have selected, but also a lot of other apps (turned my computer off when i realised whatt was happening, to stop the process)

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.03134965896606445 to load all language files
🟢 checkQueue Thread started!
🔵 Language file up-to-date
🔵 Found default chocolatey installation on expected location
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "da"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\__main__.py", line 69, in <module>

🔴    File ".\__main__.py", line 69, in <module>

🔴    File ".\PackageEngine\Classes.py", line 39, in __init__

🔴    File ".\PackageEngine\Classes.py", line 39, in __init__

🔴  AttributeError: 'NoneType' object has no attribute 'NAME'

🔴  AttributeError: 'NoneType' object has no attribute 'NAME'

🔴 Note this traceback was caught by reporter and has been added to the log ('NoneType' object has no attribute 'NAME')
🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token 5160ed56fd1d3ca7ba15a1d77fb0175ddee97377e8ddeb5a0daf357a5810b99c
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Starting Winget source search...
🟢 Winget source search finished with 2 sources
🔵 Reactivation signal ignored: RaiseWindow_[1704132705.1938746]
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\wingetui.exe
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop er slået fra', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey er slået fra', 'PowerShellFound': False, 'PowerShellVersion': '', 'WingetFound': True, 'WingetVersion': 'v1.6.3482  ', '.NET ToolFound': True, '.NET ToolVersion': '8.0.100\r', 'PipFound': True, 'PipVersion': 'pip 23.3.2 from C:\\Program Files\\Python312\\Lib\\site-packages\\pip (python 3.12)   ', 'NpmFound': True, 'NpmVersion': '10.2.4 '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Pip search for installed packages
🔵 Starting Npm search for installed packages
🔵 Starting .NET Tool search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 .NET Tool search for installed packages finished with 1 result(s)
🔵 Starting Npm search for updates
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🟢 Winget source search finished with 2 sources
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🟢 About tab loaded!
🔵 Starting .NET Tool search for updates
🔵 Starting PowerShell source search...
🔵 Starting Pip search for updates
🔵 Starting Winget search for updates
🟢 Scoop source search finished with 0 sources
🟢 Chocolatey source search finished with 0 sources
🟢 Pip search for installed packages finished with 0 result(s)
🟠 Pip got too few installed packages, retrying
🔵 Starting Pip search for installed packages
🟢 Main application loaded...
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Searching for string ""
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Npm search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🟢 Pip search for installed packages finished with 89 result(s)
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🟢 Searching for string ""
🟢 Npm search for updates finished with 0 result(s)
🟢 Searching for string ""
🟡 package Update for  (KB2504637) failed parsing, going for method 2...
🟢 Winget search for installed packages finished with 325 result(s)
🟢 .NET Tool search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 PowerShell search for installed packages finished with 72 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 487
🟢 Winget search for updates finished with 8 result(s)
🟡 Package reMarkable.reMarkableCompanionApp has version * ignored
🟡 Multiple versions of Microsoft.DotNet.DesktopRuntime.6 are installed, latest version is installed. Not showing the update
🟡 Multiple versions of Microsoft.DotNet.DesktopRuntime.6 are installed, latest version is installed. Not showing the update
🟡 Package Microsoft.DotNet.SDK.6 has version * ignored
🟢 Searching for string ""
🟢 Pip search for updates finished with 7 result(s)
🟢 Searching for string ""
🔵 Starting Winget search for installed packages
🔵 Starting Pip search for installed packages
🔵 Starting Npm search for installed packages
🔵 Starting .NET Tool search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Pip search for installed packages finished with 89 result(s)
🟢 Searching for string ""
🟢 PowerShell search for updates finished with 56 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 67
🟢 Npm search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell search for installed packages finished with 72 result(s)
🟢 Searching for string ""
🟡 package Update for  (KB2504637) failed parsing, going for method 2...
🟢 Winget search for installed packages finished with 325 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 487
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
🟢 Log copied to the clipboard successfully!
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Cannot be attached, the body can only be 65536 characters
```

**Comment by marticliment** [comment]
I think I understand what you mean.

By filter, do you refer to a specific text query or selecting specific managers from the filters pane?

**Comment by marticliment** [comment]
[NOTE FOR ME]: Requires unification of getting selected packages in a new method GetPackagges and GetSelectedPackages 
 on the SoftwareSection class. This method should return list[PackageItem] representing the package items that have been set to be shown (SoftwareSection.visibleItems?)

Requires implementation of this method on all procedures that require getting all or a selection of packages, to match the filters given.

**Comment by GKilsgaard** [comment]
> I think I understand what you mean.
> 
> By filter, do you refer to a specific text query or selecting specific managers from the filters pane?

I did like this screenshot, is that what you meen:
![image](https://github.com/marticliment/WingetUI/assets/84013871/9d91d032-cdad-4e60-9305-400449cd0d78)

**Comment by marticliment** [comment]
Yes, I see where the issue is.

I have been checking the behaviour and indeed it is not consistent across the interface. I will fix that.

**Comment by priceaj** [comment]
This just got me as well, wanted to uninstall all pip packages, so filtered by pip only in sources, clicked select all, expecting it to only select visible packages, then clicked uninstall.

Obviously it started uninstalling everything

**Comment by GKilsgaard** [comment]
> This just got me as well, wanted to uninstall all pip packages, so filtered by pip only in sources, clicked select all, expecting it to only select visible packages, then clicked uninstall.
> 
> Obviously it started uninstalling everything

Got note yesterday, that it should be fixed in the next release, so when 1724 is released, it should be fixed :-)
https://github.com/marticliment/WingetUI/pull/1724

**Comment by marticliment** [comment]
Yes.

In fact, the latest prerelease version already has this issue fixed
