### ISSUE TITLE
[BUG] Now requires running wingetUI as administrator

### ISSUE THREAD

**Issue by NobbyBarnes** [marticliment/WingetUI#1692]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

If a User (account not in the administrators group) runs WingetUI no repositories are available.
Installed apps are not listed, nor are any updates listed.
If you RunAS 'Administrator' all looks good.

This is a change of operation since sometime in December 2023
Windows 10 22H2

### Steps to reproduce the issue

Install latest WinGetUI
Logon as User (no admin rights)
load WinGetUI
unable to search for apps EG: Chrome, No updates showing, installed apps not listed

### WingetUI Log

```text
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
🔵 It took 0.008999347686767578 to load all language files
🟢 checkQueue Thread started!
🟢 Updating outdated language file...
🟢 Using cached lang file
🟡 Chocolatey was not found on the default location, perhaps a portable WingetUI installation?
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token 9159676c0da65d5c20db2ef82d75ab81ca10e38223a3b574891dce0a4440afac
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Starting Winget source search...
🟢 Winget source search finished with 0 sources
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\wingetui.exe
🔵 Reactivation signal ignored: RaiseWindow_[1704726666.638889]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool is disabled', 'ChocolateyFound': False, 'ChocolateyVersion': '', 'PowerShellFound': False, 'PowerShellVersion': '', 'WingetFound': True, 'WingetVersion': ''}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Winget search for installed packages finished with 0 result(s)
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🟢 Winget source search finished with 0 sources
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🟢 Chocolatey source search finished with 0 sources
🟢 About tab loaded!
Win32Mica Error: win32 version 19045 is not supported
🟢 Scoop source search finished with 0 sources
Win32Mica Error: win32 version 19045 is not supported
🟢 Main application loaded...
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Starting Chocolatey search for updates
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting Winget search for updates
🔵 Starting PowerShell source search...
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Found reactivation lock file...
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Chocolatey source search finished with 0 sources
🟢 Winget source search finished with 0 sources
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟠 Unable to retrieve announcement image
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DavidBarnes\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DavidBarnes\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\DavidBarnes\\AppData/Local/WingetUI/CachedIcons\\announcement.png')
🟢 Scoop source search finished with 1 sources
🟢 PowerShell source search finished with 1 sources
🟢 Found reactivation lock file...
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🟢 Chocolatey source search finished with 0 sources
🟢 Winget source search finished with 0 sources
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟠 Unable to retrieve announcement image
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DavidBarnes\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DavidBarnes\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\DavidBarnes\\AppData/Local/WingetUI/CachedIcons\\announcement.png')
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟠 Unable to retrieve announcement image
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DavidBarnes\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DavidBarnes\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\DavidBarnes\\AppData/Local/WingetUI/CachedIcons\\announcement.png')
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Scoop source search finished with 1 sources
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 PowerShell source search finished with 1 sources
🔵 Starting Winget source search...
🟢 Winget source search finished with 0 sources
🔵 Starting Winget source search...
🟢 Winget source search finished with 0 sources
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Waiting for install permission... title=C:\Program, id=C:\Program, installId=1704727392.0326
🔵 Given package: <Package: C:\Program;C:\Program;;Winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x00000174ACD6F1D0>;<wingetui.Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x00000174ADDB5BC0>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
Win32Mica Error: win32 version 19045 is not supported
🔵 Found icon:  
🟡 Icon url empty
🟡 Icon  not found in json (KeyError)
🟡 Icon for C:\Program does not exist
🔵 Current program set to 1704727392.0326
🟢 Have permission to install, starting installation threads...
🔵 Starting source C:\Program installation with Command ['C:\\Program Files\\WingetUI\\wingetui\\components\\gsudo.exe', 'C:\\Program Files\\WingetUI\\wingetui\\PackageEngine/Managers\\winget-cli_x64\\winget.exe', 'source', 'add', '--name', 'C:\\Program', '--arg', 'Files\\WingetUI\\wingetui\\PackageEngine\\Managers\\winget-cli_x64\\winget.exe', '--accept-source-agreements', '--disable-interactivity']
.\PackageEngine\Managers\winget.py:809: RuntimeWarning: libshiboken: Overflow: Value 2147942403 exceeds limits of type  [signed] "int" (4bytes).
OverflowError
['Adding source:', 'C:\\Program -> Files\\WingetUI\\wingetui\\PackageEngine\\Managers\\winget-cli_x64\\winget.exe', 'An unexpected error occurred while executing the command:', '0x80070003 : unknown error', '']
Win32Mica Error: win32 version 19045 is not supported
🔵 Starting Winget source search...
🟢 Winget source search finished with 0 sources
🟢 Waiting for install permission... title="C:\Program, id="C:\Program, installId=1704727448.494437
🔵 Given package: <Package: "C:\Program;"C:\Program;;Winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x00000174ACD6F1D0>;<wingetui.Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x00000174ADD972C0>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🔵 Found icon:  
🟡 Icon url empty
🟡 Icon  not found in json (KeyError)
🟡 Icon for "C:\Program does not exist
Win32Mica Error: win32 version 19045 is not supported
🔵 Current program set to 1704727448.494437
🟢 Have permission to install, starting installation threads...
🔵 Starting source "C:\Program installation with Command ['C:\\Program Files\\WingetUI\\wingetui\\components\\gsudo.exe', 'C:\\Program Files\\WingetUI\\wingetui\\PackageEngine/Managers\\winget-cli_x64\\winget.exe', 'source', 'add', '--name', '"C:\\Program', '--arg', 'Files\\WingetUI\\wingetui\\PackageEngine\\Managers\\winget-cli_x64\\winget.exe"', '--accept-source-agreements', '--disable-interactivity']
OverflowError
['Adding source:', '"C:\\Program -> Files\\WingetUI\\wingetui\\PackageEngine\\Managers\\winget-cli_x64\\winget.exe"', 'An unexpected error occurred while executing the command:', '0x80070003 : unknown error', '']
Win32Mica Error: win32 version 19045 is not supported
🔵 Starting Winget source search...
🟢 Winget source search finished with 0 sources
🔵 Sending cancel signal...
🔵 Sending cancel signal...
🟢 Found reactivation lock file...
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 Chocolatey source search finished with 0 sources
🟢 Winget source search finished with 0 sources
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Scoop source search finished with 1 sources
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 PowerShell source search finished with 1 sources
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 797, in InstallSource
IndexError: list index out of range
🟢 Waiting for install permission... title=winget, id=winget, installId=1704727674.4208782
🔵 Given package: <Package: winget;winget;;Winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x00000174ACD6F1D0>;<wingetui.Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x00000174ADDB0CC0>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🔵 Found icon:  
🟡 Icon url empty
🟡 Icon  not found in json (KeyError)
Win32Mica Error: win32 version 19045 is not supported
🟡 Icon for winget does not exist
🔵 Current program set to 1704727674.4208782
🟢 Have permission to install, starting installation threads...
🔵 Starting source winget installation with Command ['C:\\Program Files\\WingetUI\\wingetui\\components\\gsudo.exe', 'C:\\Program Files\\WingetUI\\wingetui\\PackageEngine/Managers\\winget-cli_x64\\winget.exe', 'source', 'add', '--name', 'winget', '--arg', 'https://cdn.winget.microsoft.com/cache', '--accept-source-agreements', '--disable-interactivity']
.\PackageEngine\Managers\winget.py:809: RuntimeWarning: libshiboken: Overflow: Value 2316632076 exceeds limits of type  [signed] "int" (4bytes).
OverflowError
['A source with the given name already exists and refers to the same location:', 'winget -> https://cdn.winget.microsoft.com/cache', '']
Win32Mica Error: win32 version 19045 is not supported
🔵 Starting Winget source search...
🟢 Winget source search finished with 0 sources
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Found reactivation lock file...
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🟢 Chocolatey source search finished with 0 sources
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget source search finished with 0 sources
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Scoop source search finished with 1 sources
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 PowerShell source search finished with 1 sources
🔵 Loading WingetUI log...
🔵 Loading WingetUI log...
🔵 Loading WingetUI log...
🔵 Loading WingetUI log...
🔵 Loading WingetUI log...
🔵 Sending cancel signal...
🟢 Searching for string "c"
🟢 Searching for string "ch"
🔵 Loading dynamic packages for query ch
🔵 Searching packages on chocolatey for query ch
🔵 Starting Winget search for dynamic packages
🔵 Starting PowerShell query search
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string "chr"
🟢 Searching for string "chro"
🟢 Searching for string "chrom"
🟢 Searching for string "chrome"
🔵 Loading dynamic packages for query chrome
🔵 Searching packages on chocolatey for query chrome
🔵 Starting Winget search for dynamic packages
🔵 Starting PowerShell query search
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string "chrome"
🟢 Searching for string "chrome"
🔵 Loading operation log...
🔵 Loading WingetUI log...
🟢 Searching for string ""
🟢 Searching for string ""
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------Chocolatey
The system cannot find the path specified.

---------Winget---------Chocolatey
The system cannot find the path specified.---------Winget------------------Chocolatey
The system cannot find the path specified.---------Winget---------
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\DavidBarnes> 
PS C:\Users\DavidBarnes>         function Test-GalleryModuleUpdate
>>         {
>>             param
>>             (
>>                 [Parameter(Mandatory,ValueFromPipelineByPropertyName)]
>>                 [string]
>>                 $Name,
>> 
>>                 [Parameter(Mandatory,ValueFromPipelineByPropertyName)]
>>                 [version]
>>                 $Version,
>> 
>>                 [Parameter(Mandatory,ValueFromPipelineByPropertyName)]
>>                 [string]
>>                 $Repository,
>> 
>>                 [switch]
>>                 $NeedUpdateOnly
>>             )
>> 
>>             process
>>             {
>> 
>> 
>>                 $URLs = @{"PSGallery" = "https://www.powershellgallery.com/api/v2";}
>> 
>>                 $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$Name") -UseBasicParsing -Maximum 0 -ea Ignore
>>                 [version]$latest = Split-Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupkg") -Leaf
>>                 $needsupdate = $Latest -gt $Version
>> 
>>                 if ($needsupdate)
>>                 {
>>                     Write-Output ($Name + "|" + $Version.ToString() + "|" + $Latest.ToString() + "|" + $Repository)
>>                 }
>>             }
>>         }
>> 
PS C:\Users\DavidBarnes>         Get-InstalledModule | Test-GalleryModuleUpdate
PS C:\Users\DavidBarnes>         exit---------Chocolatey
The system cannot find the path specified.---------Winget

---------Chocolatey
The system cannot find the path specified.---------Winget---------

---------Chocolatey
The system cannot find the path specified.
---------Winget

---------Chocolatey
The system cannot find the path specified.---------Winget------------------Chocolatey
The system cannot find the path specified.

---------Winget
---------Chocolatey
The system cannot find the path specified.
---------Winget
---------
---------Chocolatey
The system cannot find the path specified.

---------Winget
---------Chocolatey
The system cannot find the path specified.---------Winget
---------------- Winget query ch

------- Winget query chrome

---------Chocolatey
The system cannot find the path specified.

---------Winget
---------Chocolatey
The system cannot find the path specified.
---------Winget
---------
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/132630057/903a1ba3-3cd6-4184-a68e-e2014e62629b)

As 'User':
![image](https://github.com/marticliment/WingetUI/assets/132630057/dec662e4-ce60-4614-9c4b-da644bc08035)

As 'Administrator'
![image](https://github.com/marticliment/WingetUI/assets/132630057/7e0f0315-4a72-44d6-8136-baf41bdf073b)

![image](https://github.com/marticliment/WingetUI/assets/132630057/c42a9861-d458-4c8d-983b-103b5798e726)

**Comment by marticliment** [comment]
This is an issue with WingetUI 2.2.0.

Please disable automatic WingetUI updates from the settings and imstall WingetUI 2.1.1

**Comment by thomas315** [comment]
Same issue for me but I can see Chocolatey packages at least. Uninstalling WingetUI 2.2.0 and using WingetUI 2.1.1 doesn't fix the issue for me.

**Comment by gilromano** [comment]
I have the same issue, and downgrading to WingetUI 2.1.1 doesn't solve it for me either.  Forcing the use of the system winget via the "experimental" wingetui settings DOES resolve the problem for me.

**Comment by marticliment** [comment]
Hello,

Please try deleting the C:\Users\%USERNAME%\AppData\Local\Microsoft\WinGet\Settings\defaultState\sources_metadata file

**Comment by gilromano** [comment]
In file explorer, as I traversed down the path, it asked for UAC elevation in order to view the “defaultState” directory (elevation not required prior to that).  The defaultState directory was completely empty, so no “sources_metadata” file to delete.
 
____________________
Gil Romano
 ***@***.***> ***@***.***

**Comment by marticliment** [comment]
Then try to remove the defaultState folder and any other folder that requires UAC

**Comment by gilromano** [comment]
That worked!
 
1.	Deleted the empty and UAC protected directory C:\Users\Gil\AppData\Local\Microsoft\WinGet\Settings\defaultState
2.	Started WingetUI and turned off the setting to use the system winget
3.	Restarted WingetUI, which recreated the defaultState directory and the contained sources_metadata file.  The defaultState directory no longer requires UAC to view
4.	Installed apps now show up
 
 
____________________
Gil Romano
 ***@***.***> ***@***.***

**Comment by marticliment** [comment]
Perfect!

**Comment by marticliment** [comment]
I will try to add an automated script that performs those actions

**Comment by gilromano** [comment]
After deleting defaultState and disabling system winget, the winget sources work again.  
 
I now tried enabling chocolatey again (which did work previously when system winget was enabled), and I’m now getting no sources and the error “The system cannot find the path specified”.
 
I noticed that the operation log and the top of the Chocolatey Preferences panel show an incorrect path:
Incorrect Path:  C:\Program Files\WingetUI\wingetui\choco-cli\choco.exe
Correct Path (after clean install of v2.2.0):  C:\Program Files\WingetUI\choco-cli\choco.exe
 
--------------------------------
Operation: installation - Perform date 2024-01-19 10:10:48.591580
Package: <Package: chocolatey;chocolatey;;Chocolatey;<wingetui.PackageEngine.Managers.choco.ChocoPackageManager object at 0x0000028D5667DB50>;<wingetui.Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x0000028D71774040>>
Command-line call: "C:\Program Files\WingetUI\wingetui\choco-cli\choco.exe source add --name chocolatey --source https://community.chocolatey.org/api/v2/ -y" Output code: 1
Console output:
   | The system cannot find the path specified.
--------------------------------
 
I’m running v2.2.0
 
____________________
Gil Romano
 ***@***.***> ***@***.***

**Comment by captainfalcon23** [comment]
Tried the advice to delete the defaulttate folder, but still have the same issue. Also tried upgrading to latest 2.2.0 and still cannot load any packages :(

**Comment by captainfalcon23** [comment]
Tried also uninstalling and reinstalling, and same issue.

**Comment by marticliment** [comment]
@captainfalcon23, does system winget work for you?

**Comment by marticliment** [comment]
@gilromano, can you try enabling system chocolatey?

**Comment by captainfalcon23** [comment]
@marticliment It seems to work with system winget on ver 2.1.0. Should I upgrade to latest and see? Should we even be using system winget?

**Comment by marticliment** [comment]
Maybe you can give version 2.2.0 a try

> Should we even be using system winget?

You should not, but if bundled winget does not is always an alternative

**Comment by llvs** [comment]
Sounds like the temporary files issue [here].(https://github.com/marticliment/WingetUI/issues/1721)
Please check if it also applies to you.

**Comment by captainfalcon23** [comment]
Yep, cleaning up the temp dir worked for me
