### ISSUE TITLE
[BUG] WingetUI doesn't show any installed Packages anymore!

### ISSUE THREAD

**Issue by saimench** [marticliment/WingetUI#1720]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Suddenly, WingetUI doesn't show any installed Packages anymore. The Winget Command in Powershell `winget list` shows all my installed Packages correctly.

### Steps to reproduce the issue

Open or search on the "installed Packages" tab:
![2024-01-19 12_21_41-WingetUI](https://github.com/marticliment/WingetUI/assets/5787497/73f79f9f-e050-48eb-a4c2-d4c262253498)

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.06700253486633301 to load all language files
🟢 checkQueue Thread started!
🔵 Found default chocolatey installation on expected location
🔵 Language file up-to-date
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "de"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Starting API with random session authentication token 0f0685ca8a3b472909f0d4f25f0e501cb8c444ef545122707d0642b17eaab502
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Reactivation signal ignored: RaiseWindow_[1705614976.4266784]
🔵 Starting Winget source search...
🟢 Winget source search finished with 0 sources
🟢 Found valid aumid {6D80...
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop ist deaktiviert', 'PipFound': False, 'PipVersion': 'Pip ist deaktiviert', 'NpmFound': False, 'NpmVersion': 'Npm ist deaktiviert', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool ist deaktiviert', 'PowerShellFound': False, 'PowerShellVersion': '', 'WingetFound': True, 'WingetVersion': 'v1.6.3482  ', 'ChocolateyFound': True, 'ChocolateyVersion': '2.2.2  '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🔵 Reloading Scoop sources...
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🟢 PowerShell search for installed packages finished with 0 result(s)
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Winget source search finished with 0 sources
Win32Mica Error: win32 version 19045 is not supported
🔵 Starting PowerShell source search...
🟢 Scoop source search finished with 0 sources
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
Win32Mica Error: win32 version 19045 is not supported
🟢 Main application loaded...
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey source search finished with 1 sources
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 114: invalid start byte

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 114: invalid start byte

🔴 Note this traceback was caught by reporter and has been added to the log ('utf-8' codec can't decode byte 0x81 in position 114: invalid start byte)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting Chocolatey search for updates
🔵 Starting Winget search for updates
🔵 Starting PowerShell source search...
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 114: invalid start byte

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 114: invalid start byte

🔴 Note this traceback was caught by reporter and has been added to the log ('utf-8' codec can't decode byte 0x81 in position 114: invalid start byte)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting Chocolatey search for updates
🔵 Starting PowerShell source search...
🔵 Starting Winget search for updates
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 114: invalid start byte

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 114: invalid start byte

🔴 Note this traceback was caught by reporter and has been added to the log ('utf-8' codec can't decode byte 0x81 in position 114: invalid start byte)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Found reactivation lock file...
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
🟠 Unable to retrieve announcement image
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴    File ".\Interface\CustomWidgets\SpecificWidgets.py", line 403, in loadAnnouncements

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\simon\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\simon\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\simon\\AppData/Local/WingetUI/CachedIcons\\announcement.png')
https://www.marticliment.com/wingetui/help?isWingetUIIframe
https://www.marticliment.com/wingetui/help?isWingetUIIframe
https://www.marticliment.com/wingetui/help?isWingetUIIframe
🟢 Found reactivation lock file...
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------Chocolatey
Chocolatey v2.2.2

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.

---------
---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt---------Chocolatey
Chocolatey v2.2.2
0 packages installed.
---------Chocolatey
Chocolatey v2.2.2
Outdated Packages
Output is package name | current version | available version | pinned?Chocolatey has determined 0 package(s) are outdated.

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt---------Chocolatey
Chocolatey v2.2.2
Outdated Packages
Output is package name | current version | available version | pinned?Chocolatey has determined 0 package(s) are outdated.
---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt---------Chocolatey
Chocolatey v2.2.2
Outdated Packages
Output is package name | current version | available version | pinned?Chocolatey has determined 0 package(s) are outdated.
---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt---------Chocolatey
Chocolatey v2.2.2
0 packages installed.------------------Chocolatey
Chocolatey v2.2.2
0 packages installed.---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt

---------Chocolatey
Chocolatey v2.2.2
0 packages installed.---------
---------Chocolatey
Chocolatey v2.2.2
0 packages installed.
---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt
---------Chocolatey
Chocolatey v2.2.2
0 packages installed.------------------Chocolatey
Chocolatey v2.2.2
0 packages installed.
```

**Comment by Korben85** [comment]
Hi I have the same issue and can see that in the Winget/Chocolatey settings there are no sources anymore.
Currently I cannot try to reset this but wanted to share my finding in case it helps.

**Comment by Korben85** [comment]
Tried deleting the file but it didn't resolve the issue.

**Comment by saimench** [comment]
Hello Martí,

 

thank you very much. Your advice fixed the issue !

 

Best Regards

Simon

 

Von: Martí Climent ***@***.*** 
Gesendet: Freitag, 19. Januar 2024 17:24
An: marticliment/WingetUI ***@***.***>
Cc: Simon Anderegg ***@***.***>; Author ***@***.***>
Betreff: Re: [marticliment/WingetUI] [BUG] WingetUI doesn't show any installed Packages anymore! (Issue #1720)

 

Hello,

Please try deleting this file: C:\Users%USERNAME%\AppData\Local\Microsoft\WinGet\Settings\defaultState\sources_metadata

**Comment by saimench** [comment]
Addendum: The correct path to delete is (without quotes): "C:\Users\%USERNAME%\AppData\Local\Microsoft\WinGet\Settings\defaultState\sources_metadata"

**Comment by Korben85** [comment]
Hi,
I'm sorry for reopening this, but the provided solution doesn't work for me.
Here some information about my system.
I have an account without admin privileges and it is my primary account.
Then I have another account for administrative operations.
The app was working fine and suddenly doesn't show any installed packages.
I tried:
1. reinstalling the app
2. deleting the "%USERPROFILE%\AppData\Local\Microsoft\WinGet\Settings\defaultState\sources_metadata" file
3. resetting the winget settings in WingetUI -> just getting an error "The system cannot find the path specified.
'.\winget.exe' is not recognized as an internal or external command"
4. When I copy the path from the packet manager settings I see winget.exe there.

What else can I try to solve the issue?

addition: When I start WingetUI as admin it does find the packages.

**Comment by marticliment** [comment]
on step 2, have you deleted the file for every user on your machine?

**Comment by Korben85** [comment]
Yes, I deleted it for every user.
I now had a look in (here)[https://github.com/marticliment/WingetUI/issues/1721#issuecomment-1904367578] and tried this as well.
I also uninstalled wingetui and deleted every winget folder I could find in every user profile.
Restarted the machine, installed wingetui and it is now working again.
