### ISSUE TITLE
[CRASH] (Enter your description here)

### ISSUE THREAD

**Issue by lupus-wolf** [marticliment/WingetUI#1788]
Hard crash experienced

Error details : 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.22631.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0-alpha0
                Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: Collection was modified; enumeration operation may not execute.

Crash Traceback: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at ModernWindow.Interface.SoftwareUpdatesPage.<GenerateToolBar>b__27_4(Object s, RoutedEventArgs e) in C:\SomePrograms\WingetUI-Store\src\wingetui-interface\Interface\Pages\SoftwareUpdates.xaml.cs:line 606
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by lupus-wolf** [comment]
Die Anwendung wurde nach dem sie beendet wurde immer neu gestartet

**Comment by marticliment** [comment]
Next beta will have this issue fixed
