### ISSUE TITLE
[BUG] JDownloader cant be uninstalled

### ISSUE THREAD

**Issue by Keith94** [marticliment/WingetUI#1807]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Found JDownloader 2 [AppWork.JDownloader]
Starting package uninstall...
Uninstall failed with exit code: 1

### Steps to reproduce the issue

Install JDownloader 2
Uninstall it

### WingetUI Log

```text
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
🔵 It took 0.024576425552368164 to load all language files
🟢 checkQueue Thread started!
🔵 Found default chocolatey installation on expected location
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🟢 Updating outdated language file...
🟢 Using cached lang file
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Starting API with random session authentication token e55660869964e8d9152e3d7020f87612da46b549c937acb5e7f85042257e326e
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🔴 Could not load latest metadata from remote file https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File "urllib\request.py", line 1348, in do_open

🔴    File "urllib\request.py", line 1348, in do_open

🔴    File "http\client.py", line 1283, in request

🔴    File "http\client.py", line 1283, in request

🔴    File "http\client.py", line 1329, in _send_request

🔴    File "http\client.py", line 1329, in _send_request

🔴    File "http\client.py", line 1278, in endheaders

🔴    File "http\client.py", line 1278, in endheaders

🔴    File "http\client.py", line 1038, in _send_output

🔴    File "http\client.py", line 1038, in _send_output

🔴    File "http\client.py", line 976, in send

🔴    File "http\client.py", line 976, in send

🔴    File "http\client.py", line 1455, in connect

🔴    File "http\client.py", line 1455, in connect

🔴    File "ssl.py", line 517, in wrap_socket

🔴    File "ssl.py", line 517, in wrap_socket

🔴    File "ssl.py", line 1075, in _create

🔴    File "ssl.py", line 1075, in _create

🔴    File "ssl.py", line 1346, in do_handshake

🔴    File "ssl.py", line 1346, in do_handshake

🔴  ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴  ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴  
During handling of the above exception, another exception occurred:


🔴  
During handling of the above exception, another exception occurred:


🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\Application.py", line 298, in downloadPackagesMetadata

🔴    File ".\Interface\Application.py", line 298, in downloadPackagesMetadata

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 519, in open

🔴    File "urllib\request.py", line 519, in open

🔴    File "urllib\request.py", line 536, in _open

🔴    File "urllib\request.py", line 536, in _open

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 1391, in https_open

🔴    File "urllib\request.py", line 1391, in https_open

🔴    File "urllib\request.py", line 1351, in do_open

🔴    File "urllib\request.py", line 1351, in do_open

🔴  urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

🔴  urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>)
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\Application.py", line 309, in downloadPackagesMetadata

🔴    File ".\Interface\Application.py", line 309, in downloadPackagesMetadata

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\domin\\AppData/Local/WingetUI/CachedData\\Icon Database.json'

🔴  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\domin\\AppData/Local/WingetUI/CachedData\\Icon Database.json'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\domin\\AppData/Local/WingetUI/CachedData\\Icon Database.json')
🔵 Starting Winget source search...
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Winget source search finished with 2 sources
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\Application.py", line 222, in getAUMID

🔴    File ".\Interface\Application.py", line 222, in getAUMID

🔴  IndexError: list index out of range

🔴  IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Adding chocolatey to path...
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool is disabled', 'PowerShellFound': False, 'PowerShellVersion': '', 'WingetFound': True, 'WingetVersion': 'v1.6.3482  ', 'ChocolateyFound': True, 'ChocolateyVersion': '2.2.2  '}
🔵 Reached main ui load milestone
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\MainWindow.py", line 47, in __init__

🔴    File ".\Interface\MainWindow.py", line 47, in __init__

🔴  AssertionError: Invalid window geometry format

🔴  AssertionError: Invalid window geometry format

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid window geometry format)
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🟢 Winget source search finished with 2 sources
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🔵 Reloading Scoop sources...
🟢 About tab loaded!
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 Main application loaded...
🟢 Chocolatey source search finished with 1 sources
🟢 Winget search for installed packages finished with 58 result(s)
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
🟢 Scoop source search finished with 5 sources
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 58
🟢 PowerShell source search finished with 1 sources
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
🔵 Starting PowerShell source search...
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 1 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 1
🟢 Waiting for install permission... title=JDownloader 2, id=AppWork.JDownloader, installId=1708414978.727434
🔵 Given package: <Package: JDownloader 2;AppWork.JDownloader;2.0;Winget: winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x00000229F5B1BB50>;<wingetui.Interface.CustomWidgets.SpecificWidgets.InstalledPackageItem object at 0x00000229F5D0EE40>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🔵 Current program set to 1708414978.727434
🔵 Found icon:  
🟡 Icon url empty
🟡 Icon jdownloader not found in json (KeyError)
🟡 Icon for AppWork.JDownloader does not exist
🟢 Have permission to install, starting installation threads...
🔵 Starting <Package: JDownloader 2;AppWork.JDownloader;2.0;Winget: winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x00000229F5B1BB50>;<wingetui.Interface.CustomWidgets.SpecificWidgets.InstalledPackageItem object at 0x00000229F5D0EE40>> uninstall with Command ['C:\\Users\\domin\\AppData\\Local\\Programs\\WingetUI\\wingetui\\PackageEngine/Managers\\winget-cli_x64\\winget.exe', 'uninstall', '--id', 'AppWork.JDownloader', '--exact', '--accept-source-agreements', '--disable-interactivity']
.\PackageEngine\Managers\winget.py:725: RuntimeWarning: libshiboken: Overflow: Value 2316632112 exceeds limits of type  [signed] "int" (4bytes).
OverflowError
['Found JDownloader 2 [AppWork.JDownloader]', 'Starting package uninstall...', 'Uninstall failed with exit code: 1', '']
🔵 Starting <Package: JDownloader 2;AppWork.JDownloader;2.0;Winget: winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x00000229F5B1BB50>;<wingetui.Interface.CustomWidgets.SpecificWidgets.InstalledPackageItem object at 0x00000229F5D0EE40>> uninstall with Command ['C:\\Users\\domin\\AppData\\Local\\Programs\\WingetUI\\wingetui\\PackageEngine/Managers\\winget-cli_x64\\winget.exe', 'uninstall', '--id', 'AppWork.JDownloader', '--exact', '--accept-source-agreements', '--disable-interactivity']
OverflowError
['Found JDownloader 2 [AppWork.JDownloader]', 'Starting package uninstall...', 'Uninstall failed with exit code: 1', '']
🔵 Loading WingetUI log...
🔵 Saving log...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------Chocolatey
Chocolatey v2.2.2
0 packages installed.

---------Winget
- 
   \ 
   | 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.22 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.22 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.22 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.22 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.22 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.22 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.22 MB
  ██████████████████████████▒▒▒▒  8.00 MB / 9.22 MB
  █████████████████████████████▒  9.00 MB / 9.22 MB
  ██████████████████████████████  9.22 MB / 9.22 MB
                                                                                                                        

   - 
   \ 
                                                                                                                        
Name                                    Id                                       Version            Available    Source
-----------------------------------------------------------------------------------------------------------------------
7-Zip 23.01 (x64)                       7zip.7zip                                23.01                           winget
Intel® Graphics Command Center          AppUp.IntelGraphicsExperience_8j3eq9eme… 1.100.5336.0
Lies of P                               Lies of P_is1                            Unknown
Microsoft Edge                          Microsoft.Edge                           121.0.2277.128                  winget
Microsoft Edge Update                   Microsoft Edge Update                    1.3.185.17
Microsoft Edge WebView2 Runtime         Microsoft.EdgeWebView2Runtime            121.0.2277.128                  winget
App Installer                           Microsoft.AppInstaller                   1.21.3482.0                     winget
Get Help                                Microsoft.GetHelp_8wekyb3d8bbwe          10.2308.12552.0
Microsoft Tips                          Microsoft.Getstarted_8wekyb3d8bbwe       10.2309.0.0
HEIF Image Extensions                   Microsoft.HEIFImageExtension_8wekyb3d8b… 1.0.63001.0
English (United Kingdom) Local Experie… Microsoft.LanguageExperiencePacken-GB_8… 22621.37.194.0
Microsoft Edge                          Microsoft.MicrosoftEdge.Stable_8wekyb3d… 121.0.2277.128
Microsoft .Net Native Framework Packag… Microsoft.NET.Native.Framework.2.2_8wek… 2.2.29512.0
Microsoft .Net Native Runtime Package … Microsoft.NET.Native.Runtime.2.2_8wekyb… 2.2.28604.0
OneDrive                                Microsoft.OneDriveSync_8wekyb3d8bbwe     24020.128.3.0
Raw Image Extension                     Microsoft.RawImageExtension_8wekyb3d8bb… 2.1.63181.0
Windows Security                        Microsoft.SecHealthUI_8wekyb3d8bbwe      1000.25873.9001.0
Microsoft Engagement Framework          Microsoft.Services.Store.Engagement_8we… 10.0.23012.0
Store Experience Host                   Microsoft.StorePurchaseApp_8wekyb3d8bbwe 22310.1401.1.0
Microsoft.UI.Xaml.2.7                   Microsoft.UI.Xaml.2.7                    7.2208.15002.0                  winget
Microsoft.UI.Xaml.2.8                   Microsoft.UI.Xaml.2.8                    8.2310.30001.0                  winget
Microsoft Visual C++ 2015 UWP Desktop … Microsoft.VCLibs.Desktop.14              14.0.33519.0                    winget
Microsoft Visual C++ 2015 UWP Runtime … Microsoft.VCLibs.140.00_8wekyb3d8bbwe    14.0.33519.0
VP9 Video Extensions                    Microsoft.VP9VideoExtensions_8wekyb3d8b… 1.0.62911.0
Webp Image Extensions                   Microsoft.WebpImageExtension_8wekyb3d8b… 1.0.62681.0
Dev Home (Preview)                      Microsoft.DevHome                        0.1001.389.0                    winget
Microsoft Photos                        Microsoft.Windows.Photos_8wekyb3d8bbwe   2024.11010.23003.0
Microsoft.WindowsAppRuntime.1.2         Microsoft.WindowsAppRuntime.1.2_8wekyb3… 2000.802.31.0
WindowsAppRuntime.1.4                   Microsoft.WindowsAppRuntime.1.4_8wekyb3… 4000.1136.2333.0
Windows Camera                          Microsoft.WindowsCamera_8wekyb3d8bbwe    2023.2311.8.0
Microsoft Store                         Microsoft.WindowsStore_8wekyb3d8bbwe     22401.1401.2.0
Xbox Game Bar Plugin                    Microsoft.XboxGameOverlay_8wekyb3d8bbwe  1.54.4001.0
Game Bar                                Microsoft.XboxGamingOverlay_8wekyb3d8bb… 6.123.11012.0
Xbox Identity Provider                  Microsoft.XboxIdentityProvider_8wekyb3d… 12.95.3001.0
Xbox Game Speech Window                 Microsoft.XboxSpeechToTextOverlay_8weky… 1.21.13002.0
Phone Link                              Microsoft.YourPhone_8wekyb3d8bbwe        1.23102.126.0
Windows Web Experience Pack             MicrosoftWindows.Client.WebExperience_c… 424.1301.40.0
NVIDIA Control Panel                    NVIDIACorp.NVIDIAControlPanel_56jybvy8s… 8.1.964.0
Realtek Audio Control                   RealtekSemiconductorCorp.RealtekAudioCo… 1.50.319.0
Killer Intelligence Center              RivetNetworks.KillerControlCenter_rh07t… 3.1523.831.0
Steam                                   Valve.Steam                              2.10.91.91                      winget
Wallpaper Engine                        Steam App 431960                         Unknown
SteelSeries GG 56.0.0                   SteelSeries.GG                           56.0.0                          winget
Sublime Text                            SublimeHQ.SublimeText.4                  Unknown            4.0.0.416900 winget
JDownloader 2                           AppWork.JDownloader                      2.0                             winget
qBittorrent                             qBittorrent.qBittorrent                  4.6.3                           winget
Intel(R) Chipset Device Software        {128196ab-db0f-4c9e-b603-9c8d8b59934d}   10.1.18950.8297
Microsoft Visual C++ 2015-2022 Redistr… Microsoft.VCRedist.2015+.x86             14.38.33130.0                   winget
Realtek Card Reader                     {5BC2B5AB-80DE-4E83-B8CF-426902051D0A}   10.0.22000.21353
Intel(R) Serial IO                      {9FD91C5C-44AE-4D9D-85BE-AE52816B0294}   30.100.2134.22
Everything 1.4.1.1024 (x64)             voidtools.Everything                     1.4.1.1024                      winget
NVIDIA Graphics Driver 551.52           {B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_… 551.52
NVIDIA PhysX System Software 9.21.0713  Nvidia.PhysX                             9.21.0713                       winget
NVIDIA HD Audio Driver 1.3.40.14        {B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_… 1.3.40.14
Killer Performance Driver Suite UWD     {C55E0E21-AC08-4F9B-8551-BCBECF982FC5}   3.1121.1159
Microsoft Update Health Tools           {C6FD611E-7EFE-488C-A0E0-974C09EF6473}   5.72.0.0
Realtek Audio Driver                    {F132AF7F-7BCA-4EDE-8A7C-958108FE7DBC}   6.0.9297.1
Microsoft Visual C++ 2015-2022 Redistr… Microsoft.VCRedist.2015+.x64             14.38.33135.0                   winget
---------Chocolatey
Chocolatey v2.2.2
0 packages installed.---------
---------Chocolatey
Chocolatey v2.2.2
Outdated Packages
Output is package name | current version | available version | pinned?Chocolatey has determined 0 package(s) are outdated.---------Winget
- 
   \ 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.22 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.22 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.22 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.22 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.22 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.22 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.22 MB
  ██████████████████████████▒▒▒▒  8.00 MB / 9.22 MB
  █████████████████████████████▒  9.00 MB / 9.22 MB
  ██████████████████████████████  9.22 MB / 9.22 MB
                                                                                                                        

   - 
                                                                                                                        
Name         Id                      Version Available    Source
----------------------------------------------------------------
Sublime Text SublimeHQ.SublimeText.4 Unknown 4.0.0.416900 winget
1 upgrades available.
---------
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\domin> 
PS C:\Users\domin>         function Test-GalleryModuleUpdate
>>         {
>>             param
>>             (
>>                 [Parameter(Mandatory,ValueFromPipelineByPropertyName)]
>>                 [string]
>>                 $Name,
>> 
>>                 [Parameter(Mandatory,ValueFromPipelineByPropertyName)]
>>                 [version]
>>                 $Version,
>> 
>>                 [Parameter(Mandatory,ValueFromPipelineByPropertyName)]
>>                 [string]
>>                 $Repository,
>> 
>>                 [switch]
>>                 $NeedUpdateOnly
>>             )
>> 
>>             process
>>             {
>> 
>> 
>>                 $URLs = @{"PSGallery" = "https://www.powershellgallery.com/api/v2";}
>> 
>>                 $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$Name") -UseBasicParsing -Maximum 0 -ea Ignore
>>                 [version]$latest = Split-Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupkg") -Leaf
>>                 $needsupdate = $Latest -gt $Version
>> 
>>                 if ($needsupdate)
>>                 {
>>                     Write-Output ($Name + "|" + $Version.ToString() + "|" + $Latest.ToString() + "|" + $Repository)
>>                 }
>>             }
>>         }
>> 
PS C:\Users\domin>         Get-InstalledModule | Test-GalleryModuleUpdate
PS C:\Users\domin>         exit
```

### Relevant information

Exception:

java.lang.NoSuchMethodError: org.appwork.updatesys.client.UpdateClient.<init>(Lorg/appwork/updatesys/client/Setup;Lorg/appwork/updatesys/client/ImplBuilder;)V
	at org.appwork.install4j.updatesys.Webinstaller$8.<init>(Webinstaller.java:686)
	at org.appwork.install4j.updatesys.Webinstaller.uninstallByID(Webinstaller.java:686)
	at org.appwork.install4j.updatesys.Webinstaller.uninstall(Webinstaller.java:625)
	at com.install4j.runtime.installer.UninstallerContextImpl$2.fetchValue(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.actions.FetchObjectAction.execute(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionDirect(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionInt(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionChecked(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.fetchObjectChecked(Unknown Source)
	at com.install4j.runtime.installer.UninstallerContextImpl.performActionIntStatic(Unknown Source)
	at com.install4j.runtime.installer.UninstallerContextImpl.performActionInt(Unknown Source)
	at com.install4j.runtime.installer.ContextImpl.performAction(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.handleCommand(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.start(Unknown Source)
	at com.install4j.runtime.installer.Uninstaller.runInProcess(Unknown Source)
	at com.install4j.runtime.installer.Uninstaller.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)
	at com.install4j.runtime.launcher.WinLauncher.main(Unknown Source)

System properties:

java.runtime.name=Java(TM) SE Runtime Environment
exe4j.moduleName=C:\Program Files\JDownloader\Uninstall JDownloader.exe
exe4j.processCommFile=C:\Users\domin\AppData\Local\Temp\e4j_p20428.tmp
exe4j.semaphoreName=Local\c:_program_files_jdownloader_uninstall_jdownloader.exe
sun.boot.library.path=c:\program files\jdownloader\jre\bin
java.vm.version=25.31-b07
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
exe4j.consoleCodepage=cp0
path.separator=;
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg=sun.io
com.sun.jndi.rmi.object.trustURLCodebase=false
user.country=US
user.script=
sun.os.patch.level=
install4j.exeDir=C:\Program Files\JDownloader\
java.vm.specification.name=Java Virtual Machine Specification
user.dir=C:\Program Files
java.runtime.version=1.8.0_31-b13
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs=c:\program files\jdownloader\jre\lib\endorsed
os.arch=amd64
java.io.tmpdir=C:\Users\domin\AppData\Local\Temp\
line.separator=

java.vm.specification.vendor=Oracle Corporation
user.variant=
exe4j.tempDir=
os.name=Windows 8
com.sun.jndi.ldap.object.trustURLCodebase=false
sun.jnu.encoding=Cp1252
java.library.path=C:\Program Files\JDownloader\.\.install4j;C:\Users\domin\AppData\Local\Programs\WingetUI\PySide6;C:\Users\domin\AppData\Local\Programs\WingetUI;C:\Program Files (x86)\Microsoft\Edge\Application;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\domin\AppData\Local\Programs\WingetUI\choco-cli\bin;C:\Users\domin\AppData\Local\Microsoft\WindowsApps;c:\program files\jdownloader\jre\bin
sun.awt.enableExtraMouseButtons=true
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
exe4j.isInstall4j=true
os.version=6.2
java.rmi.server.useCodebaseOnly=true
user.home=C:\Users\domin
user.timezone=America/Denver
java.awt.printerjob=sun.awt.windows.WPrinterJob
file.encoding=Cp1252
java.specification.version=1.8
java.class.path=C:\Program Files\JDownloader\.install4j\i4jruntime.jar;C:\Program Files\JDownloader\.\.install4j\user.jar;C:\Program Files\JDownloader\.\.install4j\user\proxyVole.jar;;C:\Program Files\JDownloader\jre\lib\deploy.jar;C:\Program Files\JDownloader\jre\lib\plugin.jar;C:\Program Files\JDownloader\JDownloader.jar
user.name=domin
java.vm.specification.version=1.8
sun.java.command=C:\Program Files\JDownloader\Uninstall JDownloader.exe
java.home=c:\program files\jdownloader\jre
sun.arch.data.model=64
exe4j.launchName=C:\Program Files\JDownloader\Uninstall JDownloader.exe
user.language=en
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.awt.windows.WToolkit
java.vm.info=mixed mode
exe4j.unextractedPosition=0
java.version=1.8.0_31
java.ext.dirs=c:\program files\jdownloader\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
sun.boot.class.path=c:\program files\jdownloader\jre\lib\resources.jar;c:\program files\jdownloader\jre\lib\rt.jar;c:\program files\jdownloader\jre\lib\sunrsasign.jar;c:\program files\jdownloader\jre\lib\jsse.jar;c:\program files\jdownloader\jre\lib\jce.jar;c:\program files\jdownloader\jre\lib\charsets.jar;c:\program files\jdownloader\jre\lib\jfr.jar;c:\program files\jdownloader\jre\classes
install4j.appDir=C:\Program Files\JDownloader\
java.vendor=Oracle Corporation
file.separator=\
com.sun.jndi.cosnaming.object.trustURLCodebase=false
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
install4j.systemLanguage=en
sun.desktop=windows
sun.cpu.isalist=amd64

**Comment by marticliment** [comment]
I am afraid that this issue is with this package itself. The maintainer did not publish a correct pakacge on Winget-cli, and therefore this would be ultimately a winget-cli issue, and not a WingetUI
