### ISSUE TITLE
[CRASH] (Enter your description here)

### ISSUE THREAD

**Issue by BEZQu4liTy** [marticliment/WingetUI#1808]
Hard crash experienced

Error details : 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.22631.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0-alpha1
                Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: The notification platform is unavailable.

The notification platform is unavailable.


Crash Traceback: 
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.UI.Notifications.IToastNotificationHistoryMethods.Clear(IObjectReference _obj, String applicationId)
   at Windows.UI.Notifications.ToastNotificationHistory.Clear(String applicationId)
   at CommunityToolkit.WinUI.Notifications.ToastNotificationHistoryCompat.Clear()
   at ModernWindow.MainApp..ctor() in C:\SomePrograms\WingetUI-Store\src\wingetui-interface\App.xaml.cs:line 66
```

**Comment by marticliment** [comment]
Related tracebacks: 

```
OS: Win32NT
Version: Microsoft Windows NT 10.0.22631.0
OS Architecture: True
APP Architecture: True
Language: Unknown
APP Version: 3.0-alpha0
Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: La plataforma de notificación no está disponible.

La plataforma de notificación no está disponible.


Crash Traceback: 
at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
at ABI.Windows.UI.Notifications.IToastNotificationManagerStaticsMethods.CreateToastNotifier(IObjectReference _obj, String applicationId)
at Windows.UI.Notifications.ToastNotificationManager.CreateToastNotifier(String applicationId)
at CommunityToolkit.WinUI.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
at CommunityToolkit.WinUI.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
at ModernWindow.Interface.SoftwareUpdatesPage.LoadPackages() in C:\SomePrograms\WingetUI-Store\src\wingetui-interface\Interface\Pages\SoftwareUpdates.xaml.cs:line 348
at ModernWindow.Interface.SoftwareUpdatesPage.<.ctor>b__16_0(Object s, RoutedEventArgs e) in C:\SomePrograms\WingetUI-Store\src\wingetui-interface\Interface\Pages\SoftwareUpdates.xaml.cs:line 54
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0() 

```


```
OS: Win32NT
Version: Microsoft Windows NT 10.0.22631.0
OS Architecture: True
APP Architecture: True
Language: Unknown
APP Version: 3.0-alpha1
Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: La plataforma de notificación no está disponible.

La plataforma de notificación no está disponible.


Crash Traceback: 
at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
at ABI.Windows.UI.Notifications.IToastNotificationHistoryMethods.Clear(IObjectReference _obj, String applicationId)
at Windows.UI.Notifications.ToastNotificationHistory.Clear(String applicationId)
at CommunityToolkit.WinUI.Notifications.ToastNotificationHistoryCompat.Clear()
at ModernWindow.MainApp..ctor() in C:\SomePrograms\WingetUI-Store\src\wingetui-interface\App.xaml.cs:line 66 

```

**Comment by marticliment** [comment]
Fixed!

**Comment by marticliment** [comment]
Fixed

**Comment by BEZQu4liTy** [comment]
Thank you. :)
