### ISSUE TITLE
[BUG] Bundled WinGet in 2.2.0 path is in correct and contains backslashes

### ISSUE THREAD

**Issue by stevef-5gn-com-au** [marticliment/WingetUI#1810]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

In 2.2.0, the bundled WinGet path contains backslashes which completely breaks WinGetUI - no packages can be found/installed/updated. Reverting to using system WinGet works fine.

E.g using bundled winget:
<img width="713" alt="image" src="https://github.com/marticliment/WingetUI/assets/159501847/2a149a07-c665-443c-8de5-7a985026f2c1">

![image](https://github.com/marticliment/WingetUI/assets/159501847/02f00300-5c6a-401a-98c2-376fe87b5375)

Eg using system winget:
<img width="1357" alt="image" src="https://github.com/marticliment/WingetUI/assets/159501847/bfe6c17b-9cc1-435c-9955-35cc517026b1">

<img width="799" alt="image" src="https://github.com/marticliment/WingetUI/assets/159501847/8e247170-ae63-42dc-8cf6-79ffce039a5a">

About:
<img width="1160" alt="image" src="https://github.com/marticliment/WingetUI/assets/159501847/7a3ff17d-4810-454b-abcf-06d130b05fe4">

### Steps to reproduce the issue

Not sure... this randomly broke the other day.... perhaps it updated from 2.1.0 to 2.2.0

### WingetUI Log

```text
Logs from when using the inbuilt winget, NOT system winget, and issue reproduced:

🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.0019795894622802734 to load all language files
🟢 checkQueue Thread started!
🟡 Chocolatey was not found on the default location, perhaps a portable WingetUI installation?
🔵 Language file up-to-date
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token e50aefe23a495061c4debe59efec28f2b246cac3bf7fb5e985adf5d65b8b5255
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🔵 Starting Winget source search...
🟢 Winget source search finished with 2 sources
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🔵 Loaded metadata from local file
🟢 Updates not found
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E...
🔵 Reactivation signal ignored: RaiseWindow_[1708556564.937068]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool is disabled', 'PowerShellFound': False, 'PowerShellVersion': 'PowerShell is disabled', 'WingetFound': True, 'WingetVersion': 'v1.6.3482  '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
🟢 Chocolatey source search finished with 0 sources
🟢 Settings tab loaded!
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Winget source search finished with 2 sources
🟢 About tab loaded!
🟢 Scoop source search finished with 0 sources
🟢 Main application loaded...
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🟢 Total packages: 0
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 PowerShell source search finished with 1 sources
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Reloading Scoop sources...
🔵 Starting Winget search for updates
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Logs from when using the inbuilt winget, NOT system winget, and issue reproduced:


Outputs from package managers on the current session:
 ---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x80070005 : Access is denied.---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x80070005 : Access is denied.
---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x80070005 : Access is denied.

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x80070005 : Access is denied.
```

**Comment by stevef-5gn-com-au** [comment]
Looks like I can't update apps using system winget now when trying to "Update as Administrator" :( :( 

```
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing
```

**Comment by stevef-5gn-com-au** [comment]
Ok, i figured out the issue, it was actually not related to the path (which is still incorrect) but my C:\Users\USER\AppData\Local\Microsoft\WinGet\State\defaultState folder required admin perms to open. Anyways, I deleted it and let WinGet recreate it and all seems ok for now

**Comment by Girofox** [comment]
I once had a similar issue and just deleting the database file `%LocalAppData%\Microsoft\WinGet\State\defaultState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db` helped.

**Comment by marticliment** [comment]
therefore this issue has been fixed, right?

**Comment by stevef-5gn-com-au** [comment]
While yes my issue of broken winget is resolved, this issue (unsure if only just cosmetic or not) remains:
![image](https://github.com/marticliment/WingetUI/assets/159501847/6548fd1f-ba65-491d-8fcd-e819d838bab1)

**Comment by marticliment** [comment]
This issue has already been fixed on wingetui 3 alpha
