### ISSUE TITLE
[BUG] "Manage ignored updates" missing

### ISSUE THREAD

**Issue by mdes** [marticliment/WingetUI#1816]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Hello,
In the French version, the choice "Manage ignored updates" does not exist in the toolbar.

### Steps to reproduce the issue

Run WinGetUI

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.01700139045715332 to load all language files
🟢 checkQueue Thread started!
🔵 Language file up-to-date
🔵 Found default chocolatey installation on expected location
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "fr"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token 086d2ac632b2b056acf745579c8e5a115b2e4c1e4419a548cc3319e7840cbb12
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Starting Winget source search...
🟢 Winget source search finished with 2 sources
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\winget...
🔵 Reactivation signal ignored: RaiseWindow_[1708884048.6855242]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop est désactivé(e)', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey est désactivé(e)', 'PipFound': False, 'PipVersion': 'Pip est désactivé(e)', 'NpmFound': False, 'NpmVersion': 'Npm est désactivé(e)', '.NET ToolFound': False, '.NET ToolVersion': '', 'PowerShellFound': False, 'PowerShellVersion': '', 'WingetFound': True, 'WingetVersion': 'v1.6.3482  '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting .NET Tool search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🟢 .NET Tool search for installed packages finished with 0 result(s)
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🟢 Winget source search finished with 2 sources
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 About tab loaded!
🔵 Starting Winget search for updates
🟢 Scoop source search finished with 0 sources
🔵 Starting PowerShell source search...
🟢 Main application loaded...
🟢 Chocolatey source search finished with 1 sources
🔵 Starting .NET Tool search for updates
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
🟡 Installing dotnet-tools-outdated, that was missing...
🟢 Searching for string ""
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
[b'The command could not be loaded, possibly because:\r\n', b'  * You intended to execute a .NET application:\r\n', b"      The application 'tool' does not exist.\r\n", b'  * You intended to execute a .NET SDK command:\r\n', b'      No .NET SDKs were found.\r\n', b'\r\n', b'Download a .NET SDK:\r\n', b'https://aka.ms/dotnet/download\r\n', b'\r\n', b'Learn about SDK resolution:\r\n', b'https://aka.ms/dotnet/sdk-not-found\r\n']
🟢 .NET Tool search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟡 package Windows Driver Package - Intel Net  (0… failed parsing, going for method 2...
🟢 Winget search for installed packages finished with 174 result(s)
🟢 PowerShell source search finished with 1 sources
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 174
🟢 Winget search for updates finished with 2 result(s)
🟡 Package Google.Chrome has version * ignored
🟡 Package SystemExplorer.SystemExplorer has version * ignored
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 70: invalid start byte

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 70: invalid start byte

🔴 Note this traceback was caught by reporter and has been added to the log ('utf-8' codec can't decode byte 0x82 in position 70: invalid start byte)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 -------dotnet
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

-------dotnet
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
--------dotnet

'dotnet-tools-outdated' n'est pas reconnu en tant que commande interne
ou externe, un programme excutable ou un fichier de commandes.---------
---------Winget
- 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.26 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.26 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.26 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.26 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.26 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.26 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.26 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.26 MB
  █████████████████████████████▒  9.00 MB / 9.26 MB
  ██████████████████████████████  9.26 MB / 9.26 MB
                                                                                                                        

   - 
   \ 
                                                                                                                        
Name                                    Id                                      Version            Available     Source
-----------------------------------------------------------------------------------------------------------------------
Mp3tag                                  35795FlorianHeidenreich.Mp3tag.ShellEx… 3.16.1.0
Spotlight Wallpapers                    4484Ram6ler.SpotlightWallpapers_a1cxey… 1.5.1.0
WhatsApp                                5319275A.WhatsAppDesktop_cv1g1gvanyjgm  2.2401.5.0
7-Zip 23.01 (x64)                       7zip.7zip                               23.01                            winget
Signal 6.48.1                           OpenWhisperSystems.Signal               6.48.1                           winget
ShareX                                  ShareX.ShareX                           15.0.0                           winget
Windows Driver Package - Intel Net  (0… A9CA00F445B493FC6A2A568F6A2FA2E7C2C246… 02/09/2023 2.1.3.3
HP Smart                                AD2F1837.HPPrinterControl_v10z8vjag6ke6 151.3.1092.0
AMD Software                            AMD Catalyst Install Manager            24.1.1
AMD Chipset Software                    AMD_Chipset_IODrivers                   6.01.25.342
Adobe Acrobat Reader                    AdobeAcrobatReaderCoreApp_pc75e8sa7ep4e 23.0.0.0
AMD Radeon Software                     AdvancedMicroDevicesInc-RSXCM_fhmx3h6d… 22.10.0.0
Prime Video for Windows                 AmazonVideo.PrimeVideo_pwbj9vvecjh7j    1.0.153.0
AnyBurn                                 PowerSoftware.AnyBurn                   6.0                              winget
AutoHotkey                              AutoHotkey.AutoHotkey                   2.0.11                           winget
Beyond Compare 5.0.0 Beta               BeyondCompare5_is1                      5.0.0.28983
Beyond Translation version 4.3.3.24497  BeyondTranslation4_is1                  Unknown
BingSnap                                BingSnap                                3.1
Microsoft Clipchamp                     Clipchamp.Clipchamp_yxz26nhyzhsrt       2.9.1.0
Cobian Reflector                        Cobian Reflector                        2.3.11
CodeStuff Starter                       CodeStuff Starter                       5.6.2.9
CoolUtils MBox Viewer                   CoolUtils MBox Viewer_is1               2.5
Crucial Storage Executive               Crucial.StorageExecutive                9.09.092023.03                   winget
CrystalDiskInfo 9.2.3                   CrystalDewWorld.CrystalDiskInfo         9.2.3                            winget
DesktopOK                               DesktopOK                               Unknown
Dropbox                                 Dropbox.Dropbox                         193.4.5594                       winget
Dropbox                                 DropboxInc.Dropbox_wkt425jdc3sga        193.4.5594.0
Duplicate File Finder (64-bit)          DupFiles_is1                            3.7
Everything 1.4.1.1024 (x64)             voidtools.Everything                    1.4.1.1024                       winget
Messenger                               FACEBOOK.317180B0BB486_8xx8rvfyw5nnt    2050.11.228.0
Facebook                                FACEBOOK.FACEBOOK_8xx8rvfyw5nnt         2023.531.1.0
FastStone Photo Resizer 4.4             FastStone Photo Resizer                 4.4
FileZilla 3.66.1                        FileZilla Client                        3.66.1
Google Chrome                           Google.Chrome                           122.0.6261.58      122.0.6261.70 winget
HopToDesk                               HopToDesk                               1.40.9
ImageFinder                             ImageFinder                             1.005
K-Lite Codec Pack 17.6.6 Basic          KLiteCodecPack_is1                      17.6.6
Logiciel Logitech Unifying 2.52         Logitech.UnifyingSoftware               2.52.33                          winget
Macrium Reflect Free                    MacriumReflect                          v8.0.7690
Microsoft .NET Framework 1.1            Microsoft .NET Framework 1.1  (1033)    Unknown
Microsoft Edge                          Microsoft.Edge                          122.0.2365.52                    winget
Microsoft Edge Update                   Microsoft Edge Update                   1.3.185.17
Microsoft Edge WebView2 Runtime         Microsoft.EdgeWebView2Runtime           121.0.2277.128                   winget
Cortana                                 Microsoft.549981C3F5F10_8wekyb3d8bbwe   4.2308.1005.0
Microsoft Advertising SDK for XAML      Microsoft.Advertising.Xaml_8wekyb3d8bb… 10.1811.1.0
Actualités                              Microsoft.BingNews_8wekyb3d8bbwe        4.55.62231.0
MSN Météo                               Microsoft.BingWeather_8wekyb3d8bbwe     4.53.52331.0
Programme d'installation d'application  Microsoft.AppInstaller                  1.21.3482.0                      winget
Obtenir de l'aide                       Microsoft.GetHelp_8wekyb3d8bbwe         10.2308.12552.0
Astuces Microsoft                       Microsoft.Getstarted_8wekyb3d8bbwe      10.2312.1.0
HEIF Image Extensions                   Microsoft.HEIFImageExtension_8wekyb3d8… 1.0.63001.0
Extensions vidéo HEVC du fabricant de … Microsoft.HEVCVideoExtension_8wekyb3d8… 2.0.61931.0
Ink.Handwriting.Main.fr-FR.1.0          Microsoft.Ink.Handwriting.Main.fr-FR.1… 0.237.110.0
Ink.Handwriting.fr-FR.1.0               Microsoft.Ink.Handwriting.fr-FR.1.0_8w… 0.237.110.0
Module d'expérience locale français (F… Microsoft.LanguageExperiencePackfr-FR_… 22621.47.192.0
Messages opérateur Windows              Microsoft.Messaging_8wekyb3d8bbwe       5.1901.60431.0
Microsoft Edge                          Microsoft.MicrosoftEdge.Stable_8wekyb3… 122.0.2365.52
Solitaire & Casual Games                Microsoft.MicrosoftSolitaireCollection… 4.19.1261.0
Pense-bêtes Microsoft                   Microsoft.MicrosoftStickyNotes_8wekyb3… 4.0.6002.0
Microsoft .Net Native Framework Packag… Microsoft.NET.Native.Framework.2.2_8we… 2.2.29512.0
Microsoft .Net Native Runtime Package … Microsoft.NET.Native.Runtime.2.2_8weky… 2.2.28604.0
OneDrive                                Microsoft.OneDriveSync_8wekyb3d8bbwe    24020.128.3.0
Outlook for Windows                     Microsoft.OutlookForWindows_8wekyb3d8b… 1.2023.1011.100
Paint                                   Microsoft.Paint_8wekyb3d8bbwe           11.2311.30.0
Contacts Microsoft                      Microsoft.People_8wekyb3d8bbwe          10.2202.33.0
Power Automate                          Microsoft.PowerAutomateDesktop_8wekyb3… 1.0.1091.0
PowerToys ImageResizer Context Menu     Microsoft.PowerToys.ImageResizerContex… 0.78.0.0
Raw Image Extension                     Microsoft.RawImageExtension_8wekyb3d8b… 2.3.171.0
Outil Capture d'écran                   Microsoft.ScreenSketch_8wekyb3d8bbwe    11.2312.33.0
Sécurité Windows                        Microsoft.SecHealthUI_8wekyb3d8bbwe     1000.25992.9000.0
Microsoft Engagement Framework          Microsoft.Services.Store.Engagement_8w… 10.0.23012.0
Hôte de l'expérience du Microsoft Store Microsoft.StorePurchaseApp_8wekyb3d8bb… 22312.1401.1.0
Microsoft To Do                         Microsoft.Todos_8wekyb3d8bbwe           2.114.7122.0
Microsoft.UI.Xaml.2.6                   Microsoft.UI.Xaml.2.6_8wekyb3d8bbwe     2.62112.3002.0
Microsoft.UI.Xaml.2.7                   Microsoft.UI.Xaml.2.7                   7.2208.15002.0                   winget
Microsoft.UI.Xaml.2.8                   Microsoft.UI.Xaml.2.8                   8.2310.30001.0                   winget
Microsoft Visual C++ Runtime Package    Microsoft.VCLibs.120.00_8wekyb3d8bbwe   12.0.21005.1
Microsoft Visual C++ 2015 UWP Desktop … Microsoft.VCLibs.Desktop.14             14.0.33519.0                     winget
Microsoft Visual C++ 2015 UWP Runtime … Microsoft.VCLibs.140.00_8wekyb3d8bbwe   14.0.33519.0
VP9 Video Extensions                    Microsoft.VP9VideoExtensions_8wekyb3d8… 1.1.41.0
Extensions de support web               Microsoft.WebMediaExtensions_8wekyb3d8… 1.0.62931.0
Webp Image Extensions                   Microsoft.WebpImageExtension_8wekyb3d8… 1.0.62681.0
Dev Home (Preview)                      Microsoft.DevHome                       0.1101.416.0                     winget
Photos Microsoft                        Microsoft.Windows.Photos_8wekyb3d8bbwe  2024.11010.23003.0
Horloge Windows                         Microsoft.WindowsAlarms_8wekyb3d8bbwe   1.0.189.0
WindowsAppRuntime.1.2                   Microsoft.WindowsAppRuntime.1.2_8wekyb… 2000.802.31.0
WindowsAppRuntime.1.3                   Microsoft.WindowsAppRuntime.1.3_8wekyb… 3000.934.1904.0
WindowsAppRuntime.1.4                   Microsoft.WindowsAppRuntime.1.4_8wekyb… 4000.1136.2333.0
Calculatrice Windows                    Microsoft.WindowsCalculator_8wekyb3d8b… 11.2311.0.0
Caméra Windows                          Microsoft.WindowsCamera_8wekyb3d8bbwe   2023.2312.3.0
Hub de commentaires                     Microsoft.WindowsFeedbackHub_8wekyb3d8… 1.2401.20253.0
Cartes Windows                          Microsoft.WindowsMaps_8wekyb3d8bbwe     1.0.57.0
Bloc-notes Windows                      Microsoft.WindowsNotepad_8wekyb3d8bbwe  11.2312.18.0
Magnétophone Windows                    Microsoft.WindowsSoundRecorder_8wekyb3… 1.0.71.0
Microsoft Store                         Microsoft.WindowsStore_8wekyb3d8bbwe    22401.1401.2.0
Terminal Windows                        Microsoft.WindowsTerminal               1.19.10302.0                     winget
Windows Package Manager Source (winget) Microsoft.Winget.Source_8wekyb3d8bbwe   2024.222.1023.368
Xbox Game Bar Plugin                    Microsoft.XboxGameOverlay_8wekyb3d8bbwe 1.54.4001.0
Game Bar                                Microsoft.XboxGamingOverlay_8wekyb3d8b… 6.124.1221.0
Xbox Identity Provider                  Microsoft.XboxIdentityProvider_8wekyb3… 12.95.3001.0
Xbox Game Speech Window                 Microsoft.XboxSpeechToTextOverlay_8wek… 1.21.13002.0
Mobile connecté                         Microsoft.YourPhone_8wekyb3d8bbwe       1.24012.92.0
Lecteur multimédia Windows              Microsoft.ZuneMusic_8wekyb3d8bbwe       11.2401.2.0
Films et TV                             Microsoft.ZuneVideo_8wekyb3d8bbwe       10.22091.10061.0
Assistance rapide                       MicrosoftCorporationII.QuickAssist_8we… 2.0.28.0
Windows Web Experience Pack             MicrosoftWindows.Client.WebExperience_… 424.1301.140.0
Mozilla Thunderbird (x64 fr)            Mozilla.Thunderbird                     115.8.0                          winget
Mozilla Maintenance Service             MozillaMaintenanceService               115.8.0
Creevity Mp3 Cover Downloader           Mp3 Cover Downloader_is1                1.4.0
Mp3tag v3.24                            Mp3tag.Mp3tag                           3.24                             winget
MusicBrainz Picard                      MusicBrainz.Picard                      2.11.0                           winget
Quick Share                             NearbyShareLauncher_xyz345f542f50       1.0.1444.0
NetWorx 5.5.5                           NetWorx_is1                             Unknown
Notepad++ (64-bit x64)                  Notepad++.Notepad++                     8.6.4                            winget
Notepad++                               NotepadPlusPlus_7njy0v32s6xk6           1.0.0.0
Microsoft OneDrive                      Microsoft.OneDrive                      24.020.0128.0003                 winget
Intel(R) Network Connections Drivers    PROSet                                  28.0
Microsoft Office Professional Plus 202… ProPlus2021Retail - fr-fr               16.0.17231.20236
RegCool                                 KurtZimmermann.RegCool                  1.353                            winget
Beyond Compare 5 shell extension        ScooterSoftware.BeyondCompare.5.ShellE… 5.0.0.28504
Search and Replace Wizard               Search_Replace_Wizard_is1               3.0
Sweet Home 3D version 7.2               eTeks.SweetHome3D                       7.2                              winget
TeamViewer                              TeamViewer.TeamViewer                   15.50.5                          winget
Tenacity 1.3.3                          TenacityTeam.Tenacity                   1.3.3                            winget
Unlocker 1.9.2                          Unlocker                                1.9.2
VLC media player                        VideoLAN.VLC                            3.0.20                           winget
WinCompose version 0.9.11               SamHocevar.WinCompose                   0.9.11                           winget
WinHTTrack Website Copier 3.49-2 (x64)  XavierRoche.HTTrack                     3.49.2                           winget
Google Drive                            c0c8dc5730739ac4bfc9633f11530400        1.0
Courrier et calendrier                  microsoft.windowscommunicationsapps_8w… 16005.14326.21830…
Logitech SetPoint 6.90                  Logitech.SetPoint                       6.90.66                          winget
Facebook                                www.facebook.com-1C2D851A_n468xs7erp6tc 2023.531.1.1
MiniTool Partition Wizard Free 12.8     MiniTool.PartitionWizard.Free           12.8                             winget
Remove Empty Directories 2.3            JonasJohn.RemoveEmptyDirectories        2.3                              winget
EXIF Date Changer v3.9.3                {26CA1B07-BC53-4196-B9C2-A11C6F6F3E08}… 3.9.3
Microsoft Bing Service                  {27990F25-A90A-4CE5-868E-1A1BB70A58EE}  2.0.0.7
Microsoft Visual C++ 2015-2022 Redistr… Microsoft.VCRedist.2015+.x86            14.38.33130.0                    winget
System Explorer 7.0.0                   SystemExplorer.SystemExplorer           Unknown            7.0.0         winget
paint.net                               dotPDNLLC.paintdotnet                   5.0.12                           winget
Omron Health Management Software        {4FD6E4C8-8B13-433E-879C-7D6FE975BBD0}  1.60.0004
DB Browser for SQLite                   DBBrowserForSQLite.DBBrowserForSQLite   3.12.2                           winget
Outil de téléchargement USB/DVD Window… {5F8683B5-5056-411C-B808-B289E29E9BBB}  1.0.30
Microsoft Visual C++ 2008 Redistributa… Microsoft.VCRedist.2008.x64             9.0.30729.6161                   winget
PDFsam Basic                            PDFsam.PDFsam                           5.2.2.0                          winget
Brother iPrint&Scan                     {7093f2e2-41d5-47f1-a1ea-781ab3ff33ec}  11.0.3.4
Java 8 Update 401 (64-bit)              {71024AE4-039E-4CA4-87B4-2F64180401F0}  8.0.4010.10
Microsoft Visual C++ 2005 Redistributa… Microsoft.VCRedist.2005.x86             8.0.61001                        winget
Microsoft Visual C++ 2008 Redistributa… {8220EEFE-38CD-377E-8595-13398D740ACE}  9.0.30729
WingetUI                                SomePythonThings.WingetUIStore          2.2.0                            winget
calibre 64bit                           calibre.calibre                         7.5.1                            winget
PerspectiveImageCorrection              {8DDC8DA6-3C80-4B95-8F9C-63EE1FF9F44C}  2.0.0.8
Microsoft Visual C++ 2008 Redistributa… {91415F19-4C22-3609-A105-92ED3522D83C}  9.0.30729.4048
Microsoft Filter Pack 2.0               {95140000-2000-0409-1000-0000000FF1CE}  14.0.7015.1000
Microsoft .NET Framework 1.1 French La… {9A394342-4A68-4EBA-85A6-55B559F4E700}  1.1.4322
Microsoft Visual C++ 2008 Redistributa… Microsoft.VCRedist.2008.x86             9.0.30729.6161                   winget
CopyQ 7.1.0                             hluk.CopyQ                              7.1.0                            winget
AnyTXT Searcher 1.3                     {A83692D5-3E9B-4E95-9E7E-B5DF7536C09D}… Unknown
HttpToUsbBridge                         {A92EB32D-F0D1-45D8-A071-262D1229D400}  2.0.33.1
Adobe Acrobat (64-bit)                  {AC76BA86-1036-1033-7760-BC15014EA700}  23.008.20533
PowerShell 7-x64                        Microsoft.PowerShell                    7.4.1.0                          winget
Quick Access Popup v11.6.3.2            {BE9D760B-0D64-40BD-9F24-B5B8AB90131B}… v11.6.3.2
Microsoft Update Health Tools           {C6FD611E-7EFE-488C-A0E0-974C09EF6473}  5.72.0.0
SysTools MBOX Viewer v4.0               {C7D1A247-02C7-4966-850B-7B69B50ED0B4}… Unknown
Regedix                                 {CBA0854E-E0F9-4CB9-B3EB-D0CC39F8F9A0}  2.0.0
Hugin                                   Hugin.Hugin                             20.23.0                          winget
Quick Share from Google                 Google.NearbyShare                      1.0.1444.0                       winget
PDF-XChange Editor                      TrackerSoftware.PDF-XChangeEditor       10.2.1.385                       winget
WinClean 1.3.1                          {F7168958-5DC1-4316-B05E-A5D6E7851C84}… 1.3.1
Agent Ransack                           Mythicsoft.AgentRansack                 9.2.3406.1                       winget
Microsoft Visual C++ 2005 Redistributa… {ad8a2fa1-06e7-4b0d-927d-6e54b3d31028}  8.0.61000
PowerToys (Preview) x64                 Microsoft.PowerToys                     0.78.0                           winget
Microsoft Visual C++ 2015-2022 Redistr… Microsoft.VCRedist.2015+.x64            14.38.33135.0                    winget
Microsoft Windows Desktop Runtime - 6.… Microsoft.DotNet.DesktopRuntime.6       6.0.27                           winget
Microsoft Windows Desktop Runtime - 7.… Microsoft.DotNet.DesktopRuntime.7       7.0.16                           winget
---------Winget
- 
   \ 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.26 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.26 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.26 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.26 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.26 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.26 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.26 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.26 MB
  █████████████████████████████▒  9.00 MB / 9.26 MB
  ██████████████████████████████  9.26 MB / 9.26 MB
                                                                                                                        

   - 
                                                                                                                        
Name                  Id                            Version       Available     Source
--------------------------------------------------------------------------------------
Google Chrome         Google.Chrome                 122.0.6261.58 122.0.6261.70 winget
System Explorer 7.0.0 SystemExplorer.SystemExplorer Unknown       7.0.0         winget
2 upgrades available.
```

### Screenshots and videos

![2024-02-25 19 09 34 (WingetUI)](https://github.com/marticliment/WingetUI/assets/6514419/c3299a8e-d3ea-4019-bb8c-550a7f55b4c5)

**Comment by marticliment** [comment]
Does this happen on the latest prerelease?

**Comment by mdes** [comment]
I'm sorry, but I don't know how to download the last pre-release (3.0.0-ALPHA 2) :(

**Comment by mdes** [comment]
I can manage the ignored ones with v3 α2:
![image](https://github.com/marticliment/WingetUI/assets/6514419/8dcb9bc1-af3a-468a-b21a-c71492213aee)
Thanks a lot for your very quick answer!
Kink regards,
Michel.
