### ISSUE TITLE
[CRASH] (Enter your description here)

### ISSUE THREAD

**Issue by flysn0w** [marticliment/WingetUI#1827]
Hard crash experienced

Error details : 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.26063.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0-alpha2
                Executable: C:\Program Files\WingetUI\wingetui.exe

Crash Message: Cannot start process because a file name has not been provided.

Crash Traceback: 
   at System.Diagnostics.Process.Start()
   at ModernWindow.PackageEngine.Managers.Scoop.RunCleanup() in C:\SomePrograms\WingetUI-Store\src\wingetui-interface\PackageEngine\Managers\Scoop.cs:line 604
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by marticliment** [comment]
This issue will be fixed on the next prerelease version
