### ISSUE TITLE
[BUG] Empty WingetUI window appears when connecting/disconnecting display

### ISSUE THREAD

**Issue by sgilder1** [marticliment/WingetUI#1837]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When connecting or disconnecting a second display (monitor), and WingetUI is running minimised to the system tray, a WingetUI appears on one display, maximised and empty.

### Steps to reproduce the issue

Disconnect and reconnect second display

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.031246423721313477 to load all language files
🟢 checkQueue Thread started!
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Core\Tools.py", line 482, in updateLangFile

🔴    File ".\Core\Tools.py", line 482, in updateLangFile

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 643, in http_error_default

🔴    File "urllib\request.py", line 643, in http_error_default

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴  
During handling of the above exception, another exception occurred:


🔴  
During handling of the above exception, another exception occurred:


🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Core\Tools.py", line 484, in updateLangFile

🔴    File ".\Core\Tools.py", line 484, in updateLangFile

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 643, in http_error_default

🔴    File "urllib\request.py", line 643, in http_error_default

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 404: Not Found)
🔵 Found default chocolatey installation on expected location
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token c8326deed1fe8785d2bbe6a0f63a7051a048a99cc8ed5a311bb508b725f4236c
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🔵 Starting Winget source search...
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Winget source search finished with 2 sources
🔵 Reactivation signal ignored: RaiseWindow_[1709190791.5490687]
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\wingetui.exe
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool is disabled', 'WingetFound': True, 'WingetVersion': 'v1.6.3482  ', 'PowerShellFound': False, 'PowerShellVersion': '', 'ChocolateyFound': True, 'ChocolateyVersion': '2.2.2  '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🟢 Winget source search finished with 2 sources
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🟢 About tab loaded!
🔵 Starting PowerShell source search...
🟢 Scoop source search finished with 0 sources
🔵 Starting Winget search for updates
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 Chocolatey source search finished with 0 sources
🔵 Starting Chocolatey search for updates
🟢 Main application loaded...
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🟢 Winget search for installed packages finished with 178 result(s)
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 178
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 178
🟢 Winget search for updates finished with 2 result(s)
🟡 Package PrimateLabs.Geekbench.6 has version 6.2.2 ignored
🟡 Package Microsoft.Teams.Classic has version * ignored
🟢 Searching for string ""
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
🔵 Starting PowerShell source search...
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🟢 Winget search for updates finished with 2 result(s)
🟡 Package PrimateLabs.Geekbench.6 has version 6.2.2 ignored
🟡 Package Microsoft.Teams.Classic has version * ignored
🟢 Searching for string ""
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Found reactivation lock file...
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 178 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 178
🟢 Searching for string "g"
🟢 Searching for string "gi"
🟢 Searching for string "git"
🟢 Searching for string "git"
🔵 Loading dynamic packages for query git
🔵 Searching packages on chocolatey for query git
🔵 Starting Winget search for dynamic packages
🔵 Starting PowerShell query search
🟢 Winget search for updates finished with 123 result(s)
🟢 Searching for string "git"
🟢 Waiting for install permission... title=Git, id=Git.Git, installId=1709195352.1427236
🔵 Given package: <Package: Git;Git.Git;2.44.0;Winget: winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x00000214ED9FA0D0>;<wingetui.Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x00000214F00833C0>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🔵 Found icon:  https://raw.githubusercontent.com/git/git-scm.com/main/public/images/logos/downloads/Git-Icon-1788C.png
🔵 Current program set to 1709195352.1427236
🟢 Have permission to install, starting installation threads...
🔵 Starting <Package: Git;Git.Git;2.44.0;Winget: winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x00000214ED9FA0D0>;<wingetui.Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x00000214F00833C0>> installation with Command ['C:\\Program Files\\WingetUI\\wingetui\\PackageEngine/Managers\\winget-cli_x64\\winget.exe', 'install', '--id', 'Git.Git', '--exact', '--accept-source-agreements', '--disable-interactivity', '--accept-package-agreements']
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 178 result(s)
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 178
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 178
['Found Git [Git.Git] Version 2.44.0', 'This application is licensed to you by its owner.', 'Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.', 'Downloading https://github.com/git-for-windows/git/releases/download/v2.44.0.windows.1/Git-2.44.0-64-bit.exe', '██████████████████████████████  62.3 MB / 62.3 MB', 'Successfully verified installer hash', 'Starting package install...', 'The installer will request to run as administrator, expect a prompt.', 'Successfully installed', '']
🔵 Adding package to the uninstall section...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting Chocolatey search for updates
🔵 Reloading Scoop sources...
🔵 Starting Winget search for updates
🔵 Starting PowerShell source search...
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🟢 Winget search for updates finished with 2 result(s)
🟡 Package PrimateLabs.Geekbench.6 has version 6.2.2 ignored
🟡 Package Microsoft.Teams.Classic has version * ignored
🟢 Searching for string ""
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting Chocolatey search for updates
🔵 Starting Winget search for updates
🔵 Starting PowerShell source search...
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🟢 Winget search for updates finished with 2 result(s)
🟡 Package PrimateLabs.Geekbench.6 has version 6.2.2 ignored
🟡 Package Microsoft.Teams.Classic has version * ignored
🟢 Searching for string ""
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 179 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 179
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 179 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 179
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
🔵 Starting PowerShell source search...
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 2 result(s)
🟡 Package PrimateLabs.Geekbench.6 has version 6.2.2 ignored
🟡 Package Microsoft.Teams.Classic has version * ignored
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🟢 PowerShell search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 179 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 179
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 179 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 179
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/warnsign.png
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Contains personal info. Will provide if needed.
```

### Relevant information

Running Windows 10.0.22631 Build 22631

**Comment by marticliment** [comment]
This issue has been fixed on the latest prerelease version
