### ISSUE TITLE
[BUG] Discover packages - search loading bar stays after results were found

### ISSUE THREAD

**Issue by min7-i** [marticliment/WingetUI#1843]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When entering a search term for a package in the discover packages section, an animated loading bar will appear (see video below). This bar will stay permanently even when the number of packages found doesn't change anymore.

I can't tell if it's actually still trying to find additional search results or if it's just the animation that is still displayed. Anyway I would expect it to stop searching/stop the animation at some point.

### Steps to reproduce the issue

1. Go to "Discover packages".
2. Enter a search term, e.g. "gimp".
3. Wait for the results to appear.

### WingetUI Log

```text
C:\Users\usernameEdited\AppData\Local\WingetUI\CachedLangFiles\lang_en.json
C:\Program Files\WingetUI\Assets\Languages\lang_en.json
Loaded language locale: en
Api auth token: edited
Starting update check
Api running on http://localhost:7058
Downloaded icons and screenshots successfully!
Lang files were updated successfully
WingetUI is up to date
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. Das System kann die angegebene Datei nicht finden.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 82
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 128
Start backup
Finished loading serializable objects. Serializing with format JSON
Finished serializing
Backup saved to C:\Users\usernameEdited\Documents\WingetUI\device installed packages.json
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
```

### Package Managers Logs

```text
[02.03.2024 09:04:22] .NET Tool - Arguments: tool search "gimp"
       Executable: C:\Program Files\dotnet\dotnet.exe
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'tool' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[02.03.2024 09:04:22] Exit Code: -2147450735
=========================================
=========================================
[02.03.2024 09:04:22] Winget - Arguments:  search "gimp"  --accept-source-agreements
       Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
   \ 
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.39 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.39 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.39 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.39 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.39 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.39 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.39 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.39 MB
  ████████████████████████████▒▒  9.00 MB / 9.39 MB
  ██████████████████████████████  9.39 MB / 9.39 MB
Name         Id                Version Match     Source
--------------------------------------------------------
GIMP         XPDM27W10192Q0    Unknown           msstore
GIMP         GIMP.GIMP         2.10.36           winget
GIMP Nightly GIMP.GIMP.Nightly 2.99.16 Tag: gimp winget
[02.03.2024 09:04:22] Exit Code: 0
=========================================
=========================================
[02.03.2024 09:04:22] Chocolatey - Arguments:  search "gimp"
       Executable: C:\Users\usernameEdited\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
Chocolatey v2.2.2
bouml 7.9.1 [Approved] Downloads cached for licensed users
gimp 2.10.36.1 [Approved] Downloads cached for licensed users
gimp-data-extras 2.0.4 [Approved] Downloads cached for licensed users
photogimp 1.0.2020 [Approved] Downloads cached for licensed users
prime95 30.8.17 [Approved]
ufraw 0.19.2 [Approved]
6 packages found.
[02.03.2024 09:04:22] Exit Code: 0
```

### Screenshots and videos

https://github.com/marticliment/WingetUI/assets/97251923/01272af0-3378-442d-b2b6-852a02ac5732

**Comment by marticliment** [comment]
Hello,

Which Package Managers do you have enabled?

**Comment by min7-i** [comment]
That was a good hint. Winget, Chocolatey, .NET Tool and PowerShell were enabled.

I tried all of the sources separately now and it only happens when PowerShell is enabled. If I just enable the other sources, the loading bar disappears after the packages were found or it will show a message that no results were found.

**Comment by marticliment** [comment]
I will study this

**Comment by min7-i** [comment]
Thanks for fixing it 👍
