### ISSUE TITLE
[3.0-beta0] Crash when clicking on "X" of window

### ISSUE THREAD

**Issue by Girofox** [marticliment/WingetUI#1845]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When I click on "X"-symbol it should minimize to tray but instead it crashes with an error report.

### Steps to reproduce the issue

- Launch WingetUI
- Enable "Close WingetUI to the notification area" under "Notification Tray Options"
- Clicking on "X" in window title bar

### WingetUI Log

```text
OS: Win32NT
                   Version: Microsoft Windows NT 10.0.22631.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0-beta0
                Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: Invalid function. (0x80070001)

Crash Traceback: 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at H.NotifyIcon.Interop.InteropUtilities.EnsureNonZero(BOOL value) in /_/src/libs/H.NotifyIcon/Interop/InteropUtilities.cs:line 85
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetProcessQualityOfServiceLevel(QualityOfServiceLevel level) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 53
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetEfficiencyMode(Boolean value) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 97
   at H.NotifyIcon.WindowExtensions.Hide(Window window, Boolean enableEfficiencyMode) in /_/src/libs/H.NotifyIcon.Shared/WindowExtensions.cs:line 37
   at ModernWindow.MainWindow.HandleClosingEvent(AppWindow sender, AppWindowClosingEventArgs args) in Y:\WingetUI-Store\src\wingetui\Interface\MainWindow.xaml.cs:line 92
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

### Package Managers Logs

```text
Not relevant because updating apps is working as intended.
```

### Relevant information

Possible .NET error?

**Comment by marticliment** [comment]
It looks as an issue with the Efficiency Mode handled by the System Tray Icon library
