### ISSUE TITLE
[BUG] (Error When Launching If Do Not Download App Translations Is Enabled)

### ISSUE THREAD

**Issue by YouSummoner** [marticliment/WingetUI#1851]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

In V3.0 Beta 0 
Enable The Do Not Download App Translations Automatically And Restart WingetUI.
An Error Appear Shown In The Screenshot Below.

### WingetUI Log

```text
C:\Users\suyas\AppData\Local\WingetUI\CachedLangFiles\lang_en.json
Loaded language locale: en
Api auth token: 6t1gcp6dxpaio0ozxq81noliid7ra0j456o21c8l5ggp1at1gs87woy71uffegbo
Starting update check
Api running on http://localhost:7058
Lang files were updated successfully
Downloaded icons and screenshots successfully!
WingetUI is up to date
Could not initialize Package Manager Winget: 
System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_arm64\winget.exe' with working directory 'C:\Program Files\WingetUI'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Winget.LoadManager() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Winget.cs:line 809
   at ModernWindow.PackageEngine.Classes.PackageManager.InitializeAsync() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 41
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
```

### Package Managers Logs

```text
=========================================
[3/3/2024 9:00:31 PM] Chocolatey - Arguments:  source list
       Executable: C:\Users\suyas\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[3/3/2024 9:00:31 PM] Exit Code: 0
=========================================
=========================================
[3/3/2024 9:00:31 PM] PowerShell - Arguments: -NoProfile -Command Get-PSRepository
       Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[3/3/2024 9:00:31 PM] Exit Code: 0
=========================================
=========================================
[3/3/2024 9:00:36 PM] Chocolatey - Arguments:  source list
       Executable: C:\Users\suyas\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[3/3/2024 9:00:36 PM] Exit Code: 0
=========================================
=========================================
[3/3/2024 9:00:37 PM] Chocolatey - Arguments:  outdated
       Executable: C:\Users\suyas\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
Chocolatey v2.2.2
Outdated Packages
 Output is package name | current version | available version | pinned?
Chocolatey has determined 0 package(s) are outdated. 
[3/3/2024 9:00:37 PM] Exit Code: 0
=========================================
=========================================
[3/3/2024 9:00:37 PM] Chocolatey - Arguments:  list
       Executable: C:\Users\suyas\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
Chocolatey v2.2.2
0 packages installed.
[3/3/2024 9:00:37 PM] Exit Code: 0
=========================================
=========================================
[3/3/2024 9:00:38 PM] PowerShell - Arguments: -NoProfile -Command Get-PSRepository
       Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[3/3/2024 9:00:38 PM] Exit Code: 0
=========================================
=========================================
[3/3/2024 9:00:39 PM] PowerShell - Arguments: -NoProfile -Command Get-InstalledModule
       Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
[3/3/2024 9:00:39 PM] Exit Code: 0
=========================================
=========================================
[3/3/2024 9:00:39 PM] PowerShell - Arguments: -NoProfile -Command Get-PSRepository
       Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[3/3/2024 9:00:39 PM] Exit Code: 0
=========================================
=========================================
[3/3/2024 9:00:41 PM] PowerShell - Arguments: 
       Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
PS C:\Program Files\WingetUI> 
PS C:\Program Files\WingetUI>                 function Test-GalleryModuleUpdate {
>>                     param (
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Name,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [version] $Version,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Repository,
>>                         [switch] $NeedUpdateOnly
>>                     )
>>                     process {
>>                         $URLs = @{"PSGallery" = "https://www.powershellgallery.com/api/v2";}
>>                         $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$Name") -UseBasicParsing -Maximum 0 -ea Ignore
>>                         [version]$latest = Split-Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupkg") -Leaf
>>                         $needsupdate = $Latest -gt $Version
>>                         if ($needsupdate) {
>>                             Write-Output ($Name + "|" + $Version.ToString() + "|" + $Latest.ToString() + "|" + $Repository)
>>                         }
>>                     }
>>                 }
>>                 Get-InstalledModule | Test-GalleryModuleUpdate
>>                 exit
>>                 
[3/3/2024 9:00:41 PM] Exit Code: 0
=========================================
```

### Screenshots and videos

![Screenshot 2024-03-03 205049](https://github.com/marticliment/WingetUI/assets/107224555/b092afe4-166f-4419-a619-b1c11d1d7876)

**Comment by marticliment** [comment]
Can you please share your system specs?

**Comment by YouSummoner** [comment]
Asus VivoBook X152FA
Windows 11 Home
Core i3 10th Gen
4 GB RAM

**Comment by marticliment** [comment]
Please do delete the folder named .wingetui under your user directory

**Comment by YouSummoner** [comment]
Sure, also, I never deleted any folder related to WingetUI

**Comment by marticliment** [comment]
Does the issue still happens?

**Comment by YouSummoner** [comment]
It only happens if the Disable auto download translations from GitHub is
enabled

**Comment by marticliment** [comment]
I will investigate the issue
