### ISSUE TITLE
[CRASH] 3.0-beta0 crash

### ISSUE THREAD

**Issue by demo0102** [marticliment/WingetUI#1852]
Hard crash experienced

Error details : 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.22631.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0-beta0
                Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: Object reference not set to an instance of an object.

Crash Traceback: 
   at ModernWindow.PackageEngine.Classes.InstallationOptions..ctor(Package package, Boolean reset) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Package.cs:line 539
   at ModernWindow.PackageEngine.Operations.PackageOperation..ctor(Package package) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Operations\PackageOperations.cs:line 92
   at ModernWindow.PackageEngine.Operations.UpdatePackageOperation..ctor(Package package) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Operations\PackageOperations.cs:line 241
   at ModernWindow.Interface.SoftwareUpdatesPage.MenuInstallSettings_Invoked(Object sender, RoutedEventArgs e) in Y:\WingetUI-Store\src\wingetui\Interface\SoftwarePages\SoftwareUpdates.xaml.cs:line 763
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by marticliment** [comment]
This issue was fixed on a previous commit
