### ISSUE TITLE
[BUG] Installed apps not detected

### ISSUE THREAD

**Issue by lordraiden** [marticliment/WingetUI#1863]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

It does not load the installed apps

### Steps to reproduce the issue

I have tried to uninstall and install several times, I have tried the latest beta
I have tried this as well:
https://github.com/marticliment/WingetUI/issues/1721

### WingetUI Log

```text
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
🔵 It took 0.002001523971557617 to load all language files
🟢 checkQueue Thread started!
🟡 System chocolatey used
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "es"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Core\Tools.py", line 482, in updateLangFile

🔴    File ".\Core\Tools.py", line 482, in updateLangFile

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 643, in http_error_default

🔴    File "urllib\request.py", line 643, in http_error_default

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴  
During handling of the above exception, another exception occurred:


🔴  
During handling of the above exception, another exception occurred:


🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Core\Tools.py", line 484, in updateLangFile

🔴    File ".\Core\Tools.py", line 484, in updateLangFile

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 643, in http_error_default

🔴    File "urllib\request.py", line 643, in http_error_default

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 404: Not Found)
🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token e19b89d5187cf2f28cc177e2f7ad272dcc0e209e3d03e7847cb03d8a31d9cf7a
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Starting Winget source search...
🔵 Loaded metadata from local file
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Winget source search finished with 0 sources
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\wingetui.exe
🔵 Reactivation signal ignored: RaiseWindow_[1709677955.1836603]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop está deshabilitado', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey está deshabilitado', 'PipFound': False, 'PipVersion': 'Pip está deshabilitado', 'NpmFound': False, 'NpmVersion': 'Npm está deshabilitado', 'WingetFound': True, 'WingetVersion': 'v1.6.3482  ', 'PowerShellFound': False, 'PowerShellVersion': '', '.NET ToolFound': False, '.NET ToolVersion': ''}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting .NET Tool search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 .NET Tool search for installed packages finished with 0 result(s)
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🟢 Winget source search finished with 0 sources
🟢 About tab loaded!
🟢 Scoop source search finished with 0 sources
🔵 Starting PowerShell source search...
🟢 Main application loaded...
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🔵 Starting Winget search for updates
🔵 Starting .NET Tool search for updates
🟡 Installing dotnet-tools-outdated, that was missing...
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Winget search for updates finished with 0 result(s)
[b'The command could not be loaded, possibly because:\r\n', b'  * You intended to execute a .NET application:\r\n', b"      The application 'tool' does not exist.\r\n", b'  * You intended to execute a .NET SDK command:\r\n', b'      No .NET SDKs were found.\r\n', b'\r\n', b'Download a .NET SDK:\r\n', b'https://aka.ms/dotnet/download\r\n', b'\r\n', b'Learn about SDK resolution:\r\n', b'https://aka.ms/dotnet/sdk-not-found\r\n']
🟢 Chocolatey source search finished with 1 sources
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Searching for string ""
🟢 .NET Tool search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell source search finished with 1 sources
🟢 PowerShell source search finished with 1 sources
🔵 Starting PowerShell search for updates
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴    File ".\PackageEngine\Managers\powershell.py", line 138, in getAvailableUpdates

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 107: invalid start byte

🔴  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 107: invalid start byte

🔴 Note this traceback was caught by reporter and has been added to the log ('utf-8' codec can't decode byte 0xa2 in position 107: invalid start byte)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Starting Winget search for installed packages
🔵 Starting .NET Tool search for installed packages
🔵 Starting PowerShell search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 PowerShell search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt
-------dotnet
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt

-------dotnet
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

------------------Winget
--------dotnet

"dotnet-tools-outdated" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt
-------dotnet
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt
-------dotnet
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

---------
```

### Screenshots and videos

![imagen](https://github.com/marticliment/WingetUI/assets/17175395/0be16275-c126-44c8-a419-e6aac0a0db19)

**Comment by marticliment** [comment]
Please follow the steps on #1721

**Comment by lordraiden** [comment]
> Please follow the steps on #1721

> Start WingetUI again and disable System Winget if you had enabled it.

What is this step exactly? how do I disable system winget?

**Comment by marticliment** [comment]
WingtUI Settings -> Experimental Settings -> Use System Winget
