### ISSUE TITLE
[BUG] Skip this version doesn't work

### ISSUE THREAD

**Issue by RuiNtD** [marticliment/WingetUI#1865]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

"Skip this version" still shows the skipped versions, even thought they appear on the "Manage ignored updates" page.

### Steps to reproduce the issue

1. Right click on an update and click "Skip this version"
2. Click refresh on the top right.

### WingetUI Log

```text
C:\Users\ethan\AppData\Local\WingetUI\CachedLangFiles\lang_en.json
Loaded language locale: en
Api auth token: t5rdc6oq106ss6wgfw91jx52d9k9d4je59nc40tdgp53k8r4kfldmtyhdr4v03ei
Starting update check
Api running on http://localhost:7058
WingetUI is up to date
Lang files were updated successfully
Downloaded icons and screenshots successfully!
Starting scoop cleanup...
System.TimeoutException: The operation has timed out.
   at ModernWindow.MainApp.InitializeAllManagersAsync() in Y:\WingetUI-Store\src\wingetui\App.xaml.cs:line 201
Timeout: Not all package managers have finished initializing.
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 82
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 128
PowerShell sources took too long to load, using known sources as default
Error finding installed packages on manager Npm: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 146
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Scoop sources took too long to load, using known sources as default
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Start backup
Finished loading serializable objects. Serializing with format JSON
Finished serializing
Backup saved to C:\Users\ethan\Documents\WingetUI\ETHAN-PC installed packages 2024-03-05 22-48-14.json
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 82
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 128
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Unknown source!
Package Id=Python.Python.3.12 with NewVersion=3.12.2 is already installed, skipping it...
```

### Package Managers Logs

```text
N/a
```

### Relevant information

I only tested this with the WinGet source.
I also couldn't include the package manager logs because "There was an error creating your issue: body is too long (maximum is 65536 characters)."

### Screenshots and videos

![WingetUI_TXRtQDrthw](https://github.com/marticliment/WingetUI/assets/1149870/5b60c2e6-88e4-4756-90a2-f8eb8d0ff1a9)
![WingetUI_wtJLKnaRtF](https://github.com/marticliment/WingetUI/assets/1149870/301cf924-3397-47b6-891b-6b8a2056e0a9)

**Comment by marticliment** [comment]
> I also couldn't include the package manager logs because "There was an error creating your issue: body is too long (maximum is 65536 characters)."

Please attach them on a file
