### ISSUE TITLE
[BUG] Overlay icon on Help page

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#1908]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Webviewer views of external webpages show an additional overlay icon over the "Scroll to the top" icon

### Steps to reproduce the issue

Press Help in the tab Package Updates:
- A webviewer opens the external WingetUI Help page
- At the bottom right of the viewport, there's an icon "Scroll to the top"
- This icon has an overlay icon resembling a keyhole with an exclamation mark
- When clicked this overlay icon opens another webviewer window with a webpage of www.iubenda.com "Why does my website show this icon?"

Surely this should not be present in WingetUI?

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.0
               Version Code 3
C:\Users\****\AppData\Local\WingetUI\CachedLangFiles\lang_nl.json
Loaded language locale: nl
Api auth token: ff6h39tu83dqex7o7n7h3rs1ol07r4yppfff97ehh909v84n9xo326akifrhvjyy
Starting update check
Api running on http://localhost:7058
Lang files were updated successfully
WingetUI is up to date
Downloaded icons and screenshots successfully!
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: C:\Program Files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: True
█ Found: True
█ Fancye exe name: pip
█ Executable path: C:\Users\****\AppData\Local\Microsoft\WindowsApps\python.exe
█ Call arguments:  -m pip
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█ Call arguments: 
█ Version: 
█   v1.7.10582
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: True
█ Fancye exe name: choco.exe
█ Executable path: C:\Users\****\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█ Call arguments: 
█ Version: 
█   2.2.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments: -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.22621.2506                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.22621.2506                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\WINDOWS\system32'. Het systeem kan het opgegeven bestand niet vinden.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 82
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
```

### Package Managers Logs

```text
NA
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/10008599/e234ae8f-1f07-4c10-bb77-cfc83f384081)

**Comment by marticliment** [comment]
Oh, this is the Cookies banner. 

I will fix this

**Comment by marticliment** [comment]
This issue has been fixed
![image](https://github.com/marticliment/WingetUI/assets/53119851/78737dd9-e01a-40c6-8a8d-baf78b5ccbf9)
