### ISSUE TITLE
[BUG] 3.0.0 Beta 1 crashes after release of 3.0.0 GA

### ISSUE THREAD

**Issue by dave-sc** [marticliment/WingetUI#1919]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [x] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Tried to open WingetUI Beta 1 today and check if it successfully autoupdated to the release version, but the program does not longer start and instantly crashes. I have attached the stack trace that was logged by the .NET runtime into the windows event log below.

Maybe also affects 3.0.0 when 3.0.1/3.1.0 releases?

### WingetUI Log

```text
Application: WingetUI.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x8001010E): Eine Schnittstelle, die für einen anderen Thread marshalled war, wurde von der Anwendung aufgerufen.

Eine Schnittstelle, die für einen anderen Thread marshalled war, wurde von der Anwendung aufgerufen.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IInfoBarMethods.set_Title(IObjectReference _obj, String value)
   at Microsoft.UI.Xaml.Controls.InfoBar.set_Title(String value)
   at ModernWindow.Structures.AppTools.UpdateWingetUIIfPossible(Int32 round) in Y:\WingetUI-Store\src\wingetui\Core\Tools.cs:line 419
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
Yes, I am aware. 
3.0.0 will not have this issue when updating to newer releases. Please update manually
