### ISSUE TITLE
[ENHANCEMENT] flexible width of tab column

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#1982]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

The tab column at the right side of the WingetUI window is not wide enough for translations with long words.
Please make the width of the tab column flexible so that the largest word fits. 

### Describe how this improvement could help users.

It will prevent unintended breaking of long words.
See example in below screenshot where the word **Geïnstalleerde** is broken.

If this is not possible in the short run, would it be an idea to replace **Installed packages** with **Packages on this system** in order to prevent the situation?

![image](https://github.com/marticliment/WingetUI/assets/10008599/2ac53b61-4a29-402b-94f8-343f1aea8045)

**Comment by marticliment** [comment]
> If this is not possible in the short run, would it be an idea to replace **Installed packages** with **Packages on this system** in order to prevent the situation?

If you feel that this would look better and it would still be understood, you may as well change the Danish translation for it. However, please be consistent with it

**Comment by Stephan-P** [comment]
I have no rights on the Danish language in Tolgee. Aside of that, I wouldn't know Danish without the use of a translation tool.

I did replace "Installed packages" with "Packages on this system"/"Pakketten op dit systeem".
Now waiting for it to show up in my WingetUI.

**Comment by marticliment** [comment]
Sorry, I thought you were the danish translator. I got confused

**Comment by Stephan-P** [comment]
BTW, I've changed the string "Installed packages" into "Packages on this system" in Tolgee 4 days ago, but this update doesn't appear to come across via the option "download updated translations"

**Comment by marticliment** [comment]
It should download, please share the logs, there we should see if the files are being downloaded

**Comment by Stephan-P** [comment]
Welcome to WingetUI Version 3.0.1
               Version Code 3,01
C:\Users\StephanPaternotte\AppData\Local\WingetUI\CachedLangFiles\lang_nl.json
Loaded language locale: nl
Api auth token: iz0ty8r9aqeokfjcc673o7vw4lxfxbhp3il94djl6zupqiwumumh4nse4agf826u
Starting update check
Api running on http://localhost:7058
Lang files were updated successfully
WingetUI is up to date
Downloaded icons and screenshots successfully!
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: C:\Program Files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: True
█ Found: True
█ Fancye exe name: pip
█ Executable path: C:\Users\StephanPaternotte\AppData\Local\Microsoft\WindowsApps\python.exe
█ Call arguments:  -m pip
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█ Call arguments: 
█ Version: 
█   v1.7.10582
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.22621.2506                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.22621.2506                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: True
█ Fancye exe name: choco.exe
█ Executable path: C:\Users\StephanPaternotte\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█ Call arguments: 
█ Version: 
█   2.2.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. Het systeem kan het opgegeven bestand niet vinden.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Starting check for updates wait interval with waitTime=86400
Starting update check
WingetUI is up to date
Starting update check
WingetUI is up to date
Starting update check
WingetUI is up to date
Starting update check
WingetUI is up to date
Starting update check
WingetUI is up to date
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. Het systeem kan het opgegeven bestand niet vinden.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Starting update check
WingetUI is up to date

**Comment by Stephan-P** [comment]
Okay, I used the option to reset WingetUI to it's initial settings and after that the translation updates came through.
Not so nice that the string "Packages on this system" is split into 4 rows. Could have been 3.

![image](https://github.com/marticliment/WingetUI/assets/10008599/9b1bd63c-3209-4c26-9eaf-42d7792186b6)

**Comment by marticliment** [comment]
It should not split, I will take a look at it
