### ISSUE TITLE
[BUG] WingetUI - The package is not updated

### ISSUE THREAD

**Issue by bartoligerman497** [marticliment/WingetUI#1993]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When I select all the packages I want to update, the interface tells me that it was updated successfully but then when I refresh they appear again and the package was never updated

Errors:
  No applicable installer found; see logs for more details.
Winget could not found culture data for package Id=RARLab.WinRAR and Culture=es-AR. Trying to get data for en-US

Received info ModernWindow.PackageEngine.Classes.PackageDetails
System.Runtime.InteropServices.COMException (0x80004005)
   at ModernWindow.Interface.Dialogs.PackageDetailsPage.DownloadInstallerButton_Click(Object sender, RoutedEventArgs e) in Y:\WingetUI-Store\src\wingetui\Interface\Pages\PackageDetailsPage.xaml.cs:line 235
System.Runtime.InteropServices.COMException (0x80004005)
   at ModernWindow.Interface.Dialogs.PackageDetailsPage.DownloadInstallerButton_Click(Object sender, RoutedEventArgs e) in Y:\WingetUI-Store\src\wingetui\Interface\Pages\PackageDetailsPage.xaml.cs:line 235
Notification activated: action=openWingetUI;notificationId=1236 Windows.Foundation.Collections.ValueSet

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.1
               Version Code 3,01
C:\Users\usuario\AppData\Local\WingetUI\CachedLangFiles\lang_es.json
Loaded language locale: es
Api auth token: jaf0r0sxm07tan6z7259ld2r4fshc67q8nbglxspuymhvoy3bm1jsfwb9k4rp68n
Starting update check
Api running on http://localhost:7058
Lang files were updated successfully
WingetUI is up to date
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: C:\Program Files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   8.0.200
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Downloaded icons and screenshots successfully!
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█ Call arguments: 
█ Version: 
█   v1.7.10582
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: True
█ Fancye exe name: choco.exe
█ Executable path: C:\Users\usuario\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█ Call arguments: 
█ Version: 
█   2.2.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.19041.4170                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.19041.4170                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
   - 
   \ 
   | 
   / 
   - 
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.54 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.54 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.54 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.54 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.54 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.54 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.54 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.54 MB
  ████████████████████████████▒▒  9.00 MB / 9.54 MB
  ██████████████████████████████  9.54 MB / 9.54 MB
Found WinRAR [RARLab.WinRAR]
Version: 7.00.0
Publisher: win.rar GmbH
Publisher Url: https://www.win-rar.com
Publisher Support Url: https://www.win-rar.com/support.html?&L=0
Author: RARLab
Moniker: winrar
Description: WinRAR is a powerful archiver (RAR and ZIP) and extractor tool that can open all popular file formats.
Homepage: https://www.win-rar.com/start.html?&L=0
License: Trialware / Nagware
License Url: https://www.win-rar.com/winrarlicense.html?&L=0
Privacy Url: https://www.win-rar.com/cookies.html?&L=0
Copyright: © 2024 win.rar GmbH All rights reserved.
Copyright Url: https://www.win-rar.com/winrarlicense.html?&L=0
Tags:
  archive
  compression
  rar
  winrar
Installer:
  No applicable installer found; see logs for more details.
Winget could not found culture data for package Id=RARLab.WinRAR and Culture=es-AR. Trying to get data for en-US
   - 
   \ 
   | 
   / 
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.54 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.54 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.54 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.54 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.54 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.54 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.54 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.54 MB
  ████████████████████████████▒▒  9.00 MB / 9.54 MB
  ██████████████████████████████  9.54 MB / 9.54 MB
Found WinRAR [RARLab.WinRAR]
Version: 7.00.0
Publisher: win.rar GmbH
Publisher Url: https://www.win-rar.com
Publisher Support Url: https://www.win-rar.com/support.html?&L=0
Author: RARLab
Moniker: winrar
Description: WinRAR is a powerful archiver (RAR and ZIP) and extractor tool that can open all popular file formats.
Homepage: https://www.win-rar.com/start.html?&L=0
License: Trialware / Nagware
License Url: https://www.win-rar.com/winrarlicense.html?&L=0
Privacy Url: https://www.win-rar.com/cookies.html?&L=0
Copyright: © 2024 win.rar GmbH All rights reserved.
Copyright Url: https://www.win-rar.com/winrarlicense.html?&L=0
Tags:
  archive
  compression
  rar
  winrar
Installer:
  Installer Type: exe
  Installer Locale: en-US
  Installer Url: https://www.rarlab.com/rar/winrar-x64-700.exe
  Installer SHA256: 426b7b38ca6de20f1f6535d2fa63c16e11780c7cd5f2ebc66ff9a0022e246e83
  Release Date: 2024-02-28
Received info ModernWindow.PackageEngine.Classes.PackageDetails
System.Runtime.InteropServices.COMException (0x80004005)
   at ModernWindow.Interface.Dialogs.PackageDetailsPage.DownloadInstallerButton_Click(Object sender, RoutedEventArgs e) in Y:\WingetUI-Store\src\wingetui\Interface\Pages\PackageDetailsPage.xaml.cs:line 235
System.Runtime.InteropServices.COMException (0x80004005)
   at ModernWindow.Interface.Dialogs.PackageDetailsPage.DownloadInstallerButton_Click(Object sender, RoutedEventArgs e) in Y:\WingetUI-Store\src\wingetui\Interface\Pages\PackageDetailsPage.xaml.cs:line 235
Notification activated: action=openWingetUI;notificationId=1236 Windows.Foundation.Collections.ValueSet
   - 
   \ 
   | 
   / 
   - 
   \ 
   | 
   / 
   - 
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.54 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.54 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.54 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.54 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.54 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.54 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.54 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.54 MB
  ████████████████████████████▒▒  9.00 MB / 9.54 MB
  ██████████████████████████████  9.54 MB / 9.54 MB
Found WinRAR [RARLab.WinRAR]
Version: 7.00.0
Publisher: win.rar GmbH
Publisher Url: https://www.win-rar.com
Publisher Support Url: https://www.win-rar.com/support.html?&L=0
Author: RARLab
Moniker: winrar
Description: WinRAR is a powerful archiver (RAR and ZIP) and extractor tool that can open all popular file formats.
Homepage: https://www.win-rar.com/start.html?&L=0
License: Trialware / Nagware
License Url: https://www.win-rar.com/winrarlicense.html?&L=0
Privacy Url: https://www.win-rar.com/cookies.html?&L=0
Copyright: © 2024 win.rar GmbH All rights reserved.
Copyright Url: https://www.win-rar.com/winrarlicense.html?&L=0
Tags:
  archive
  compression
  rar
  winrar
Installer:
  No applicable installer found; see logs for more details.
Winget could not found culture data for package Id=RARLab.WinRAR and Culture=es-AR. Trying to get data for en-US
```

### Package Managers Logs

```text
█▀▀▀▀▀▀▀▀▀ [18/3/2024 16:58:43] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  update --include-unknown  --accept-source-agreements
   \ 
   / 
   \ 
   / 
   \ 
   / 
   \ 
   / 
   \ 
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.54 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.54 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.54 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.54 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.54 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.54 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.54 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.54 MB
  ████████████████████████████▒▒  9.00 MB / 9.54 MB
  ██████████████████████████████  9.54 MB / 9.54 MB
   - 
   | 
Name                                             Id                                  Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------
Notepad++ (64-bit x64)                           Notepad++.Notepad++                 8.6.2         8.6.4         winget
WinRAR 6.24 (64-bit)                             RARLab.WinRAR                       6.24.0        7.00.0        winget
Microsoft Visual C++ 2015-2022 Redistributable … Microsoft.VCRedist.2015+.x86        14.38.33130.0 14.40.33617.1 winget
Microsoft SQL Server Management Studio - 19.0.2  Microsoft.SQLServerManagementStudio 19.0.2        19.3          winget
Microsoft .NET Core SDK 2.1.301 (x64)            Microsoft.DotNet.SDK.3_1            < 3.1.419     3.1.426       winget
5 upgrades available.
[18/3/2024 16:58:43] Exit Code: 0
```

**Comment by marticliment** [comment]
Hello,

Some packages sometimes fail to be detected properly by Winget, causing missing packages or mistakenly reported updates. Please use the "Ignore Updates" or "Skip this version" options within WingetUI.

Since this is an issue with Winget (not WingetUI), the error cannot be fixed from here, so my best advice is to ignore those updates
