### ISSUE TITLE
[BUG] Missing Winget Packages/Updates

### ISSUE THREAD

**Issue by codengine** [marticliment/WingetUI#2037]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Since the Update to 3.0.1 I can't find Winget Packages anymore. It used to work just fine.
I also followed the steps described here: https://github.com/marticliment/WingetUI/issues/1721 with no luck.

### Steps to reproduce the issue

Just start WingetUI

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.1
               Version Code 3,01
C:\Users\shueg\AppData\Local\WingetUI\CachedLangFiles\lang_de.json
Loaded language locale: de
Api auth token: hx0wl4t6uf9qf7kly7d5genx3rezd6s4gki5a7a8zi102lbie9t4vaoologpr5mm
Starting update check
Api running on http://localhost:7058
Lang files were updated successfully
Downloaded icons and screenshots successfully!
WingetUI is up to date
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: True
█ Found: True
█ Fancye exe name: pip
█ Executable path: C:\Users\shueg\AppData\Local\Microsoft\WindowsApps\python.exe
█ Call arguments:  -m pip
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: c:\program files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   8.0.202
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█ Call arguments: 
█ Version: 
█   v1.7.10582
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: True
█ Fancye exe name: choco.exe
█ Executable path: c:\programdata\chocolatey\bin\choco.exe
█ Call arguments: 
█ Version: 
█   2.2.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.19041.4170                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.19041.4170                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ModernWindow.PackageEngine.Managers.Winget.GetInstalledPackages_UnSafe() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Winget.cs:line 236
```

### Package Managers Logs

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:17] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[25.03.2024 11:56:17] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:17] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: c:\programdata\chocolatey\bin\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[25.03.2024 11:56:17] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:17] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[25.03.2024 11:56:17] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:18] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[25.03.2024 11:56:18] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:18] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\shueg\AppData\Local\Microsoft\WindowsApps\python.exe
█  Arguments:  -m pip list --outdated
Python konnte nicht gefunden werden. Führen Sie die Verknüpfung ohne Argumente aus, um sie über den Microsoft Store zu installieren, oder deaktivieren Sie diese Verknüpfung unter 
[25.03.2024 11:56:18] Exit Code: 9009
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:18] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\shueg\AppData\Local\Microsoft\WindowsApps\python.exe
█  Arguments:  -m pip list
Python konnte nicht gefunden werden. Führen Sie die Verknüpfung ohne Argumente aus, um sie über den Microsoft Store zu installieren, oder deaktivieren Sie diese Verknüpfung unter 
[25.03.2024 11:56:18] Exit Code: 9009
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:18] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: c:\program files\dotnet\dotnet.exe
█  Arguments: tool list --global
Paket-ID                   Version         Befehle              
----------------------------------------------------------------
dotnet-ef                  8.0.2           dotnet-ef            
dotnet-tools-outdated      0.7.1           dotnet-tools-outdated
nuke.globaltool            8.0.0           nuke                 
obfuscar.globaltool        2.2.38          obfuscar.console     
upgrade-assistant          0.4.410601      upgrade-assistant    
x                          6.0.12          x                    
[25.03.2024 11:56:18] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:18] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: c:\programdata\chocolatey\bin\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[25.03.2024 11:56:18] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:19] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\shueg\.dotnet\tools\dotnet-tools-outdated.exe
█  Arguments: 
Package Id        Current    Available
--------------------------------------
dotnet-ef         8.0.2      8.0.3
upgrade-assistant 0.4.410601 0.5.586
x                 6.0.12     8.0.1
[25.03.2024 11:56:19] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:19] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[25.03.2024 11:56:19] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:19] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: c:\programdata\chocolatey\bin\choco.exe
█  Arguments:  list
Chocolatey v2.2.2
7zip.install 23.1.0
anydesk 8.0.8
anydesk.portable 8.0.8
audacity 3.4.2
autohotkey.portable 2.0.11
autohotkey-compiler 1.0.0
avidemux 2.8.1
cheatengine 7.5.0
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolateygui 2.1.0
chocolatey-misc-helpers.extension 0.0.4
chocolatey-windowsupdate.extension 1.0.5
cmake 3.28.3
cmake.install 3.28.3
crystaldiskinfo 9.1.1
crystaldiskinfo.portable 9.1.1
DotNet4.5.2 4.5.2.20140902
DotNet4.6.1 4.6.1055.20170308
dotnetfx 4.8.0.20220524
eac 1.6.0
filezilla 3.66.5
freac 1.1.7
freac.portable 1.1.7
fsviewer 7.8.0
ghidra 11.0.1
git 2.44.0
git.install 2.44.0
hxd 2.5.0
InkScape 1.3.2
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
keepass 2.56.0
keepass.install 2.56.0
kubernetes-helm 3.14.1
maven 3.9.6
microsoft-teams 1.7.0.6058
mingw 13.2.0
mp3tag 3.24.0
mpc-be 1.6.11
musicbee 3.5.8698
netfx-4.7.2 4.7.2
ngrok 3.7.0
nodejs-lts 20.11.1
openvpn 2.6.9.1
peazip 9.7.1
peazip.install 9.7.1
php 8.3.3
postman 10.23.5
poweriso 8.2.0
qbittorrent 4.6.3
quarkus 3.8.2
rufus 4.4.0
scummvm 2.8.0
signal 6.48.0
slack 4.36.136
smtp4dev 3.3.2
sumatrapdf 3.5.2
sumatrapdf.install 3.5.2
vcredist140 14.38.33130
vcredist2015 14.0.24215.20170201
vcredist2017 14.16.27033
virtualclonedrive 5.5.2
vlc 3.0.20
vlc.install 3.0.20
vortex 1.10.6
vscode 1.86.2
vscode.install 1.86.2
windirstat 1.1.2.20161210
WinImage 9.0.0
winrar 7.0.0
wowup 2.10.0
77 packages installed.
[25.03.2024 11:56:19] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:19] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-InstalledModule
[25.03.2024 11:56:19] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:19] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: 
Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
Lernen Sie das neue plattform�bergreifende PowerShell kennen - https://aka.ms/pscore6
PS C:\Program Files\WingetUI> 
PS C:\Program Files\WingetUI>                 function Test-GalleryModuleUpdate {
>>                     param (
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Name,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [version] $Version,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Repository,
>>                         [switch] $NeedUpdateOnly
>>                     )
>>                     process {
>>                         $URLs = @{}
>>                         @(Get-PSRepository).ForEach({$URLs[$_.Name] = $_.SourceLocation})
>>                         $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$Name") -UseBasicParsing -Maximum 0 -ea Ignore
>>                         [version]$latest = Split-Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupkg") -Leaf
>>                         $needsupdate = $Latest -gt $Version
>>                         if ($needsupdate) {
>>                                 Write-Output($Name + "|" + $Version.ToString() + "|" + $Latest.ToString() + "|" + $Repository)
>>                         }
>>                     }
>>                 }
>>                 Get-InstalledModule | Test-GalleryModuleUpdate
PS C:\Program Files\WingetUI>                 exit
[25.03.2024 11:56:19] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:19] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  update --include-unknown  --accept-source-agreements
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").
   \ 
Failed when searching source; results will not be included: winget
No installed package found matching input criteria.
[25.03.2024 11:56:19] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:20] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  list  --accept-source-agreements
   - 
Failed when searching source; results will not be included: winget
[25.03.2024 11:56:20] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:20] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: c:\programdata\chocolatey\bin\choco.exe
█  Arguments:  outdated
Chocolatey v2.2.2
Outdated Packages
 Output is package name | current version | available version | pinned?
cmake|3.28.3|3.29.0|false
cmake.install|3.28.3|3.29.0|false
kubernetes-helm|3.14.1|3.14.2|false
ngrok|3.7.0|3.8.0|false
openvpn|2.6.9.1|2.6.10.001|false
php|8.3.3|8.3.4|false
poweriso|8.2.0|8.7.0|true
quarkus|3.8.2|3.8.3|false
signal|6.48.0|7.3.1|false
slack|4.36.136|4.37.98|false
smtp4dev|3.3.2|3.3.4|false
vcredist140|14.38.33130|14.38.33135|false
vortex|1.10.6|1.10.7|false
vscode|1.86.2|1.87.2|false
vscode.install|1.86.2|1.87.2|false
Chocolatey has determined 15 package(s) are outdated. 
[25.03.2024 11:56:20] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [25.03.2024 11:56:37] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[25.03.2024 11:56:37] Exit Code: 0
```

**Comment by marticliment** [comment]
Please try resetting winget sources using the option that can be found on WingetUI Setting -> WinGet -> Reset WinGet Sources

**Comment by codengine** [comment]
> Please try resetting winget sources using the option that can be found on WingetUI Settings -> WinGet -> Reset WinGet Sources

I already reset it multiple times.

```
Info: Elevation allowed for process Id 3124 and children.
Warning: Cache is a security risk. Use `gsudo cache off` (or `-k`) to go back to safety.
This script will reset winget sources.
. Please wait...
winget path: "C:\Program Files\WingetUI\Assets\Utilities\..\..\winget-cli\PackageManagers\winget-cli_x64\winget.exe"
Deleting Winget local data sources...
Performing reset...
Removing source: winget...
Done
Adding source:
  winget -> https://cdn.winget.microsoft.com/cache
  ██████████████████████████████  5.17 MB / 5.17 MB
Done
Resetting all sources...Done
Info: Cache session closed.
Task completed!
You can now close this window and refresh your package lists
```

The issue remains.

**Comment by codengine** [comment]
I also reinstalled WingetUI and reset WingetUI itself - no luck.
Before 3.0.0 everything worked nicely.

**Comment by marticliment** [comment]
Then please try enabling system winget (WingetUI Settings -> Experimental preferences -> Enable system winget)

**Comment by codengine** [comment]
This didn't work either. What DID work however was the following:
- Opening an elevated terminal
- `winget source update`
- `winget update --include-unknown  --accept-source-agreements`

Afterwards I unchecked the experimental setting, deleted the Winget Cache again and its showing up now. I still don't know if its an error on my behalf or if the issue is in WingetUI because it used to work flawlessly before.

**Comment by marticliment** [comment]
This is more likely to have been caused by a corrupted WinGet database or similar, so it would be more likely to be related with WinGet...
