### ISSUE TITLE
[BUG] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by andraaspar** [marticliment/WingetUI#2044]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Install does not work, error is displayed.

### Steps to reproduce the issue

Try to install DBeaver 24.0.1 from Winget using the following options:

![image](https://github.com/marticliment/WingetUI/assets/3512382/ede60abb-321d-46d6-a09c-34274cbdf23d)

### WingetUI Log

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.22621.2506                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.22621.2506                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
System.Text.Json.JsonException: '}' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 211.
 ---> System.Text.Json.JsonReaderException: '}' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 211.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   at ModernWindow.PackageEngine.Classes.InstallationOptions.LoadOptionsFromDisk() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Package.cs:line 724
 -
 -
  ⚠️⚠️⚠️ START OF UNHANDLED ERROR TRACE ⚠️⚠️⚠️
Unhandled Exception raised: Object reference not set to an instance of an object.
Stack Trace: 
   at ModernWindow.PackageEngine.Classes.InstallationOptions..ctor(Package package, Boolean reset) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Package.cs:line 585
   at ModernWindow.PackageEngine.Operations.PackageOperation..ctor(Package package) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Operations\PackageOperations.cs:line 92
   at ModernWindow.PackageEngine.Operations.InstallPackageOperation..ctor(Package package) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Operations\PackageOperations.cs:line 99
   at ModernWindow.Interface.DiscoverPackagesPage.MenuInstallSettings_Invoked(Object sender, RoutedEventArgs e) in Y:\WingetUI-Store\src\wingetui\Interface\SoftwarePages\DiscoverPackages.xaml.cs:line 679
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
  ⚠️⚠️⚠️  END OF UNHANDLED ERROR TRACE  ⚠️⚠️⚠️
 -
 -
System.Text.Json.JsonException: '}' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 211.
 ---> System.Text.Json.JsonReaderException: '}' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 211.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   at ModernWindow.PackageEngine.Classes.InstallationOptions.LoadOptionsFromDisk() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Package.cs:line 724

```
```


### Package Managers Logs

```text
Nothing here.
```

**Comment by marticliment** [comment]
This issue was fixed on a previous commit.

Changes will be effective on the next release
