### ISSUE TITLE
[BUG] IndexOutOfRangeException with non global npm list

### ISSUE THREAD

**Issue by NorbertHD** [marticliment/WingetUI#2067]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When WingetUi searches for npm updates there is an IndexOutOfRangeException in the logs.

"npm list" gives the output "`-- (empty)". After the split with "@" there is only one element in the "elements" array.
And then "elements[1]" leads to the IndexOutOfRangeException.

Please add:

   if (elements.Length >= 2)

before line 155 in file Npm.cs

### WingetUI Log

```text
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
```

### Package Managers Logs

```text
Irrelevant
```

**Comment by marticliment** [comment]
Please shatr your Package Manager logs, so I can see which packages are failing

**Comment by NorbertHD** [comment]
Original post updated with Package Manager log.
Thanks for looking into it.

**Comment by marticliment** [comment]
Nice!

**Comment by edumserrano** [comment]
I'm also getting this issue:

> LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding installed packages on manager Npm: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds

Is there any extra info I can provide?

**Comment by marticliment** [comment]
This is fine, I don't need more details
