### ISSUE TITLE
[CRASH] (Enter your description here)

### ISSUE THREAD

**Issue by JeanChristian12** [marticliment/WingetUI#2075]
Hard crash experienced

Error details : 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.22631.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0.0
                Executable: C:\Users\jean-\AppData\Local\Programs\WingetUI\WingetUI.exe

Crash Message: Le texte associé à ce code d’erreur est introuvable.

Cannot create instance of type 'ModernWindow.Interface.Widgets.NavButton' [Line: 0 Position: 0]

Crash Traceback: 
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at ModernWindow.Interface.NavigationPage.InitializeComponent()
   at ModernWindow.Interface.NavigationPage..ctor()
   at ModernWindow.MainWindow.SwitchToInterface()
   at ModernWindow.MainApp.LoadComponentsAsync()
```

**Comment by marticliment** [comment]
Hello, everyone,

**WingetUI 3.0.2 has been published. It fixes**
 - Crashes with .NET Sdk 8.0.3 (no launch at all)
 - Crashes with .NET Sdk 8.0.4 (Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml)
 - Crashes with the App Sdk (This app requires whe Windows App runtime) when it was already installed
 - Crashes when elevating WingetUI from non-admin users

**WingetUI 3.0.2 can be downloaded directly from [here](https://github.com/marticliment/WingetUI/releases/download/3.0.2/WingetUI.Installer.exe). If the crashes persist, please reply here and I will reopen the issue.**
