### ISSUE TITLE
[BUG] Scoop was not found on WingetUI 3.x, works fine on 2.2

### ISSUE THREAD

**Issue by unxpected-uxp** [marticliment/WingetUI#2157]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When using any 3.x version of WingetUI it says "Scoop was not found".
Using version 2.2 it works totally fine.

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.0
               Version Code 3
C:\Users\uXp\AppData\Local\WingetUI\CachedLangFiles\lang_en.json
Loaded language locale: en
Api auth token: v8ad7ljwsyyhzfhk88m5f60yam4d95wdkzq3wpkxmpumxmwlbpofc6jb0dvducye
Starting update check
Api running on http://localhost:7058
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   at ModernWindow.Core.Data.LanguageEngine.UpdateLanguageFile(String LangKey) in Y:\WingetUI-Store\src\wingetui\Core\Data\LanguageData.cs:line 103
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Downloaded icons and screenshots successfully!
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Updates found, downloading installer...
Current version: 3
Latest version : 3.02
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
Waiting for mainWindow to be hidden





🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.006512165069580078 to load all language files
🟢 checkQueue Thread started!
🟡 Chocolatey was not found on the default location, perhaps a portable WingetUI installation?
---------------------------------------------------------------------------------------------------

   WingetUI version 2.2.0 (version number 2.2) log
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function language set to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception

🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Core\Tools.py", line 482, in updateLangFile

🔴    File ".\Core\Tools.py", line 482, in updateLangFile

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 643, in http_error_default

🔴    File "urllib\request.py", line 643, in http_error_default

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴  
During handling of the above exception, another exception occurred:


🔴  
During handling of the above exception, another exception occurred:


🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Core\Tools.py", line 484, in updateLangFile

🔴    File ".\Core\Tools.py", line 484, in updateLangFile

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 216, in urlopen

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 525, in open

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 634, in http_response

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 563, in error

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 496, in _call_chain

🔴    File "urllib\request.py", line 643, in http_error_default

🔴    File "urllib\request.py", line 643, in http_error_default

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴  urllib.error.HTTPError: HTTP Error 404: Not Found

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 404: Not Found)
🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Starting API with random session authentication token ac3d0311fc8980690f012d4afa7791fbb6603d1bc11f7ed5e24829b3f33fec47
🟡 Found lock file(s), reactivating...
🔵 Reloading Scoop sources...
🔵 Loading WingetUI AUMID...
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔴  Traceback (most recent call last):

🔴  Traceback (most recent call last):

🔴    File ".\Interface\Application.py", line 222, in getAUMID

🔴    File ".\Interface\Application.py", line 222, in getAUMID

🔴  IndexError: list index out of range

🔴  IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Reactivation signal ignored: RaiseWindow_[1713732249.491495]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'WingetFound': False, 'WingetVersion': 'Winget is disabled', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool is disabled', 'PowerShellFound': False, 'PowerShellVersion': 'PowerShell is disabled', 'ScoopFound': True, 'ScoopVersion': "Current Scoop version: 105e4161 chore(release): Bump to version 0.4.0 (#5424)  'main' bucket: ce7b105b0 oxipng: Update to version 9.1.0  'extras' bucket: 14469c070 telegram-downloader: Update to version 0.17.0  'versions' bucket: f63d8779e swift-nightly: Update to version 20240421.3  'java' bucket: 04ec327c temurin22-jre: Update to version 22.0.1-8  'games' bucket: 3dcba5e7a ryujinx: Update to version 1.1.1290  'Deide_deide-bucket' bucket: 197373b duckstation: Fix version regex  'okibcn_ScoopMaster' bucket:  "}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Scoop search for installed packages
🟢 Searching for string ""
🔵 Starting Winget source search...
🔵 Starting Scoop source search...
🔵 Starting Chocolatey source search...
🔵 Starting PowerShell source search...
🟢 Settings tab loaded!
🟢 Winget source search finished with 0 sources
🟢 Chocolatey source search finished with 0 sources
🟢 About tab loaded!
🔵 Reloading Scoop sources...
🟢 Main application loaded...
🟢 Scoop source search finished with 0 sources
🟢 Total packages: 0
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File ".\Interface\CustomWidgets\InstallerWidgets.py", line 669, in <lambda>
TypeError: 'NoneType' object is not callable
🟢 PowerShell source search finished with 1 sources
🟢 Scoop search for installed packages finished with 77 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 77
🔵 Starting Scoop search for updates
🟢 Scoop search for updates finished with 20 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 6
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [21/04/2024 22:50:52] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: S:\WingetUI3\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[21/04/2024 22:50:52] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [21/04/2024 22:50:53] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: S:\WingetUI3\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
Directory 'S:\apps\wingetui\current\choco-cli\lib' does not exist.
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[21/04/2024 22:50:53] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [21/04/2024 22:50:54] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[21/04/2024 22:50:54] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [21/04/2024 22:50:54] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: S:\WingetUI3\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[21/04/2024 22:50:54] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [21/04/2024 22:50:55] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: S:\WingetUI3\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
Directory 'S:\apps\wingetui\current\choco-cli\lib' does not exist.
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[21/04/2024 22:50:55] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [21/04/2024 22:50:55] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[21/04/2024 22:50:55] Exit Code: 0





Outputs from package managers on the current session:
 ---------Scoop
Installed apps:

Name                     Version               Source                     Updated             Info
----                     -------               ------                     -------             ----
7zip                     23.01                 main                       2023-08-07 21:18:20
audacity                 3.4.2                 extras                     2023-11-30 14:35:21
autohotkey               2.0.12                extras                     2024-04-10 19:00:37
avidemux                 2.8.1                 extras                     2023-08-06 13:08:31
borderlessgaming         9.5.6                 Deide_deide-bucket         2024-04-19 16:22:03
Cinebench-R15            15.0                  AkariiinMKII_Scoop4kariiin 2023-08-07 21:21:27
Cinebench-R20            20.060                AkariiinMKII_Scoop4kariiin 2023-08-07 21:21:57
Cinebench-R23            23.200                AkariiinMKII_Scoop4kariiin 2023-08-07 21:22:33
cpu-z                    2.09                  extras                     2024-01-19 18:44:52
cru                      1.5.2                 extras                     2024-03-14 09:26:18
crystaldiskinfo          9.2.3                 extras                     2024-02-19 10:33:15
crystaldiskmark          8.0.5                 extras                     2024-02-25 10:21:15
dark                     3.14                  main                       2024-02-25 10:21:17
defraggler               2.22.995              extras                     2023-08-24 10:51:17
dshidmini                2.2.282.0             okibcn_ScoopMaster         2024-02-25 12:45:59
dupeguru                 4.3.1                 extras                     2024-02-11 20:18:13
dxwnd                    2.06.03               extras                     2024-03-13 11:52:22
ffmpeg                   7.0                   main                       2024-04-10 19:01:01
firefox                  125.0.1               extras                     2024-04-19 11:02:10
geekbench                6.3.0                 extras                     2024-04-14 21:30:10
gimp                     2.10.36-1             extras                     2024-03-01 15:43:38
git                      2.44.0                main                       2024-02-25 10:21:31
gpu-z                    2.58.0                extras                     2024-04-10 19:01:09
handbrake                1.7.3                 extras                     2024-02-19 10:33:27
hwinfo                   8.00-5400             extras                     2024-04-10 19:01:19
imdisk                   2.1.1                 okibcn_ScoopMaster         2023-11-16 13:02:12
innounp                  0.50                  main                       2024-02-19 11:03:44
jdownloader              nightly-20230806      versions                   2023-08-06 15:44:37
joplin                   2.13.15               anderlli0053_DEV-tools-    2024-04-16 12:38:45
kdenlive                 24.02.2               extras                     2024-04-16 09:17:32
libreoffice              24.2.2                extras                     2024-04-10 19:03:11
LivelyWallpaper-Portable 2.0.7.4               ACooper81_scoop-apps       2023-11-03 12:57:07
losslesscut              3.59.1                extras                     2024-01-11 08:39:48
magpie                   0.10.6                extras                     2024-03-05 16:14:05
makemkv                  1.17.6                extras                     2024-01-23 08:47:34
mkvtoolnix               83.0                  extras                     2024-03-13 11:52:47
monitorian               4.3.0                 okibcn_ScoopMaster         2023-09-17 22:33:39
mp3directcut             2.36                  extras                     2023-08-06 13:12:23
mp3tag                   3.25                  extras                     2024-04-10 19:03:13
mpv.net                  7.1.1.0               extras                     2024-04-14 21:36:50
obs-studio               30.1.2                extras                     2024-04-10 19:03:50
ontopreplica             3.5.1-fix             extras                     2024-04-18 18:52:43
plex-server              1.40.2.8395-c67dce28e main                       2024-04-19 17:04:17
powertoys                0.80.1                extras                     2024-04-12 14:35:53
putty                    0.81                  extras                     2024-04-16 09:17:33
python                   3.12.2                main                       2024-02-19 10:35:35
qtifw                    4.7.0                 main                       2024-02-21 08:32:41
r                        4.3.3                 main                       2024-03-01 15:45:55
rstudio                  2023.12.1-402         extras                     2024-02-19 10:36:16
rtss                     7.3.6                 extras                     2024-04-10 19:06:08
rufus                    4.4                   extras                     2024-01-19 18:45:29
scoop-search             1.4.1                 main                       2024-04-19 17:27:22
scrcpy                   2.4                   main                       2024-03-05 16:14:51
shutup10                 1.9.1436              extras                     2023-11-03 12:58:22
ssd-z                    16.09.09              extras                     2023-08-06 13:18:16
subtitleedit             4.0.5                 extras                     2024-04-14 21:30:21
sudo                     0.2020.01.26          anderlli0053_DEV-tools     2024-04-15 16:49:26
sunshine                 0.23.0                extras                     2024-04-15 21:16:42
temurin8-jre             8.0.402-6             java                       2024-01-23 08:47:53
UltimateWindowsTweaker   5.1                   JesseRacine_myscoop        2023-08-23 19:36:49
ungoogled-chromium       123.0.6312.105-1.1    extras                     2024-04-10 19:05:15
ventoy                   1.0.97                extras                     2024-01-24 14:26:07
virtualbox               7.0.14                okibcn_ScoopMaster         2024-03-07 16:03:43
vlc                      3.0.20                extras                     2023-11-03 12:58:57
vscodium                 1.88.1.24104          extras                     2024-04-14 21:34:40
win10_brightnessslider   1.7.15                extras                     2023-08-06 16:03:58
winmerge                 2.16.38               extras                     2024-02-19 10:36:23
winrar                   7.00                  extras                     2024-03-01 15:46:15
wireguard                0.5.3                 okibcn_ScoopMaster         2024-03-20 14:27:05
wireshark                4.2.4                 extras                     2024-04-10 19:05:44
wizfile                  3.09                  extras                     2023-08-06 13:18:19
wiztree                  4.19                  extras                     2024-03-05 16:14:56
wxmp3gain                4.0                   okibcn_ScoopMaster         2023-09-14 22:54:17
yumi                     2.0.9.4               extras                     2023-08-06 13:22:40
yumi-exfat               1.0.2.5               extras                     2024-02-19 10:37:08
yumi-uefi                0.0.4.6               extras                     2023-08-06 13:37:07---------Scoop
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: ambiguous argument 'HEAD..origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Name                     Installed Version  Latest Version     Missing Dependencies Info
----                     -----------------  --------------     -------------------- ----
autohotkey               2.0.12             2.0.13
Cinebench-R15            15.0                                                       Manifest removed
Cinebench-R20            20.060                                                     Manifest removed
Cinebench-R23            23.200                                                     Manifest removed
dshidmini                2.2.282.0                                                  Manifest removed
gpu-z                    2.58.0             2.59.0
imdisk                   2.1.1                                                      Manifest removed
joplin                   2.13.15                                                    Manifest removed
LivelyWallpaper-Portable 2.0.7.4                                                    Manifest removed
monitorian               4.3.0                                                      Manifest removed
python                   3.12.2             3.12.3
sudo                     0.2020.01.26                                               Manifest removed
sunshine                 0.23.0             0.23.1
temurin8-jre             8.0.402-6          8.0.412-8
UltimateWindowsTweaker   5.1                                                        Manifest removed
ungoogled-chromium       123.0.6312.105-1.1 123.0.6312.122-1.1
virtualbox               7.0.14                                                     Manifest removed
wireguard                0.5.3                                                      Manifest removed
wxmp3gain                4.0                                                        Manifest removed
```

**Comment by marticliment** [comment]
Please share logs of version 3.X

**Comment by unxpected-uxp** [comment]
Hm? Both the WingetUI and Packet Manager logs are already there for 3.0.0 (same result on 3.0.1 and 3.0.2) and 2.2.

**Comment by marticliment** [comment]
Sorry, I didn't see them. 

What happens when you run the command `where scoop` on a command prompt?

**Comment by unxpected-uxp** [comment]
C:\Users\uXp>where scoop
S:\shims\scoop
S:\shims\scoop.cmd

**Comment by marticliment** [comment]
How did you install scoop?

**Comment by name8102** [comment]
I have the same issue. I have changed the environment variable and installed scoop in a custom path.

**Comment by neoOpus** [comment]
same here, (fresh windows 11 23H2 installation)

**Comment by neoOpus** [comment]
Here is the log, just in case.
[WingetUI Log.txt](https://github.com/marticliment/WingetUI/files/15078076/WingetUI.Log.txt)

**Comment by Glomzzz** [comment]
same here, (fresh windows 11 23H2 installation), too
[WingetUI 日志.txt](https://github.com/marticliment/WingetUI/files/15145158/WingetUI.txt)

**Comment by Glomzzz** [comment]
> You have scoop added on user path or on system path?

sure, i did

**Comment by marticliment** [comment]
No, I was asking on which path do you have scoop, user OR system path

**Comment by neoOpus** [comment]
I fixed it but it tooks me several times uninstalling reinstalling scoop with different methods, I don't recollect which one who solved the issue but I still have a problem since I am transfering folders of scoop from the old OS, after forcing a reinstall in order to have their shortcuts created and everything as before, WingetUI show some version as Manifest. 
![image](https://github.com/marticliment/WingetUI/assets/1388336/d811adbe-93df-4cd9-a340-7965624cc62c)

**Comment by ipisano** [comment]
Same issue here, I installed Scoop directly from WinGetUI on a pretty fresh Windows installation, but it isn't recognized. I tried rebooting, adding Scoop to system path (it was already added to user path), I have no clue what to do to get it working. If I invoke scoop through any terminal window it works, it's just WinGetUI that doesn't recognize it.

![vivaldi_Io8FcNN0wz](https://github.com/marticliment/WingetUI/assets/18221957/559cbbdd-c0e4-4cee-98a6-c05fa471fbc7)

**Comment by neoOpus** [comment]
[**@ipisano**](https://github.com/ipisano) commented on [May 20, 2024, 1:14 PM EDT](https://github.com/marticliment/WingetUI/issues/2157#issuecomment-2120863030 "2024-05-20T17:14:46Z - Replied by Github Reply Comments"):
> Same issue here, I installed Scoop directly from WinGetUI on a pretty fresh Windows installation, but it isn't recognized. I tried rebooting, adding Scoop to system path (it was already added to user path), I have no clue what to do to get it working. If I invoke scoop through any terminal window it works, it's just WinGetUI that doesn't recognize it.
> 
> ![vivaldi_Io8FcNN0wz](https://github.com/marticliment/WingetUI/assets/18221957/559cbbdd-c0e4-4cee-98a6-c05fa471fbc7)
> 
> _Originally posted by @ipisano in https://github.com/marticliment/WingetUI/issues/2157#issuecomment-2120863030_

I partially fixed my problem by deleting the scoop folder inside the app scoop/apps then reinstalled it via WingetUI but it took several attempts in order to make it recognize scoop! Still this doesn't seem to be very reliable since when searching with apps it doesn't show those who are in scoop buckets but the updates somehow work!

**Comment by leic4u** [comment]
Same issue. I found it in v3.0.2.

No matter how I uninstall and reinstall it is not recognized.

I have given up using scoop in WingetUI.
