### ISSUE TITLE
[BUG] No winget updates shown in WingetUI

### ISSUE THREAD

**Issue by maicol07** [marticliment/WingetUI#2172]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Winget updates are available but they aren't shown in WingetUI

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.2
               Version Code 3,02
C:\Users\Maicol\AppData\Local\WingetUI\CachedLangFiles\lang_it.json
Loaded language locale: it
Api auth token: pvwetcpka2rfpcv5yfgm43e95qlp4b3uvm4o5j9qacez57t9igkvs3ehg7ac6y9w
Starting update check
Api running on http://localhost:7058
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at ModernWindow.Core.Data.LanguageEngine.UpdateLanguageFile(String LangKey) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\Core\Data\LanguageData.cs:line 104
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Downloaded icons and screenshots successfully!
WingetUI is up to date
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: True
█ Found: True
█ Fancye exe name: pip
█ Executable path: C:\Python311\python.exe
█ Call arguments:  -m pip
█ Version: 
█   pip 24.0 from C:\Python311\Lib\site-packages\pip (python 3.11)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Users\Maicol\AppData\Local\Microsoft\WindowsApps\winget.exe
█ Call arguments: 
█ Version: 
█   v1.8.924-preview
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: True
█ Found: True
█ Fancye exe name: npm
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
█ Version: 
█   9.8.0
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: True
█ Fancye exe name: choco.exe
█ Executable path: C:\Users\Maicol\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█ Call arguments: 
█ Version: 
█   2.2.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: True
█ Found: True
█ Fancye exe name: scoop
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
█ Version: 
█   Current Scoop version:
█   d285bb08 chore(release): Bump to version 0.4.1 (#5924)
█   
█   'main' bucket:
█   9952f90b6 supabase: Update to version 1.163.6
█   
█   'extras' bucket:
█   37c5fb542 ytdlp-interface: Update to version 2.11.1
█   
█   'versions' bucket:
█   189be6cbe okular-nightly: Update to version 4834
█   
█   'nirsoft' bucket:
█   08dbf0e 'updated'
█   
█   'nerd-fonts' bucket:
█   43346f7 Open-Sans: Fix url and license (#288)
█   
█   '.oki' bucket:
█   1dbc7c2 oh-my-posh_plus_themes: Update to version 19.24.3
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.26100.1                                                                             
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.26100.1                                                                            
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
```

### Package Managers Logs

```text
See attachment below
```

### Relevant information

[Package Managers Log.txt](https://github.com/marticliment/WingetUI/files/15131995/Package.Managers.Log.txt)

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/9463142/35d2e7b0-c841-41ae-a912-e2592e3f5583)

**Comment by marticliment** [comment]
Please see #1721 and let me know if the issue is the same

**Comment by maicol07** [comment]
> Please see #1721 and let me know if the issue is the same

I've tried to reset them but the packages to update still don't show up

**Comment by llvs** [comment]
Me too. And also cleaning in #1721 does not help. Neither does "reset sources" in WingetUI. Using Win10 and WingetUI 3.0.2.

**Comment by ds2-jetten** [comment]
Can confirm this bug as well and it has been happening since upgrading to Winget 3.0.  The interesting thing is that the updates appear just fine if I quit and re-open the program. No amount of refreshing will force the updates to appear.
