### ISSUE TITLE
[BUG] (WinGet encoding issue with umlauts in user paths - with fix)

### ISSUE THREAD

**Issue by DrPedale** [marticliment/WingetUI#2212]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Current behaviour:
![Screenshot 2024-05-14 204825](https://github.com/marticliment/WingetUI/assets/58781177/c73c9b31-eef9-475c-978d-24c95e75f50a)
Expected behaviour:
![Screenshot 2024-05-14 204908](https://github.com/marticliment/WingetUI/assets/58781177/e82d0dfd-876a-417e-bfff-d6da193524cc)

### Steps to reproduce the issue

Have special characters in the path to winget.exe and activate the option "Use system Winget"

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.2
               Version Code 3,02
C:\Users\Dönernik\AppData\Local\WingetUI\CachedLangFiles\lang_de.json
C:\Program Files\WingetUI\Assets\Languages\lang_de.json
Loaded language locale: de
Api auth token: xscjvfo3hvoed9kee2ctt68iyib4r07z4i6j9db6gvhn7w16xmtim5vpmky1lpy6
Starting update check
Api running on http://localhost:7058
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at ModernWindow.Core.Data.LanguageEngine.UpdateLanguageFile(String LangKey) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\Core\Data\LanguageData.cs:line 104
WingetUI is up to date
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: C:\Program Files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   8.0.104
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Downloaded icons and screenshots successfully!
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: True
█ Found: True
█ Fancye exe name: pip
█ Executable path: D:\Python39\python.exe
█ Call arguments:  -m pip
█ Version: 
█   pip 23.2.1 from D:\Python39\lib\site-packages\pip (python 3.9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: True
█ Found: True
█ Fancye exe name: npm
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
█ Version: 
█   6.13.4
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: True
█ Fancye exe name: choco.exe
█ Executable path: C:\Users\Dönernik\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█ Call arguments: 
█ Version: 
█   2.2.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.22621.2506                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.22621.2506                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Error finding installed packages on manager Npm: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
Error finding packages on manager Pip with query visual s: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\parse_pip_search' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Pip.FindPackages_UnSafe(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Pip.cs:line 39
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
Error finding packages on manager Pip with query visual st: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\parse_pip_search' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Pip.FindPackages_UnSafe(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Pip.cs:line 39
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
Error finding packages on manager Pip with query visual : 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\parse_pip_search' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Pip.FindPackages_UnSafe(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Pip.cs:line 39
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
Error finding packages on manager Pip with query visual s: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\parse_pip_search' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Pip.FindPackages_UnSafe(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Pip.cs:line 39
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
Error finding packages on manager Pip with query visual studio: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\parse_pip_search' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Pip.FindPackages_UnSafe(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Pip.cs:line 39
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
Error finding installed packages on manager Npm: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
Error finding packages on manager Pip with query .net: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\parse_pip_search' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Pip.FindPackages_UnSafe(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Pip.cs:line 39
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
Error finding installed packages on manager Chocolatey: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\Dönernik\AppData\Local\Programs\WingetUI\choco-cli\choco.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ModernWindow.PackageEngine.Managers.Chocolatey.GetInstalledPackages_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Chocolatey.cs:line 125
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
Error finding installed packages on manager Npm: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
Error finding installed packages on manager Chocolatey: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\Dönernik\AppData\Local\Programs\WingetUI\choco-cli\choco.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ModernWindow.PackageEngine.Managers.Chocolatey.GetInstalledPackages_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Chocolatey.cs:line 125
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
Error finding installed packages on manager Npm: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
Starting update check
WingetUI is up to date
Error finding updates on manager Chocolatey: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\Dönernik\AppData\Local\Programs\WingetUI\choco-cli\choco.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ModernWindow.PackageEngine.Managers.Chocolatey.GetAvailableUpdates_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Chocolatey.cs:line 80
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
Error finding installed packages on manager Chocolatey: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\Dönernik\AppData\Local\Programs\WingetUI\choco-cli\choco.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ModernWindow.PackageEngine.Managers.Chocolatey.GetInstalledPackages_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Chocolatey.cs:line 125
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
Error finding installed packages on manager Npm: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
```

### Package Managers Logs

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [14.05.2024 18:50:41] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\Dönernik\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[14.05.2024 18:50:41] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [14.05.2024 18:50:42] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[14.05.2024 18:50:42] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [14.05.2024 18:50:42] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\dotnet\dotnet.exe
█  Arguments: tool list --global
Package Id      Version      Commands
-------------------------------------
[14.05.2024 18:50:42] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [14.05.2024 18:50:43] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\Dönernik\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[14.05.2024 18:50:43] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [14.05.2024 18:50:43] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: D:\Python39\python.exe
█  Arguments:  -m pip list
Package                   Version
------------------------- ---------
comment too long
```

### Relevant information

Fixed by adding chcp to the arguments and utf8 encoding, like in the other managers.

Example code with implemented fix (Tools.cs Line168):

```
public async Task<string> Which(string command)
{
    Process process = new()
    {
        StartInfo = new ProcessStartInfo()
        {
            FileName = "cmd.exe",
            Arguments = "/C chcp 65001 > nul & where " + command, // chcp 65001 sets the code page to UTF-8
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
            StandardOutputEncoding = Encoding.UTF8
        }
    };
    process.Start();
```

### Screenshots and videos

![Screenshot 2024-05-14 205527](https://github.com/marticliment/WingetUI/assets/58781177/53c188b7-783d-4135-88b7-f832f56f0679)

**Comment by marticliment** [comment]
Will definitely fix
