### ISSUE TITLE
[BUG] version 3.1.0-alpha1 cannot use winget out-of the box and breaks it

### ISSUE THREAD

**Issue by EDM115** [marticliment/WingetUI#2286]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When launching UniGetUI v3.1.0-alpha1, no installed packages from winget will be listed.  
And if we keep UniGetUI open and open a terminal to do `winget list`, the command will run forever without ever succeeding.  
Closing UniGetUI, running `winget list` and reopening it fixes it for me

### Steps to reproduce the issue

1. Open UniGetUI
2. Try to list installed packages
3. Open a terminal and type `winget list`, notice that it hangs forever
4. Close UniGetUI, redo the command and then open UniGetUI again

### WingetUI Log

```text
[08/06/2024 09:27:07] 
                         __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.0-alpha1
[08/06/2024 09:27:08]
[08/06/2024 09:27:08] Version Code:  3,0991
[08/06/2024 09:27:08] Loaded language locale: en
[08/06/2024 09:27:08] Using bundled GSudo at D:\EDM115\Programmes\WingetUI\Assets\Utilities\gsudo.exe
[08/06/2024 09:27:09] Api auth token: tbgmec2hct1rxqmzhi6z4ntp87p61qplu11yhhogpg33emrxvje4eghty4vzak2h
[08/06/2024 09:27:10] Api running on http://localhost:7058
[08/06/2024 09:27:10] Begin "which" search for command winget.exe
[08/06/2024 09:27:10] Begin "which" search for command python.exe
[08/06/2024 09:27:10] Begin "which" search for command npm
[08/06/2024 09:27:10] Begin "which" search for command dotnet.exe
[08/06/2024 09:27:10] Lang files were updated successfully from GitHub
[08/06/2024 09:27:10] Downloaded new icons and screenshots successfully!
[08/06/2024 09:27:11] Begin "which" search for command scoop
[08/06/2024 09:27:11] Command npm was found on D:\EDM115\Programmes\nodejs\npm
[08/06/2024 09:27:11] Command python.exe was found on D:\EDM115\Programmes\Python312\python.exe
[08/06/2024 09:27:11] Command dotnet.exe was found on C:\Program Files\dotnet\dotnet.exe
[08/06/2024 09:27:11] Command winget.exe was found on C:\Users\EDM115\AppData\Local\Microsoft\WindowsApps\winget.exe
[08/06/2024 09:27:12] Command scoop was not found on the system
[08/06/2024 09:27:12] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/06/2024 09:27:12] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/06/2024 09:27:13] Loaded 1 sources for manager Winget
[08/06/2024 09:27:13] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\EDM115\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Naive WinGet CLI Version: v1.7.11261
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/06/2024 09:27:17] Loaded 1 sources for manager PowerShell
[08/06/2024 09:27:17] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: powershell.exe
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.3646                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.3646                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/06/2024 09:27:17] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: npm
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.8.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/06/2024 09:27:19] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   6.0.423
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/06/2024 09:27:21] System.TimeoutException: The operation has timed out.
                         at UniGetUI.MainApp.InitializeAllManagersAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\App.xaml.cs:line 316
[08/06/2024 09:27:21] Timeout: Not all package managers have finished initializing.
[08/06/2024 09:27:21] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[08/06/2024 09:27:28] Manager Npm has not implemented RefreshPackageIndexes
[08/06/2024 09:27:28] Manager .NET Tool has not implemented RefreshPackageIndexes
[08/06/2024 09:27:28] Begin "which" search for command dotnet-tools-outdated.exe
[08/06/2024 09:27:28] Manager PowerShell has not implemented RefreshPackageIndexes
[08/06/2024 09:27:28] Loaded 1 sources for manager Winget
[08/06/2024 09:27:32] Command dotnet-tools-outdated.exe was not found on the system
[08/06/2024 09:27:32] Error finding updates on manager .NET Tool
[08/06/2024 09:27:32] System.InvalidOperationException: Cannot start process because a file name has not been provided.
                         at System.Diagnostics.Process.Start()
                         at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 65
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 177
[08/06/2024 09:27:33] Found 0 installed packages from .NET Tool
[08/06/2024 09:27:33] Loaded 1 sources for manager PowerShell
[08/06/2024 09:27:36] Found 5 installed packages from PowerShell
[08/06/2024 09:27:38] Found 0 available updates from PowerShell
[08/06/2024 09:27:40] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: pip
                      █ Executable path: D:\EDM115\Programmes\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.0 from D:\EDM115\Programmes\Python312\Lib\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/06/2024 09:27:56] Found 2 installed packages from Npm
[08/06/2024 09:27:58] Found 0 available updates from Npm
[08/06/2024 09:28:28] Error finding updates on manager Winget
[08/06/2024 09:28:28] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 176
[08/06/2024 09:28:28] Error finding installed packages on manager Winget
[08/06/2024 09:28:28] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 201
[08/06/2024 09:32:17] Found 0 installed packages from .NET Tool
[08/06/2024 09:32:22] Found 2 installed packages from Npm
[08/06/2024 09:32:23] Found 5 installed packages from PowerShell
[08/06/2024 09:32:39] Found 216 installed packages from Pip
[08/06/2024 09:33:16] Error finding installed packages on manager Winget
[08/06/2024 09:33:16] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 201
```

### Package Managers Logs

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:27:17] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[08/06/2024 09:27:17] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:27:33] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\dotnet\dotnet.exe
█  Arguments: tool list --global
ID de package      Version      Commandes
-----------------------------------------
[08/06/2024 09:27:33] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:27:33] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[08/06/2024 09:27:33] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:27:36] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-InstalledModule
Version              Name                                Repository           Description                              
-------              ----                                ----------           -----------                              
1.4.8.1              PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a...
1.1.0                posh-git                            PSGallery            Provides prompt with Git status summar...
2.2.5                PowerShellGet                       PSGallery            PowerShell module with commands for di...
2.3.5                PSReadLine                          PSGallery            Great command line editing in the Powe...
1.8.1133             Microsoft.WinGet.Client             PSGallery            PowerShell Module for the Windows Pack...
[08/06/2024 09:27:36] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:27:38] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: 
Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.
Installez la dernière version de PowerShell pour de nouvelles fonctionnalités et améliorations ! https://aka.ms/PSWindows
PS D:\EDM115\Programmes\WingetUI> 
PS D:\EDM115\Programmes\WingetUI>                 function Test-GalleryModuleUpdate {
>>                     param (
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Name,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [version] $Version,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Repository,
>>                         [switch] $NeedUpdateOnly
>>                     )
>>                     process {
>>                         $URLs = @{}
>>                         @(Get-PSRepository).ForEach({$URLs[$_.Name] = $_.SourceLocation})
>>                         $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$Name") -UseBasicParsing -Maximum 0 -ea Ignore
>>                         [version]$latest = Split-Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupkg") -Leaf
>>                         $needsupdate = $Latest -gt $Version
>>                         if ($needsupdate) {
>>                                 Write-Output($Name + "|" + $Version.ToString() + "|" + $Latest.ToString() + "|" + $Repository)
>>                         }
>>                     }
>>                 }
>>                 Get-InstalledModule | Test-GalleryModuleUpdate
PS D:\EDM115\Programmes\WingetUI>                 exit
[08/06/2024 09:27:38] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:27:52] Npm ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm outdated --parseable
[08/06/2024 09:27:52] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:27:52] Npm ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm list
C:\Users\EDM115
`-- (empty)
[08/06/2024 09:27:52] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:27:56] Npm ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm list --global
D:\EDM115\Programmes\nodejs
+-- corepack@0.28.2
`-- npm@10.8.1
[08/06/2024 09:27:56] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:27:58] Npm ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm outdated --parseable --global
[08/06/2024 09:27:58] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:32:17] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\dotnet\dotnet.exe
█  Arguments: tool list --global
ID de package      Version      Commandes
-----------------------------------------
[08/06/2024 09:32:17] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:32:19] Npm ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm list
C:\Users\EDM115
`-- (empty)
[08/06/2024 09:32:19] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:32:22] Npm ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm list --global
D:\EDM115\Programmes\nodejs
+-- corepack@0.28.2
`-- npm@10.8.1
[08/06/2024 09:32:22] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:32:23] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-InstalledModule
Version              Name                                Repository           Description                              
-------              ----                                ----------           -----------                              
1.4.8.1              PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a...
1.1.0                posh-git                            PSGallery            Provides prompt with Git status summar...
2.2.5                PowerShellGet                       PSGallery            PowerShell module with commands for di...
2.3.5                PSReadLine                          PSGallery            Great command line editing in the Powe...
1.8.1133             Microsoft.WinGet.Client             PSGallery            PowerShell Module for the Windows Pack...
[08/06/2024 09:32:23] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [08/06/2024 09:32:39] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: D:\EDM115\Programmes\Python312\python.exe
█  Arguments:  -m pip list
Package                   Version
------------------------- --------------
aiofiles                  23.2.1
aiohttp                   3.9.5
aiosignal                 1.3.1
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.2.0
Babel                     2.15.0
base58check               1.0.2
beautifulsoup4            4.12.3
black                     24.4.2
bleach                    6.1.0
blinker                   1.8.2
build                     1.2.1
certifi                   2024.6.2
cffi                      1.16.0
cftime                    1.6.4
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
cmake                     3.29.3
colorama                  0.4.6
comm                      0.2.2
construct                 2.10.70
construct-typing          0.6.2
contourpy                 1.2.1
cryptography              42.0.8
cycler                    0.12.1
dask                      2024.5.2
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
dnspython                 2.6.1
docutils                  0.21.2
executing                 2.0.1
fastjsonschema            2.19.1
filelock                  3.14.0
Flask                     3.0.3
fonttools                 4.53.0
fqdn                      1.5.1
frozenlist                1.4.1
fsspec                    2024.6.0
geographiclib             2.0
geopy                     2.4.1
gitdb                     4.0.11
GitPython                 3.1.43
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.0
idna                      3.7
importlib_metadata        7.1.0
iniconfig                 2.0.0
intel-openmp              2021.4.0
ipykernel                 6.29.4
ipympl                    0.9.4
ipython                   8.25.0
ipython-genutils          0.2.0
ipywidgets                8.1.3
isoduration               20.11.0
itsdangerous              2.2.0
jaraco.classes            3.4.0
jaraco.context            5.3.0
jaraco.functools          4.0.1
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               2.4
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter                   1.0.0
jupyter_client            8.6.2
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.1
jupyter_server_terminals  0.5.3
jupyterlab                4.2.1
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.2
jupyterlab_widgets        3.0.11
keyring                   25.2.1
kiwisolver                1.4.5
locket                    1.0.0
lxml                      5.2.2
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.0
matplotlib-inline         0.1.7
mdurl                     0.1.2
mistune                   3.0.2
mkl                       2021.4.0
more-itertools            10.2.0
motor                     3.4.0
mpmath                    1.3.0
multidict                 6.0.5
mutagen                   1.47.0
mypy-extensions           1.0.0
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
netCDF4                   1.6.5
networkx                  3.3
nh3                       0.2.17
notebook                  7.2.0
notebook_shim             0.2.4
numpy                     1.26.4
oauthlib                  3.2.2
overrides                 7.7.0
packaging                 24.0
pandas                    2.2.2
pandocfilters             1.5.1
parso                     0.8.4
partd                     1.4.2
pathspec                  0.12.1
pillow                    10.3.0
pip                       24.0
pkginfo                   1.11.0
platformdirs              4.2.2
pluggy                    1.5.0
portalocker               2.8.2
prometheus_client         0.20.0
prompt_toolkit            3.0.46
psutil                    5.9.8
pure-eval                 0.2.2
pyaes                     1.6.1
pycosat                   0.6.6
pycparser                 2.22
pyflp                     2.2.1
pygame                    2.5.2
Pygments                  2.18.0
pykeyboard                0.1.5
pymongo                   4.7.3
pyparsing                 3.1.2
pyproject_hooks           1.1.0
Pyrogram                  2.0.106
pyromod                   1.5
PySocks                   1.7.1
pyte                      0.8.2
pytest                    8.2.2
PyTgCrypto                1.2.7
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-json-logger        2.0.7
python-pptx               0.6.23
python-sat                1.8.dev13
python3-openid            3.2.0
pytz                      2024.1
pywin32                   306
pywin32-ctypes            0.2.2
pywinpty                  2.0.13
PyYAML                    6.0.1
pyzmq                     26.0.3
qtconsole                 5.5.2
QtPy                      2.4.1
readme_renderer           43.0
referencing               0.35.1
requests                  2.32.3
requests-oauthlib         2.0.0
requests-toolbelt         1.0.0
rfc3339-validator         0.1.4
rfc3986                   2.0.0
rfc3986-validator         0.1.1
rich                      13.7.1
rpds-py                   0.18.1
scikit-learn              1.5.0
scipy                     1.13.1
seaborn                   0.13.2
Send2Trash                1.8.3
setuptools                70.0.0
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.5
sqlparse                  0.5.0
stack-data                0.6.3
sympy                     1.12.1
tbb                       2021.12.0
terminado                 0.18.1
TgCrypto                  1.2.5
thefuck                   3.32
threadpoolctl             3.5.0
tinycss2                  1.3.0
toolz                     0.12.1
torch                     2.3.0
torchvision               0.18.0
tornado                   6.4.1
traitlets                 5.14.3
twine                     5.1.0
types-python-dateutil     2.9.0.20240316
typing_extensions         4.12.1
tzdata                    2024.1
unzip-http                0.4
uri-template              1.3.0
urllib3                   2.2.1
voila                     0.5.7
watchdog                  4.0.1
wcwidth                   0.2.13
webcolors                 24.6.0
webencodings              0.5.1
websocket-client          1.8.0
websockets                12.0
Werkzeug                  3.0.3
wheel                     0.43.0
widgetsnbextension        4.0.11
win_unicode_console       0.5
xarray                    2024.5.0
XlsxWriter                3.2.0
yarl                      1.9.4
zipp                      3.19.2
[08/06/2024 09:32:39] Exit Code: 0
```

### Screenshots and videos

https://drive.google.com/file/d/1ttl5FpwvaBux19PkQ3UI4sW4n4aOTJ0L/view?usp=drive_link

**Comment by EDM115** [comment]
i can't provide logs atm, seems not happening if i restart directly  
however it's the second time i face this issue, only after upgrading to 3.1.0-alpha1  
i will wait 2/3 days to see if with an empty cache or smth it changes something :(

**Comment by marticliment** [comment]
I will investigate this. I have actually experienced this issue a few times myself, I will try to understand what is happening and fix it

**Comment by grimson73** [comment]
I can't reproduce but I use this version of Winget:
PS C:\Users\grims> winget -v
v1.9.1551-preview

**Comment by EDM115** [comment]
winget `v1.7.11261` here

**Comment by EDM115** [comment]
@marticliment I added logs, hope it can help you :)

**Comment by marticliment** [comment]
Latest commit seems to have fixed this issue for me.

Please wait for the next release and check if the issue gets fixed for you
