### ISSUE TITLE
[BUG] Anaconda.Miniconda3 is detected for update but fails to update

### ISSUE THREAD

**Issue by coinzdude** [marticliment/WingetUI#2296]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I have all package managers enabled for wingetUI

This might be the actual bug, I am not sure. Anaconda.Miniconda3 is identified as installed with winget. 

![image](https://github.com/marticliment/WingetUI/assets/58857646/2dfecabe-04da-4545-9be3-204c145927ff)

The winget upgrade script indicates failure as below

```
Starting package update operation for package id=Anaconda.Miniconda3with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=X64;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Users\Admin\AppData\Local\Programs\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
Process Call Arguments :  update --id Anaconda.Miniconda3 --exact --accept-source-agreements --silent --disable-interactivity --accept-package-agreements --architecture x64 --force --include-unknown
Working Directory      : C:\Users\Admin
    |    \ 
    |   ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 11.0 MB
    |   █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 11.0 MB
    |   ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 11.0 MB
    |   ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 11.0 MB
    |   █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 11.0 MB
    |   ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 11.0 MB
    |   ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 11.0 MB
    |   █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 11.0 MB
    |   ████████████████████████▒▒▒▒▒▒  9.00 MB / 11.0 MB
    |   ███████████████████████████▒▒▒  10.0 MB / 11.0 MB
    |   █████████████████████████████▒  11.0 MB / 11.0 MB
    |    | 
    | The package cannot be upgraded using winget. Please use the method provided by the publisher for upgrading this package.
Process Exit Code      : -1978334956
Process End Time       : 6/10/2024 11:43:10 AM
```

I am able to update with anaconda prompt with
```
conda update conda
```

### Steps to reproduce the issue

With wingetUI, check for updates.

Miniconda3 shows as upgradable with winget as the package manager and fails with the provided error on upgrade

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.2
               Version Code 3.02
C:\Users\Admin\AppData\Local\WingetUI\CachedLangFiles\lang_en.json
C:\Users\Admin\AppData\Local\Programs\WingetUI\Assets\Languages\lang_en.json
Loaded language locale: en
Api auth token: oo3ipt65yn91ibd3x89yz902iis2i9leazf6sp23g8vfa3ci7t3fg097bx1318xb
Starting update check
Api running on http://localhost:7058
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at ModernWindow.Core.Data.LanguageEngine.UpdateLanguageFile(String LangKey) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\Core\Data\LanguageData.cs:line 104
WingetUI is up to date
Downloaded icons and screenshots successfully!
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: C:\Program Files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   8.0.301
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: True
█ Found: True
█ Fancye exe name: pip
█ Executable path: C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe
█ Call arguments:  -m pip
█ Version: 
█   pip 24.0 from C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: True
█ Found: True
█ Fancye exe name: npm
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
█ Version: 
█   10.2.4
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Users\Admin\AppData\Local\Programs\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█ Call arguments: 
█ Version: 
█   v1.7.10582
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.22621.3672                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.22621.3672                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Users\Admin\AppData\Local\Programs\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Error finding installed packages on manager Npm: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
Unknown PowerShell source!
Error finding installed packages on manager Npm: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModernWindow.PackageEngine.Managers.Npm.GetInstalledPackages_UnSafe()
   at ModernWindow.PackageEngine.Classes.PackageManager.GetInstalledPackages() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 192
```

### Package Managers Logs

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:34:59 AM] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\Admin\AppData\Local\Programs\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[6/10/2024 11:34:59 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:01 AM] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[6/10/2024 11:35:01 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:01 AM] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\Admin\AppData\Local\Programs\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[6/10/2024 11:35:01 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:02 AM] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\dotnet\dotnet.exe
█  Arguments: tool list --global
Package Id             Version         Commands         
--------------------------------------------------------
csharpier              0.28.1          dotnet-csharpier 
cyclonedx              2.7.0           dotnet-CycloneDX 
dotnet-ef              6.0.4           dotnet-ef        
upgrade-assistant      0.3.252501      upgrade-assistant
[6/10/2024 11:35:02 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:03 AM] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe
█  Arguments:  -m pip list
Package            Version
------------------ --------
certifi            2024.6.2
charset-normalizer 3.3.2
idna               3.7
pip                24.0
requests           2.32.3
setuptools         70.0.0
urllib3            2.2.1
[6/10/2024 11:35:03 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:04 AM] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe
█  Arguments:  -m pip list --outdated
[6/10/2024 11:35:04 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:04 AM] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[6/10/2024 11:35:04 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:06 AM] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-InstalledModule
Version              Name                                Repository           Description                              
-------              ----                                ----------           -----------                              

REMOVED

[6/10/2024 11:35:06 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:06 AM] Npm ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm outdated --global --parseable
[6/10/2024 11:35:06 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:07 AM] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\Admin\AppData\Local\Programs\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  update --include-unknown  --accept-source-agreements
   \ 
  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 11.0 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 11.0 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 11.0 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 11.0 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 11.0 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 11.0 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 11.0 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 11.0 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 11.0 MB
  ███████████████████████████▒▒▒  10.0 MB / 11.0 MB
  █████████████████████████████▒  11.0 MB / 11.0 MB
  ██████████████████████████████  11.0 MB / 11.0 MB
   - 
   | 
   - 
Name                            Id                                Version              Available            Source
------------------------------------------------------------------------------------------------------------------
REMOVED

MSI Kombustor 4.1.27.0 (64-bit) MSI.Kombustor.4                   Unknown              4.1.27.0             winget
14 upgrades available.
The following packages have an upgrade available, but require explicit targeting for upgrade:
Name                                             Id                  Version        Available      Source
---------------------------------------------------------------------------------------------------------
Miniconda3 py312_24.1.2-0 (Python 3.12.1 64-bit) Anaconda.Miniconda3 py312_24.1.2-0 py312_24.4.0-0 winget
[6/10/2024 11:35:07 AM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 11:35:08 AM] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\Admin\AppData\Local\Programs\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  list  --accept-source-agreements
   \ 
   / 
  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 11.0 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 11.0 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 11.0 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 11.0 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 11.0 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 11.0 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 11.0 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 11.0 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 11.0 MB
  ███████████████████████████▒▒▒  10.0 MB / 11.0 MB
  █████████████████████████████▒  11.0 MB / 11.0 MB
  ██████████████████████████████  11.0 MB / 11.0 MB
   - 
   | 
Name                                     Id                                             Version        Available Source
-----------------------------------------------------------------------------------------------------------------------

REMOVED

sending SMS messag...
[6/10/2024 12:12:57 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [6/10/2024 12:12:59 PM] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\Admin\AppData\Local\Programs\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  list  --accept-source-agreements
   \ 
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 5.65 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 5.65 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 5.65 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  4.00 MB / 5.65 MB
  ██████████████████████████▒▒▒▒  5.00 MB / 5.65 MB
  ██████████████████████████████  5.65 MB / 5.65 MB
  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 11.0 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 11.0 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 11.0 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 11.0 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 11.0 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 11.0 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 11.0 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 11.0 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 11.0 MB
  ███████████████████████████▒▒▒  10.0 MB / 11.0 MB
  █████████████████████████████▒  11.0 MB / 11.0 MB
  ██████████████████████████████  11.0 MB / 11.0 MB
   - 
   | 
Name                                     Id                                             Version        Available Source
-----------------------------------------------------------------------------------------------------------------------

REMOVED
             
Miniconda3 py312_24.1.2-0 (Python 3.12.… Anaconda.Miniconda3                            py312_24.1.2-0 py312_24… winget

REMOVED

[6/10/2024 12:12:59 PM] Exit Code: 0
```

### Relevant information

Looking at the WingetUI Log, doesn't look too healthy. Should I try a re-install of wingetUI?

**Comment by marticliment** [comment]
Is WinGet able to update MiniConda without issues from a CLI?

**Comment by coinzdude** [comment]
from CLI I do get the same "The package cannot be upgraded using winget. Please use the method provided by the publisher for upgrading this package." I am wondering if it's a problem since knowing the package manager origin is difficult (impossible?) 

I'm actually not certain how I originally installed Anaconda.Miniconda3 and it may not have been through winget. I can try removing it and installing with winget.

**Comment by marticliment** [comment]
I am afraid I cannot help with this. This is an issue with the package, and ultimately with WinGet.

Please contact the Anaconda Maintainers to report this issue and ask for how to handle the situation

**Comment by MrMxyzptlk** [comment]
Yep, same issue here on all my machines. Everything updates fine in UniGetUI except for Miniconda3

**Comment by MrMxyzptlk** [comment]
It appears the only issue is that Miniconda needs to be uninstalled before installing the new version. Can you add this as an option in UniGetUI or for the Miniconda package?
