### ISSUE TITLE
[BUG] Why is this error shown?

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#2345]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### UniGetUI Version

3.1.0-beta0

### Windows version, edition and architecture

Windows 11 Pro 10.22621.3737

### Describe your issue

There is an error shown in UniGetUI.

### Steps to reproduce the issue

Go to settings I guess.

### WingetUI Log

```text
[26-06-2024 11:54:31] 
                         __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.0-beta0
[26-06-2024 11:54:31]
[26-06-2024 11:54:31] Version Code:  3.0992
[26-06-2024 11:54:32] Using bundled GSudo at A:\WingetUI\Assets\Utilities\gsudo.exe
[26-06-2024 11:54:32] LoadLanguageFile Failed for LangKey=en_GB, ForceBundled=True
[26-06-2024 11:54:32] System.IO.FileNotFoundException: Could not find file 'A:\WingetUI\Assets\Languages\lang_en_GB.json'.
                      File name: 'A:\WingetUI\Assets\Languages\lang_en_GB.json'
                         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
                         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                         at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                         at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
                         at System.IO.File.ReadAllText(String path, Encoding encoding)
                         at UniGetUI.Core.Language.LanguageEngine.LoadLanguageFile(String LangKey, Boolean ForceBundled) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.LanguageEngine\LanguageEngine.cs:line 66
[26-06-2024 11:54:32] Loaded language locale: en
[26-06-2024 11:54:33] Api auth token: iqh1i9sr9a752mi8eslb74w24nrsu0zsz1cwttlmvi363g7jy6bw1vaxdiehvczb
[26-06-2024 11:54:34] Api running on http://localhost:7058
[26-06-2024 11:54:34] Moving Bundled Chocolatey from old path to new path...
[26-06-2024 11:54:34] Deleting old Chocolatey directory C:\Users\Skand_zncmqfh\AppData\Local\Programs\WingetUI\choco-cli
[26-06-2024 11:54:42] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: npm
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.8.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[26-06-2024 11:54:42] UniGetUI is up to date
[26-06-2024 11:54:42] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: dotnet tool
                      █ Executable path: C:\Program Files (x86)\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[26-06-2024 11:54:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: pip
                      █ Executable path: C:\Users\Skand_zncmqfh\AppData\Local\Programs\Python\Python313\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.0 from C:\Users\Skand_zncmqfh\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip (python 3.13)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[26-06-2024 11:54:49] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.PEInterface.Initialize() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageEngine\PEInterface.cs:line 44
[26-06-2024 11:54:49] Timeout: Not all package managers have finished initializing.
[26-06-2024 11:54:50] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[26-06-2024 11:54:52] PowerShell sources took too long to load, using known sources as default
[26-06-2024 11:54:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.3672                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.3672                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[26-06-2024 11:54:58] Chocolatey sources took too long to load, using known sources as default
[26-06-2024 11:54:58] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: choco.exe
                      █ Executable path: C:\Users\Skand_zncmqfh\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[26-06-2024 11:54:58] Command dotnet-tools-outdated.exe was not found on the system
[26-06-2024 11:55:13] Error finding updates on manager .NET Tool
[26-06-2024 11:55:14] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet-tools-outdated.exe' with working directory 'A:\WingetUI'. The system cannot find the file specified.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 90
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
[26-06-2024 11:55:15] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: scoop
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[26-06-2024 11:55:15] Found 4 installed packages from Chocolatey
[26-06-2024 11:55:15] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\Skand_zncmqfh\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Naive WinGet CLI Version: v1.7.11261
                      █   Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
                      █   -----  -----  -----  --------
                      █   1      8      1133   -1
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[26-06-2024 11:55:15] Found 0 installed packages from .NET Tool
[26-06-2024 11:55:15] Found 1 installed packages from PowerShell
[26-06-2024 11:55:15] Found 0 available updates from PowerShell
[26-06-2024 11:55:15] Found 1 installed packages from Pip
[26-06-2024 11:55:49] Error finding updates on manager Chocolatey
[26-06-2024 11:55:49] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
[26-06-2024 11:55:49] Error finding updates on manager Npm
[26-06-2024 11:55:49] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
[26-06-2024 11:55:49] Error finding updates on manager Pip
[26-06-2024 11:55:49] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
[26-06-2024 11:55:50] Error finding installed packages on manager Npm
[26-06-2024 11:55:50] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 204
[26-06-2024 11:56:13] Failed to download icons and screenshots
[26-06-2024 11:56:13] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
                       ---> System.TimeoutException: The operation was canceled.
                       ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
                       ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
                       ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
                         --- End of inner exception stack trace ---
                         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
                         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
                         at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
                         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
                         at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
                         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
                         at System.Net.Http.HttpConnection.FillAsync(Boolean async)
                         at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
                         at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
                         --- End of inner exception stack trace ---
                         at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
                         at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
                         at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                         --- End of inner exception stack trace ---
                         --- End of inner exception stack trace ---
                         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
                         at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                         at UniGetUI.Core.IconEngine.IconDatabase.LoadIconAndScreenshotsDatabaseAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconDatabase.cs:line 71
[26-06-2024 11:56:31] Could not load announcements
[26-06-2024 11:56:31] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
                       ---> System.TimeoutException: A task was canceled.
                       ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
                         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
                         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
                         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                         at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
                         --- End of inner exception stack trace ---
                         --- End of inner exception stack trace ---
                         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
                         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
                         at UniGetUI.Interface.Widgets.Announcer.LoadAnnouncements(Boolean retry) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\Widgets\Announcer.xaml.cs:line 56
[26-06-2024 12:03:57] Found 0 installed packages from .NET Tool
[26-06-2024 12:03:58] Found 1 installed packages from Pip
[26-06-2024 12:03:58] Found 4 installed packages from Chocolatey
[26-06-2024 12:04:02] Found 1 installed packages from PowerShell
[26-06-2024 12:04:03] Found 0 installed packages from Scoop
[26-06-2024 12:04:04] Found 3 installed packages from Npm
[26-06-2024 12:04:14] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=snyk
[26-06-2024 12:04:49] Error finding installed packages on manager Winget
[26-06-2024 12:04:49] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 204
[26-06-2024 12:05:52] Command dotnet-tools-outdated.exe was not found on the system
[26-06-2024 12:06:00] Found 0 installed packages from Scoop
[26-06-2024 12:06:01] Found 0 available updates from Scoop
[26-06-2024 12:06:03] Error finding updates on manager .NET Tool
[26-06-2024 12:06:03] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet-tools-outdated.exe' with working directory 'A:\WingetUI'. The system cannot find the file specified.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at System.Diagnostics.Process.Start()
                         at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 90
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
[26-06-2024 12:06:05] An error occurred while retrieving the icon for package snyk
[26-06-2024 12:06:05] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
                       ---> System.TimeoutException: A task was canceled.
                       ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
                         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
                         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
                         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                         at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
                         --- End of inner exception stack trace ---
                         --- End of inner exception stack trace ---
                         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
                         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
                         at UniGetUI.Core.IconEngine.IconCacheEngine.DownloadIconOrCache(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 153
                         at UniGetUI.PackageEngine.PackageClasses.Package.GetIconUrl() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 191
[26-06-2024 12:06:19] Found 1 available updates from Pip
[26-06-2024 12:06:58] Error finding updates on manager PowerShell
[26-06-2024 12:06:58] Error finding updates on manager Chocolatey
[26-06-2024 12:06:58] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
[26-06-2024 12:06:58] Error finding updates on manager Winget
[26-06-2024 12:06:58] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 179
[26-06-2024 12:06:58] Error finding updates on manager Npm
[26-06-2024 12:06:58] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.7.11261
Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1133   -1
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 26-06-2024 11:55:15
Process end time:   26-06-2024 11:55:15

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 26-06-2024 12:03:49
Process end time:   26-06-2024 12:07:07

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Skand_zncmqfh\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 26-06-2024 12:05:50
Process end time:   UNFINISHED

Return code: Process has not finished yet

——————————————————————————————————————————
```

### Relevant information

I don't know what I did to get this issue. Or maybe it is this fact this I don't have internet I guess.

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/99239826/4e680d25-b446-44fa-a8e9-3db5f3a7a4b5)

**Comment by marticliment** [comment]
> Or maybe it is this fact this I don't have internet I guess.

Perhaps it is this. This error seems to have been thrown by a failed internet request
