### ISSUE TITLE
[BUG] Only Choco packages are available in "Installed Packages" page.

### ISSUE THREAD

**Issue by sidsharths1245** [marticliment/WingetUI#2362]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0-Beta0

### Windows version, edition and architecture

Windows 11 pro 23H2

### Describe your issue

Only choco packages are available in the "Installed Packages" page. I don't see Winget or system packages.

### UniGetUI Log

```text
[30-06-2024 00:37:42] 
                         __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.0-beta0
[30-06-2024 00:37:42]
[30-06-2024 00:37:42] Version Code:  3.0992
[30-06-2024 00:37:42] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[30-06-2024 00:37:42] LoadLanguageFile Failed for LangKey=en_GB, ForceBundled=True
[30-06-2024 00:37:42] System.IO.FileNotFoundException: Could not find file 'C:\Program Files\WingetUI\Assets\Languages\lang_en_GB.json'.
                      File name: 'C:\Program Files\WingetUI\Assets\Languages\lang_en_GB.json'
                         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
                         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                         at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                         at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
                         at System.IO.File.ReadAllText(String path, Encoding encoding)
                         at UniGetUI.Core.Language.LanguageEngine.LoadLanguageFile(String LangKey, Boolean ForceBundled) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.LanguageEngine\LanguageEngine.cs:line 66
[30-06-2024 00:37:42] Loaded language locale: en
[30-06-2024 00:37:42] Api auth token: p7e8fg94v933c6cx44gi6fxoppox3wspmkyojg83okvotg3q02jw7xbgvkly9kt7
[30-06-2024 00:37:42] Api running on http://localhost:7058
[30-06-2024 00:37:43] Downloaded new icons and screenshots successfully!
[30-06-2024 00:37:43] Command npm was not found on the system
[30-06-2024 00:37:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30-06-2024 00:37:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30-06-2024 00:37:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30-06-2024 00:37:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30-06-2024 00:37:43] Command scoop was not found on the system
[30-06-2024 00:37:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30-06-2024 00:37:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: choco.exe
                      █ Executable path: C:\Users\Siddharth\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30-06-2024 00:37:44] WinGet STDERR not empty: PackageManagement\Get-Package : No match was found for the specified search criteria and module names 
                      'Microsoft.WinGet.Client'.
                      At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2253 char:9
                      +         PackageManagement\Get-Package @PSBoundParameters | Microsoft. ...
                      +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          + CategoryInfo          : ObjectNotFound: (Microsoft.Power...lets.GetPackage:GetPackage) [Get-Package], Exception
                          + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage
                       

[30-06-2024 00:37:44] UniGetUI is up to date
[30-06-2024 00:37:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\Siddharth\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Naive WinGet CLI Version: v1.8.1791
                      █   Microsoft.WinGet.Client PSModule version: 
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30-06-2024 00:37:44] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[30-06-2024 00:37:44] Found 0 installed packages from Winget
[30-06-2024 00:37:45] Found 0 available updates from Winget
[30-06-2024 00:37:45] Found 13 installed packages from Chocolatey
[30-06-2024 00:37:45] Found 0 available updates from Chocolatey
[30-06-2024 00:37:51] Found 0 installed packages from Winget
[30-06-2024 00:37:51] Found 13 installed packages from Chocolatey
[30-06-2024 00:41:02] Uninstall
[30-06-2024 00:41:02] Found 0 screenshots for package Id=smartsystemmenu
[30-06-2024 00:41:03] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=smartsystemmenu
[30-06-2024 00:41:04] Icon for package smartsystemmenu stored on C:\Users\Siddharth\AppData\Local\UniGetUI\CachedMedia\Chocolatey\smartsystemmenu.png
[30-06-2024 00:41:04] Could not load file size for url=https://community.chocolatey.org/api/v2//Packages/smartsystemmenu.2.25.1.nupkg
[30-06-2024 00:41:04] System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
                         at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
                      --- End of stack trace from previous location ---
                         at System.Net.WebRequest.GetResponseAsync()
                         at UniGetUI.Core.Tools.CoreTools.GetFileSizeAsyncAsLong(Uri url) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Tools\Tools.cs:line 250
[30-06-2024 00:41:04] Loaded details for package smartsystemmenu on manager Chocolatey
[30-06-2024 00:41:48] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=smartsystemmenu
[30-06-2024 00:41:48] Icon for package smartsystemmenu stored on C:\Users\Siddharth\AppData\Local\UniGetUI\CachedMedia\Chocolatey\smartsystemmenu.png
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 30-06-2024 00:37:44
Process end time:   30-06-2024 00:37:44

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Siddharth\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 30-06-2024 00:37:44
Process end time:   30-06-2024 00:37:44

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 30-06-2024 00:37:44
Process end time:   30-06-2024 00:37:44

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : The term 'Get-WinGetPackage' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 30-06-2024 00:37:44
Process end time:   30-06-2024 00:37:44

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 30-06-2024 00:37:44
Process end time:   30-06-2024 00:37:45

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : The term 'Get-WinGetPackage' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 30-06-2024 00:37:50
Process end time:   30-06-2024 00:37:51

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : The term 'Get-WinGetPackage' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/64619769/59017918-f685-4fce-a191-84c80571b7fa)

**Comment by marticliment** [comment]
please run on a powershell window

```
Install-Module Microsoft.WinGet.Client
```

**Comment by sidsharths1245** [comment]
That fixed it. Thanks!!
