### ISSUE TITLE
[BUG] After the manual update, the Installed Packages is empty

### ISSUE THREAD

**Issue by deltapapa01** [marticliment/WingetUI#2365]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0-beta0

### Windows version, edition and architecture

Windows 11 23H2

### Describe your issue

I had the problem that I could not directly update UnigetUI 3.1.0 Alpha1 to Beta0:

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Starting package update operation for package id=SomePythonThings.WingetUIStore.Pre-release with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Users\delta\AppData\Local\Microsoft\WindowsApps\winget.exe
Process Call Arguments :  update --id SomePythonThings.WingetUIStore.Pre-release --exact --source winget --accept-source-agreements --silent --disable-interactivity  --accept-package-agreements --force --include-unknown
Working Directory      : C:\Users\delta
    ║    - 
    ║ Es wurde kein anwendbares Upgrade gefunden.
    ║ In einer konfigurierten Quelle ist eine neuere Paketversion verfügbar, die jedoch nicht auf Ihr System oder Ihre Anforderungen zutrifft.
Process Exit Code      : -1978335189
Process End Time       : 30.06.2024 08:48:41
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

So I did the update to version UnigetUi 3.1.0 Beta0 manually (I downloaded it directly from Github and installed it over it)
After the update to Beta0, however, the list of installed packages is empty. However, the command in the CMS with Winget list returns all the installed programs. 
In addition, the German language does not work

What can i do, that UniGetUi list all packages and update ist correctly?

### UniGetUI Log

```text
[30.06.2024 09:00:28] 
                         __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.0-beta0
[30.06.2024 09:00:28]
[30.06.2024 09:00:28] Version Code:  3,0992
[30.06.2024 09:00:28] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[30.06.2024 09:00:28] LoadLanguageFile Failed for LangKey=de_DE, ForceBundled=True
[30.06.2024 09:00:28] System.IO.FileNotFoundException: Could not find file 'C:\Program Files\UniGetUI\Assets\Languages\lang_de_DE.json'.
                      File name: 'C:\Program Files\UniGetUI\Assets\Languages\lang_de_DE.json'
                         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
                         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                         at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                         at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
                         at System.IO.File.ReadAllText(String path, Encoding encoding)
                         at UniGetUI.Core.Language.LanguageEngine.LoadLanguageFile(String LangKey, Boolean ForceBundled) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.LanguageEngine\LanguageEngine.cs:line 66
[30.06.2024 09:00:28] Loaded language locale: de
[30.06.2024 09:00:29] Api auth token: ym5qofgdpt66d71gq0jbu1dv4fo7g5890k6h0ja5azw4luuofaevcurzfl9ucdjt
[30.06.2024 09:00:29] Api running on http://localhost:7058
[30.06.2024 09:00:29] Command npm was not found on the system
[30.06.2024 09:00:29] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.06.2024 09:00:29] Command dotnet.exe was not found on the system
[30.06.2024 09:00:29] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.06.2024 09:00:29] Downloaded new icons and screenshots successfully!
[30.06.2024 09:00:29] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.06.2024 09:00:29] UniGetUI is up to date
[30.06.2024 09:00:29] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.06.2024 09:00:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.06.2024 09:00:30] Command scoop was not found on the system
[30.06.2024 09:00:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.06.2024 09:00:31] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\delta\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Naive WinGet CLI Version: v1.8.1791
                      █   Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
                      █   -----  -----  -----  --------
                      █   1      8      1791   -1
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.06.2024 09:00:31] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[30.06.2024 09:00:32] Found 0 installed packages from Winget
[30.06.2024 09:00:32] Found 0 available updates from Winget
[30.06.2024 09:01:19] Found 0 available updates from Winget
[30.06.2024 09:01:22] Found 0 available updates from PowerShell
[30.06.2024 09:01:25] Found 0 installed packages from Winget
[30.06.2024 09:01:26] Found 1 installed packages from PowerShell
[30.06.2024 09:02:22] Found 0 installed packages from Winget
[30.06.2024 09:02:23] Found 1 installed packages from PowerShell
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1791   -1
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 30.06.2024 09:00:31
Process end time:   30.06.2024 09:00:31

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\delta\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 30.06.2024 09:00:31
Process end time:   30.06.2024 09:00:31

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 30.06.2024 09:00:31
Process end time:   30.06.2024 09:00:32

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : Die Benennung "﻿Set-ExecutionPolicy" wurde nicht als Name eines Cmdlet, einer Funktion, 
  einer Skriptdatei oder eines ausf�hrbaren Programms erkannt. �berpr�fen Sie die Schreibweise des Namens, oder ob der 
  Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
  In Zeile:1 Zeichen:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : Der Befehl "Get-WinGetPackage" wurde im Modul "Microsoft.WinGet.Client" gefunden, das Modul konnte 
  aber nicht geladen werden. Wenn Sie weitere Informationen w�nschen, f�hren Sie "Import-Module Microsoft.WinGet.Client" 
  aus.
  In Zeile:1 Zeichen:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 30.06.2024 09:00:31
Process end time:   30.06.2024 09:00:31

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 30.06.2024 09:00:31
Process end time:   30.06.2024 09:00:32

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : Die Benennung "﻿Set-ExecutionPolicy" wurde nicht als Name eines Cmdlet, einer Funktion, 
  einer Skriptdatei oder eines ausf�hrbaren Programms erkannt. �berpr�fen Sie die Schreibweise des Namens, oder ob der 
  Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
  In Zeile:1 Zeichen:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : Der Befehl "Get-WinGetPackage" wurde im Modul "Microsoft.WinGet.Client" gefunden, das Modul konnte 
  aber nicht geladen werden. Wenn Sie weitere Informationen w�nschen, f�hren Sie "Import-Module Microsoft.WinGet.Client" 
  aus.
  In Zeile:1 Zeichen:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\delta\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 30.06.2024 09:01:18
Process end time:   30.06.2024 09:01:19

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 30.06.2024 09:01:19
Process end time:   30.06.2024 09:01:19

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : Die Benennung "﻿Set-ExecutionPolicy" wurde nicht als Name eines Cmdlet, einer Funktion, 
  einer Skriptdatei oder eines ausf�hrbaren Programms erkannt. �berpr�fen Sie die Schreibweise des Namens, oder ob der 
  Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
  In Zeile:1 Zeichen:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : Der Befehl "Get-WinGetPackage" wurde im Modul "Microsoft.WinGet.Client" gefunden, das Modul konnte 
  aber nicht geladen werden. Wenn Sie weitere Informationen w�nschen, f�hren Sie "Import-Module Microsoft.WinGet.Client" 
  aus.
  In Zeile:1 Zeichen:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 30.06.2024 09:01:24
Process end time:   30.06.2024 09:01:25

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : Die Benennung "﻿Set-ExecutionPolicy" wurde nicht als Name eines Cmdlet, einer Funktion, 
  einer Skriptdatei oder eines ausf�hrbaren Programms erkannt. �berpr�fen Sie die Schreibweise des Namens, oder ob der 
  Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
  In Zeile:1 Zeichen:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : Der Befehl "Get-WinGetPackage" wurde im Modul "Microsoft.WinGet.Client" gefunden, das Modul konnte 
  aber nicht geladen werden. Wenn Sie weitere Informationen w�nschen, f�hren Sie "Import-Module Microsoft.WinGet.Client" 
  aus.
  In Zeile:1 Zeichen:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 30.06.2024 09:02:21
Process end time:   30.06.2024 09:02:22

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : Die Benennung "﻿Set-ExecutionPolicy" wurde nicht als Name eines Cmdlet, einer Funktion, 
  einer Skriptdatei oder eines ausf�hrbaren Programms erkannt. �berpr�fen Sie die Schreibweise des Namens, oder ob der 
  Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
  In Zeile:1 Zeichen:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : Der Befehl "Get-WinGetPackage" wurde im Modul "Microsoft.WinGet.Client" gefunden, das Modul konnte 
  aber nicht geladen werden. Wenn Sie weitere Informationen w�nschen, f�hren Sie "Import-Module Microsoft.WinGet.Client" 
  aus.
  In Zeile:1 Zeichen:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
This issue was fixed here: https://github.com/marticliment/WingetUI/commit/7de960b986bea52540c0201b01773c2668f88c28#diff-c5edf1f9e67afdabfdd3506a6233f12e5e8cfd0a078623908926a0c95e94644e

**Comment by deltapapa01** [comment]
Hi, thank you, is there a simple way to test ist?

WBR,
deltapapa

**Comment by marticliment** [comment]
You'd need to build the source code

**Comment by marticliment** [comment]
Hello,

Please try out 3.1.0 Beta 1
