### ISSUE TITLE
[BUG] Only PowerShell packages are listed in Installed Packages page.

### ISSUE THREAD

**Issue by 13regent** [marticliment/WingetUI#2368]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.0.2-beta0

### Windows version, edition and architecture

Windows 10 Pro 22H2

### Describe your issue

Only PowerShell packages are listed in the Installed Packages page. 

### Steps to reproduce the issue

Start UniGet.

### UniGetUI Log

```text
[06/30/2024 10:57:04 AM] 
                            __  __      _ ______     __  __  ______
                           / / / /___  (_) ____/__  / /_/ / / /  _/
                          / / / / __ \/ / / __/ _ \/ __/ / / // /  
                         / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                         \____/_/ /_/_/\____/\___/\__/\____/___/   
                             Welcome to UniGetUI Version 3.1.0-beta0
[06/30/2024 10:57:04 AM]
[06/30/2024 10:57:04 AM] Version Code:  3.0992
[06/30/2024 10:57:06 AM] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[06/30/2024 10:57:09 AM] LoadLanguageFile Failed for LangKey=en_US, ForceBundled=True
[06/30/2024 10:57:09 AM] System.IO.FileNotFoundException: Could not find file 'C:\Program Files\UniGetUI\Assets\Languages\lang_en_US.json'.
                         File name: 'C:\Program Files\UniGetUI\Assets\Languages\lang_en_US.json'
                            at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
                            at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                            at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                            at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                            at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
                            at System.IO.File.ReadAllText(String path, Encoding encoding)
                            at UniGetUI.Core.Language.LanguageEngine.LoadLanguageFile(String LangKey, Boolean ForceBundled) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.LanguageEngine\LanguageEngine.cs:line 66
[06/30/2024 10:57:09 AM] Loaded language locale: en
[06/30/2024 10:57:10 AM] Api auth token: 2l84bswvlpjt6yxbbbknvrr9law0yia1r040ew95m9bgympvrzv33e7oc907ftrt
[06/30/2024 10:57:12 AM] Api running on http://localhost:7058
[06/30/2024 10:57:14 AM] UniGetUI is up to date
[06/30/2024 10:57:14 AM] The restored geometry did not have exactly 5 items (found length was 1)
[06/30/2024 10:57:15 AM] Command npm was not found on the system
[06/30/2024 10:57:15 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Npm
                         █ Enabled: True
                         █ Found: False
                         █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                         █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[06/30/2024 10:57:15 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Pip
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: pip
                         █ Executable path: C:\Users\Scott\AppData\Local\Microsoft\WindowsApps\python.exe
                         █ Call arguments:  -m pip
                         █ Version: 
                         █   
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[06/30/2024 10:57:16 AM] Command scoop was not found on the system
[06/30/2024 10:57:16 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Scoop
                         █ Enabled: True
                         █ Found: False
                         █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                         █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[06/30/2024 10:57:17 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: .NET Tool
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: dotnet tool
                         █ Executable path: C:\Program Files\dotnet\dotnet.exe
                         █ Call arguments: tool
                         █ Version: 
                         █   6.0.423
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[06/30/2024 10:57:18 AM] Downloaded new icons and screenshots successfully!
[06/30/2024 10:57:22 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Chocolatey
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: choco.exe
                         █ Executable path: C:\Users\Scott\AppData\Local\UniGetUI\Chocolatey\choco.exe
                         █ Call arguments: 
                         █ Version: 
                         █   2.2.2
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[06/30/2024 10:57:23 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: PowerShell
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: powershell.exe
                         █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                         █ Call arguments:  -NoProfile -Command
                         █ Version: 
                         █   Name                           Value                                                                                   
                         █   ----                           -----                                                                                   
                         █   PSVersion                      5.1.19041.4522                                                                          
                         █   PSEdition                      Desktop                                                                                 
                         █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                         █   BuildVersion                   10.0.19041.4522                                                                         
                         █   CLRVersion                     4.0.30319.42000                                                                         
                         █   WSManStackVersion              3.0                                                                                     
                         █   PSRemotingProtocolVersion      2.3                                                                                     
                         █   SerializationVersion           1.1.0.1
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[06/30/2024 10:57:24 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Winget
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: winget.exe
                         █ Executable path: C:\Users\Scott\AppData\Local\Microsoft\WindowsApps\winget.exe
                         █ Call arguments: 
                         █ Version: 
                         █   Naive WinGet CLI Version: v1.8.1791
                         █   Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
                         █   -----  -----  -----  --------
                         █   1      8      1791   -1
                         █   Using Native WinGet helper (COM Api)
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[06/30/2024 10:57:27 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[06/30/2024 10:57:29 AM] Command dotnet-tools-outdated.exe was not found on the system
[06/30/2024 10:57:29 AM] Found 0 available updates from Pip
[06/30/2024 10:57:30 AM] Found 0 installed packages from Pip
[06/30/2024 10:57:32 AM] Found 0 installed packages from .NET Tool
[06/30/2024 10:57:34 AM] Found 0 installed packages from Chocolatey
[06/30/2024 10:57:35 AM] Found 0 available updates from Chocolatey
[06/30/2024 10:57:44 AM] Found 0 installed packages from Winget
[06/30/2024 10:57:44 AM] Found 0 available updates from Winget
[06/30/2024 10:57:44 AM] Found 0 available updates from PowerShell
[06/30/2024 10:57:44 AM] Error finding updates on manager .NET Tool
[06/30/2024 10:57:44 AM] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet-tools-outdated.exe' with working directory 'C:\Program Files\UniGetUI'. The system cannot find the file specified.
                            at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                            at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 90
                            at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
[06/30/2024 10:57:45 AM] Found 1 installed packages from PowerShell
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1791   -1
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 06/30/2024 10:57:24 AM
Process end time:   06/30/2024 10:57:24 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Scott\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 06/30/2024 10:57:24 AM
Process end time:   06/30/2024 10:57:34 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 06/30/2024 10:57:25 AM
Process end time:   06/30/2024 10:57:44 AM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : The 'Get-WinGetPackage' command was found in the module 'Microsoft.WinGet.Client', but the module 
  could not be loaded. For more information, run 'Import-Module Microsoft.WinGet.Client'.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 06/30/2024 10:57:29 AM
Process end time:   06/30/2024 10:57:29 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 06/30/2024 10:57:35 AM
Process end time:   06/30/2024 10:57:44 AM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : The 'Get-WinGetPackage' command was found in the module 'Microsoft.WinGet.Client', but the module 
  could not be loaded. For more information, run 'Import-Module Microsoft.WinGet.Client'.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————
```

### Relevant information

This issue was happening with 3.1.0 alpha as well. With the alpha, if  I tried opening and closing 3 or 4 times, the Installed Packages would then populate. Fully uninstalled alpha and installed the beta, and it it doesn't work at all now.

### Screenshots and videos

![Screenshot 2024-06-30 111701](https://github.com/marticliment/WingetUI/assets/28539673/a0517630-0dcc-4701-bed0-d4003fde04fa)

**Comment by 13regent** [comment]
I just tried opening UniGetUI and it worked normally. Not sure why it sometimes opens correctly and most of the time it does not? 

![image](https://github.com/marticliment/WingetUI/assets/28539673/b688201a-5ce7-4ab5-b244-3b75e830ec78)

**Comment by marticliment** [comment]
This issue will be fixed in the next beta, coming very soon

**Comment by 13regent** [comment]
Excellent....thanks.

**Comment by marticliment** [comment]
Hello,

Please try out 3.1.0 Beta 1
