### ISSUE TITLE
[BUG/ISSUE] Scoop not working properly in locales other than English

### ISSUE THREAD

**Issue by csolisr** [marticliment/WingetUI#688]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
When running WinGetUI in a language other than English, the parsing of Scoop commands fails as it expects the program to be always running in English. For instance, attempting to list Scoop packages with the system language set to Spanish outputs the following:

![imagen](https://user-images.githubusercontent.com/1644021/216646276-e97f8278-17c7-48f2-940f-71f335db97af.png)

(in English, the pieces of words jumbled in the middle of the list stand for "In line 1" and "Try again")

When trying to add a bucket to Scoop, it outputs a wrong error message in Spanish:

`"scoop" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable. `

(This stands for "Scoop is not recognized as an internal or external command, program or batch file")

The error above is incorrect, as running `scoop` from the terminal does show the program as running and functional - and furthermore, the program runs in English as per default.

## To Reproduce
Steps to reproduce the behaviour:
1. On a computer with a language set to other than English, install WinGetUI.
2. When requested to install Scoop, do so.
3. Go to the "Software Updates" tab.
4. See the error shown above.

## Expected behaviour
The program should be able to correctly list and manage Scoop buckets, regardless of the locale.

## Screenshots
![imagen](https://user-images.githubusercontent.com/1644021/216646276-e97f8278-17c7-48f2-940f-71f335db97af.png)

## The Log

<details>

```
C:\Users\csoli\AppData\Local\Programs\WingetUI\sudo\gsudo.exe
C:\Users\csoli\AppData\Local\Programs\WingetUI\sudo
🟢 checkQueue Thread started!
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.003000497817993164 to load all language files
🔵 Starting main application...
Scanning for instances...
Found lock file(s), reactivating...
🔵 Starting update check
b'v1.4.10173\r\n'
None
updating winget
🔵 Language file up-to-date
b''
None
list index out of range
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
b'1.2.1\r\n'
None
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
Reactivation signal ignored: RaiseWindow_[1675438766.195291]
{'wingetFound': True, 'scoopFound': False, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'Unknown', 'chocoVersion': '1.2.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
Reached main ui load milestone
🔵 Is Dark
🟢 Starting winget search, winget on C:\Users\csoli\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Discover tab loaded
🟢 Starting winget search, winget on C:\Users\csoli\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on C:\Users\csoli\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Upgrades tab loaded
🟢 Starting winget search, winget on C:\Users\csoli\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on C:\Users\csoli\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Discover tab loaded
IndexError: list index out of range
🟢 Scoop search finished
🔴 Traceback (most recent call last):

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🟢 Scoop search finished
🟢 Starting scoop search...
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Scoop bucket search finished
🟢 Main application loaded...
🟢 Chocolatey uninstallable packages search finished
🟡 Package inténtelo found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package En found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package + found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package + found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package + found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟢 Searching for string ""
🟢 Searching for string ""
Name                                                         Id                          Version      Available
🟢 Winget search finished
🟢 Searching for string ""
🟡 package Kanjozoku Game レーサー                            Stea failed parsing, going for method 2...
Kanjozoku Game レーサー                            Steam App 2073470                                  Unknown 102
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
IndexError: list index out of range
🟢 Scoop search finished
🟢 Chocolatey search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 160
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 6
None
🟢 Winget search finished
🟢 Total packages: 11335
🟢 Found reactivation lock file...
🟠 Icon inténtelo not found in json
🟠 Icon inténtelo not found in json
🟢 Starting get info for title nuevo./Inténtelo
🔵 Scoop does not support specific version installs
🟢 Starting get info for title nuevo./inténtelo
🔵 Scoop does not support specific version installs
🟢 Starting winget search, winget on C:\Users\csoli\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on C:\Users\csoli\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🔴 Traceback (most recent call last):

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🟢 Scoop search finished
🟢 Searching for string ""
Name                                                         Id                          Version      Available
🟢 Winget search finished
🟢 Searching for string ""
🟢 Chocolatey search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 6
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/choco.png
main
🟢 Waiting for install permission... title=main Scoop bucket, id=, installId=1675439009.5456626
🔵 Current program set to 1675439009.5456626
🟢 Have permission to install, starting installation threads...
🟢 winget installer assistant thread started for process <Popen: returncode: None args: 'scoop bucket add main'>
"scoop" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
1
🟢 Starting scoop search...
['inténtelo', 'de', 'nuevo.']
IndexError: list index out of range
['+', 'scoop', 'bucket', 'list']
IndexError: list index out of range
['+', '~~~~~']
IndexError: list index out of range
['+', 'FullyQualifiedErrorId', ':', 'CommandNotFoundException']
IndexError: list index out of range
🟢 Scoop bucket search finished
🟢 Starting scoop search...
['inténtelo', 'de', 'nuevo.']
IndexError: list index out of range
['+', 'scoop', 'bucket', 'list']
IndexError: list index out of range
['+', '~~~~~']
IndexError: list index out of range
['+', 'FullyQualifiedErrorId', ':', 'CommandNotFoundException']
IndexError: list index out of range
🟢 Scoop bucket search finished
🟢 Starting scoop search...
['inténtelo', 'de', 'nuevo.']
IndexError: list index out of range
['+', 'scoop', 'bucket', 'list']
IndexError: list index out of range
['+', '~~~~~']
IndexError: list index out of range
['+', 'FullyQualifiedErrorId', ':', 'CommandNotFoundException']
IndexError: list index out of range
🟢 Scoop bucket search finished
🟠 Icon + not found in json
🟠 Icon + not found in json
🟢 Starting get info for title +
🔵 Scoop does not support specific version installs
🟢 Starting get info for title +
🔵 Scoop does not support specific version installs
🟢 Starting winget search, winget on C:\Users\csoli\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on C:\Users\csoli\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🔴 Traceback (most recent call last):

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🟢 Scoop search finished
🟢 Searching for string ""
Name                                                         Id                          Version      Available
🟢 Winget search finished
🟢 Searching for string ""
🟢 Chocolatey search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 6
🔵 Sending cancel signal...
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/choco.png
🟢 Starting scoop search...
['inténtelo', 'de', 'nuevo.']
IndexError: list index out of range
['+', 'scoop', 'bucket', 'list']
IndexError: list index out of range
['+', '~~~~~']
IndexError: list index out of range
['+', 'FullyQualifiedErrorId', ':', 'CommandNotFoundException']
IndexError: list index out of range
🟢 Scoop bucket search finished
main
🟢 Waiting for install permission... title=main Scoop bucket, id=, installId=1675439355.981606
🔵 Current program set to 1675439355.981606
🟢 Have permission to install, starting installation threads...
🟢 winget installer assistant thread started for process <Popen: returncode: None args: 'scoop bucket add main'>
"scoop" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
1
🟢 Starting scoop search...
['inténtelo', 'de', 'nuevo.']
IndexError: list index out of range
['+', 'scoop', 'bucket', 'list']
IndexError: list index out of range
['+', '~~~~~']
IndexError: list index out of range
['+', 'FullyQualifiedErrorId', ':', 'CommandNotFoundException']
IndexError: list index out of range
🟢 Scoop bucket search finished
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

```

</details>

## Additional context
Fresh installation of WinGetUI and of Scoop in my computer.

**Comment by csolisr** [comment]
This might be a regression, as bug #122 (same issue but with Chinese locale) claims to have had the issue fixed. Also related to bug #427 .

**Comment by marticliment** [comment]
hi, can you please send me the location where scoop is installed?

**Comment by marticliment** [comment]
could you please install scoop from the settings window?

**Comment by csolisr** [comment]
Hello, I checked one of the other bugs and tried rebooting the computer after installing Scoop from the settings. This solved the issue for me.

**Comment by marticliment** [comment]
All right, then
