### ISSUE TITLE
[SCOOP] Invalid entries in the "Software Updates" list

### ISSUE THREAD

**Issue by oncer** [marticliment/WingetUI#827]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked that this issue is not an issue with the scoop utility, but rather with its implementation on WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the issue
There are multiple entries that do not make sense in the "Software Updates" list when Scoop is enabled.
I have one package installed in Scoop, yet there are >10 update entries, none of them show proper package names. See attached screenshot
![image](https://user-images.githubusercontent.com/119390/226578415-0c47be62-7a15-484a-9640-94dd8862f361.png)

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Software Updates'
2. See invalid entries

## The Log

<details>

```
C:\Users\ProfParzer\AppData\Local\Programs\WingetUI\sudo\gsudo.exe
C:\Users\ProfParzer\AppData\Local\Programs\WingetUI\sudo
🟢 checkQueue Thread started!
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.01997971534729004 to load all language files
🔵 Starting main application...
Scanning for instances...
Found lock file(s), reactivating...
🔵 Starting update check
🔵 Language file up-to-date
b'v1.4.10173\r\n'
None
updating winget
b'1.3.1\r\n'
None
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
b"Current Scoop version:\nv0.3.1 - Released at 2022-11-15\n\n'extras' bucket:\ncea54139e oras: Update to version 1.0.0\n\n'main' bucket:\n0b84c09af lean-cli: Update to version 1.2.0\n\n"
None
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
Reactivation signal ignored: RaiseWindow_[1679322653.6369298]
{'wingetFound': True, 'scoopFound': True, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'v0.3.1 - Released at 2022-11-15', 'chocoVersion': '1.3.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
Reached main ui load milestone
Can't disconnect
🟢 Starting winget search, winget on C:\Users\ProfParzer\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🔵 Starting choco search
🟢 Discover tab loaded
🟢 Starting choco search, choco on choco.exe...
Can't disconnect
🟢 Starting winget search, winget on C:\Users\ProfParzer\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on choco.exe...
🟢 Upgrades tab loaded
Can't disconnect
🟢 Starting winget search, winget on C:\Users\ProfParzer\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on choco.exe...
🟢 Discover tab loaded
{'System language': 'default', 'Arabic - عربي\u200e (95%)': 'ar', 'Bulgarian - български (87%)': 'bg', 'Bangla - বাংলা (25%)': 'bn', 'Catalan - Català': 'ca', 'Czech - Čeština': 'cs', 'Danish - Dansk (47%)': 'da', 'German - Deutsch': 'de', 'English - English': 'en', 'Spanish - Castellano (99%)': 'es', 'French - Français': 'fr', 'Hindi - हिंदी (75%)': 'hi', 'Hungarian - Magyar (99%)': 'hu', 'Italian - Italiano (99%)': 'it', 'Indonesian - Bahasa Indonesia (22%)': 'id', 'Japanese - 日本語 (81%)': 'ja', 'Korean - 한국어 (94%)': 'ko', 'Dutch - Nederlands': 'nl', 'Polish - Polski': 'pl', 'Portuguese (Brazil)': 'pt_BR', 'Portuguese (Portugal)': 'pt_PT', 'Russian - Русский (99%)': 'ru', 'Serbian - Srpski (20%)': 'sr', 'Slovene - Slovenščina': 'sl', 'Turkish - Türkçe (78%)': 'tr', 'Ukranian - Yкраї́нська (78%)': 'ua', 'Simplified Chinese (China)': 'zh_CN', 'Traditional Chinese (Taiwan) (99%)': 'zh_TW'}
['System language', 'Arabic - عربي\u200e (95%)', 'Bulgarian - български (87%)', 'Bangla - বাংলা (25%)', 'Catalan - Català', 'Czech - Čeština', 'Danish - Dansk (47%)', 'German - Deutsch', 'English - English', 'Spanish - Castellano (99%)', 'French - Français', 'Hindi - हिंदी (75%)', 'Hungarian - Magyar (99%)', 'Italian - Italiano (99%)', 'Indonesian - Bahasa Indonesia (22%)', 'Japanese - 日本語 (81%)', 'Korean - 한국어 (94%)', 'Dutch - Nederlands', 'Polish - Polski', 'Portuguese (Brazil)', 'Portuguese (Portugal)', 'Russian - Русский (99%)', 'Serbian - Srpski (20%)', 'Slovene - Slovenščina', 'Turkish - Türkçe (78%)', 'Ukranian - Yкраї́нська (78%)', 'Simplified Chinese (China)', 'Traditional Chinese (Taiwan) (99%)']
en
{'default': 'System language', 'ar': 'Arabic - عربي\u200e (95%)', 'bg': 'Bulgarian - български (87%)', 'bn': 'Bangla - বাংলা (25%)', 'ca': 'Catalan - Català', 'cs': 'Czech - Čeština', 'da': 'Danish - Dansk (47%)', 'de': 'German - Deutsch', 'en': 'English - English', 'es': 'Spanish - Castellano (99%)', 'fr': 'French - Français', 'hi': 'Hindi - हिंदी (75%)', 'hu': 'Hungarian - Magyar (99%)', 'it': 'Italian - Italiano (99%)', 'id': 'Indonesian - Bahasa Indonesia (22%)', 'ja': 'Japanese - 日本語 (81%)', 'ko': 'Korean - 한국어 (94%)', 'nl': 'Dutch - Nederlands', 'pl': 'Polish - Polski', 'pt_BR': 'Portuguese (Brazil)', 'pt_PT': 'Portuguese (Portugal)', 'ru': 'Russian - Русский (99%)', 'sr': 'Serbian - Srpski (20%)', 'sl': 'Slovene - Slovenščina', 'tr': 'Turkish - Türkçe (78%)', 'ua': 'Ukranian - Yкраї́нська (78%)', 'zh_CN': 'Simplified Chinese (China)', 'zh_TW': 'Traditional Chinese (Taiwan) (99%)'}
Can't disconnect
🟢 Starting scoop search...
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Chocolatey uninstallable packages search finished
🟢 Main application loaded...
Win32Mica Error: win32 version 19044 is not supported
50
🟢 Scoop bucket search finished
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴 IndexError: list index out of range

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴 IndexError: list index out of range

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴 IndexError: list index out of range

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴 IndexError: list index out of range

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴 IndexError: list index out of range

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴   File ".\scoopHelpers.py", line 87, in searchForUpdates

🔴 IndexError: list index out of range

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🟢 Scoop search finished
🟢 Searching for string ""
🟡 Package but found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package To found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package git found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package 'C:/Users/ProfParzer/scoop/apps/scoop/current' found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package but found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package To found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package git found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package 'C:/Users/ProfParzer/scoop/apps/scoop/current' found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package but found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package To found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟡 Package git found in the updates section but not in the installed one, might be a temporal issue, retrying in 3 seconds...
🟢 Searching for string ""
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Chocolatey search finished
🟢 Searching for string ""
Name                                                Id                                    Version          Available
Unity.Unity.2021 was blackisted
Tiled.Tiled was blackisted
🟢 Winget search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 25
🟡 package 中文(简体)本地体验包                           Microsoft failed parsing, going for method 2...
中文(简体)本地体验包                           Microsoft.LanguageExperiencePackzh-CN_8wekyb3… 19041.57.180.0 94
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 202
🟠 Package but found in the updates section but not in the installed one, happened again
🟠 Package To found in the updates section but not in the installed one, happened again
🟠 Package git found in the updates section but not in the installed one, happened again
🟠 Package but found in the updates section but not in the installed one, happened again
🟠 Package 'C:/Users/ProfParzer/scoop/apps/scoop/current' found in the updates section but not in the installed one, happened again
🟠 Package To found in the updates section but not in the installed one, happened again
🟠 Package git found in the updates section but not in the installed one, happened again
🟠 Package 'C:/Users/ProfParzer/scoop/apps/scoop/current' found in the updates section but not in the installed one, happened again
🟠 Package but found in the updates section but not in the installed one, happened again
🟠 Package To found in the updates section but not in the installed one, happened again
🟠 Package git found in the updates section but not in the installed one, happened again
None
🟢 Winget search finished
IndexError: list index out of range
.... (repeats ~2900x) ....
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
IndexError: list index out of range
🟢 Scoop search finished
🟢 Total packages: 4331
🔵 Copying log to the clipboard...
```
</details>

## Additional context
Scoop was installed through WingetUI. There is one scoop package installed.

**Comment by ppvnf** [comment]
wouldn't it be better if Scoop were bundled like Winget and Chocolatey?

**Comment by marticliment** [comment]
Scoop cannot be easily b undled, since the installation direactory is where apps are installed (and it needs different env vars to be set up), and this could cause issues with the updater.
